// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Multirate_v3_FIR_filter_transposed (
        ap_ready,
        FIR_delays_read,
        FIR_delays_read_25,
        FIR_delays_read_26,
        FIR_delays_read_27,
        FIR_coe_read,
        FIR_coe_read_14,
        FIR_coe_read_15,
        FIR_coe_read_16,
        FIR_coe_read_17,
        x_n,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_rst
);


output   ap_ready;
input  [31:0] FIR_delays_read;
input  [31:0] FIR_delays_read_25;
input  [31:0] FIR_delays_read_26;
input  [31:0] FIR_delays_read_27;
input  [9:0] FIR_coe_read;
input  [12:0] FIR_coe_read_14;
input  [13:0] FIR_coe_read_15;
input  [12:0] FIR_coe_read_16;
input  [9:0] FIR_coe_read_17;
input  [15:0] x_n;
output  [15:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
input   ap_rst;

wire  signed [15:0] sext_ln84_fu_116_p0;
wire   [24:0] mul_ln84_fu_124_p2;
wire   [25:0] shl_ln_fu_130_p3;
wire  signed [31:0] sext_ln84_6_fu_138_p1;
wire   [31:0] add_ln84_fu_142_p2;
wire  signed [15:0] sext_ln87_fu_158_p0;
wire  signed [15:0] sext_ln87_3_fu_162_p0;
wire  signed [15:0] sext_ln87_4_fu_166_p0;
wire  signed [15:0] mul_ln87_3_fu_174_p0;
wire  signed [28:0] sext_ln87_4_fu_166_p1;
wire   [28:0] mul_ln87_3_fu_174_p2;
wire   [29:0] tmp_fu_180_p3;
wire  signed [31:0] sext_ln87_6_fu_188_p1;
wire   [13:0] mul_ln87_fu_202_p1;
wire   [29:0] mul_ln87_fu_202_p2;
wire   [30:0] tmp_4_fu_208_p3;
wire  signed [15:0] mul_ln87_4_fu_224_p0;
wire   [28:0] mul_ln87_4_fu_224_p2;
wire   [29:0] tmp_5_fu_230_p3;
wire   [25:0] mul_ln87_5_fu_246_p2;
wire   [26:0] tmp_6_fu_252_p3;
wire  signed [31:0] sext_ln87_7_fu_216_p1;
wire  signed [31:0] sext_ln87_9_fu_238_p1;
wire   [31:0] add_ln87_fu_192_p2;
wire   [31:0] add_ln87_4_fu_264_p2;
wire   [31:0] add_ln87_5_fu_270_p2;
wire  signed [31:0] sext_ln87_11_fu_260_p1;
wire   [29:0] mul_ln87_fu_202_p10;

Multirate_v3_mul_10s_16s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 25 ))
mul_10s_16s_25_1_1_U1(
    .din0(FIR_coe_read),
    .din1(sext_ln84_fu_116_p0),
    .dout(mul_ln84_fu_124_p2)
);

Multirate_v3_mul_16s_13s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mul_16s_13s_29_1_1_U2(
    .din0(mul_ln87_3_fu_174_p0),
    .din1(FIR_coe_read_14),
    .dout(mul_ln87_3_fu_174_p2)
);

Multirate_v3_mul_16s_14ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 30 ))
mul_16s_14ns_30_1_1_U3(
    .din0(sext_ln87_3_fu_162_p0),
    .din1(mul_ln87_fu_202_p1),
    .dout(mul_ln87_fu_202_p2)
);

Multirate_v3_mul_16s_13s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mul_16s_13s_29_1_1_U4(
    .din0(mul_ln87_4_fu_224_p0),
    .din1(FIR_coe_read_16),
    .dout(mul_ln87_4_fu_224_p2)
);

Multirate_v3_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U5(
    .din0(sext_ln87_fu_158_p0),
    .din1(FIR_coe_read_17),
    .dout(mul_ln87_5_fu_246_p2)
);

assign add_ln84_fu_142_p2 = ($signed(sext_ln84_6_fu_138_p1) + $signed(FIR_delays_read));

assign add_ln87_4_fu_264_p2 = ($signed(sext_ln87_7_fu_216_p1) + $signed(FIR_delays_read_26));

assign add_ln87_5_fu_270_p2 = ($signed(sext_ln87_9_fu_238_p1) + $signed(FIR_delays_read_27));

assign add_ln87_fu_192_p2 = ($signed(sext_ln87_6_fu_188_p1) + $signed(FIR_delays_read_25));

assign ap_ready = 1'b1;

assign mul_ln87_fu_202_p10 = FIR_coe_read_15;

assign sext_ln84_6_fu_138_p1 = $signed(shl_ln_fu_130_p3);

assign sext_ln87_11_fu_260_p1 = $signed(tmp_6_fu_252_p3);

assign sext_ln87_4_fu_166_p1 = sext_ln87_4_fu_166_p0;

assign sext_ln87_6_fu_188_p1 = $signed(tmp_fu_180_p3);

assign sext_ln87_7_fu_216_p1 = $signed(tmp_4_fu_208_p3);

assign sext_ln87_9_fu_238_p1 = $signed(tmp_5_fu_230_p3);

assign shl_ln_fu_130_p3 = {{mul_ln84_fu_124_p2}, {1'd0}};

assign tmp_4_fu_208_p3 = {{mul_ln87_fu_202_p2}, {1'd0}};

assign tmp_5_fu_230_p3 = {{mul_ln87_4_fu_224_p2}, {1'd0}};

assign tmp_6_fu_252_p3 = {{mul_ln87_5_fu_246_p2}, {1'd0}};

assign tmp_fu_180_p3 = {{mul_ln87_3_fu_174_p2}, {1'd0}};

assign ap_return_0 = {{add_ln84_fu_142_p2[31:16]}};

assign ap_return_1 = add_ln87_fu_192_p2;

assign ap_return_2 = add_ln87_4_fu_264_p2;

assign ap_return_3 = add_ln87_5_fu_270_p2;

assign ap_return_4 = sext_ln87_11_fu_260_p1;

assign mul_ln87_3_fu_174_p0 = sext_ln87_4_fu_166_p1;

assign mul_ln87_4_fu_224_p0 = sext_ln87_4_fu_166_p1;

assign mul_ln87_fu_202_p1 = mul_ln87_fu_202_p10;

assign sext_ln84_fu_116_p0 = x_n;

assign sext_ln87_3_fu_162_p0 = x_n;

assign sext_ln87_4_fu_166_p0 = x_n;

assign sext_ln87_fu_158_p0 = x_n;

endmodule //Multirate_v3_FIR_filter_transposed
