-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FIR_Cascade_v2_FIR_filter_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    FIR_delays_read : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_read_9 : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_read_10 : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_read_11 : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_read_12 : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_write : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of FIR_Cascade_v2_FIR_filter_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_4D04 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000100110100000100";
    constant ap_const_lv28_2CA : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000001011001010";
    constant ap_const_lv31_7FFFEFD4 : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111110111111010100";

attribute shreg_extract : string;
    signal FIR_delays_write_read_reg_161 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal FIR_delays_write_read_reg_161_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_write_read_reg_161_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_write_read_reg_161_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_write_read_reg_161_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_1_reg_167 : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_1_reg_167_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_1_reg_167_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_1_reg_167_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_1_reg_167_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_2_reg_173 : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_2_reg_173_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_2_reg_173_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_2_reg_173_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_2_reg_173_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_3_reg_178 : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_3_reg_178_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_3_reg_178_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_3_reg_178_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_3_reg_178_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_4_reg_183 : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_4_reg_183_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_4_reg_183_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_4_reg_183_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_4_reg_183_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read11_reg_189 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_132_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_140_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln66_1_fu_72_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sext_ln66_2_fu_76_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_150_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_132_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_140_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_150_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_132_ce : STD_LOGIC;
    signal grp_fu_140_ce : STD_LOGIC;
    signal grp_fu_150_ce : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;
    signal FIR_delays_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_9_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_10_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_11_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_12_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_write_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_3_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_4_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_5_int_reg : STD_LOGIC_VECTOR (15 downto 0);

    component FIR_Cascade_v2_am_addmul_16s_16s_15ns_32_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_Cascade_v2_ama_addmuladd_16s_16s_10ns_32s_32_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (9 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_Cascade_v2_ama_addmuladd_16s_16s_14s_32s_32_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (13 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    am_addmul_16s_16s_15ns_32_4_0_U12 : component FIR_Cascade_v2_am_addmul_16s_16s_15ns_32_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 15,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sext_ln66_2_fu_76_p0,
        din1 => sext_ln66_1_fu_72_p0,
        din2 => grp_fu_132_p2,
        ce => grp_fu_132_ce,
        dout => grp_fu_132_p3);

    ama_addmuladd_16s_16s_10ns_32s_32_4_0_U13 : component FIR_Cascade_v2_ama_addmuladd_16s_16s_10ns_32s_32_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 10,
        din3_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => FIR_delays_read11_reg_189,
        din1 => FIR_delays_write_read_reg_161,
        din2 => grp_fu_140_p2,
        din3 => grp_fu_132_p3,
        ce => grp_fu_140_ce,
        dout => grp_fu_140_p4);

    ama_addmuladd_16s_16s_14s_32s_32_4_0_U14 : component FIR_Cascade_v2_ama_addmuladd_16s_16s_14s_32s_32_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 14,
        din3_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => FIR_delays_read_4_reg_183_pp0_iter1_reg,
        din1 => FIR_delays_read_1_reg_167_pp0_iter1_reg,
        din2 => grp_fu_150_p2,
        din3 => grp_fu_140_p4,
        ce => grp_fu_150_ce,
        dout => grp_fu_150_p4);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                FIR_delays_read11_reg_189 <= FIR_delays_read_int_reg;
                FIR_delays_read_1_reg_167 <= FIR_delays_read_12_int_reg;
                FIR_delays_read_1_reg_167_pp0_iter1_reg <= FIR_delays_read_1_reg_167;
                FIR_delays_read_1_reg_167_pp0_iter2_reg <= FIR_delays_read_1_reg_167_pp0_iter1_reg;
                FIR_delays_read_1_reg_167_pp0_iter3_reg <= FIR_delays_read_1_reg_167_pp0_iter2_reg;
                FIR_delays_read_1_reg_167_pp0_iter4_reg <= FIR_delays_read_1_reg_167_pp0_iter3_reg;
                FIR_delays_read_2_reg_173 <= FIR_delays_read_11_int_reg;
                FIR_delays_read_2_reg_173_pp0_iter1_reg <= FIR_delays_read_2_reg_173;
                FIR_delays_read_2_reg_173_pp0_iter2_reg <= FIR_delays_read_2_reg_173_pp0_iter1_reg;
                FIR_delays_read_2_reg_173_pp0_iter3_reg <= FIR_delays_read_2_reg_173_pp0_iter2_reg;
                FIR_delays_read_2_reg_173_pp0_iter4_reg <= FIR_delays_read_2_reg_173_pp0_iter3_reg;
                FIR_delays_read_3_reg_178 <= FIR_delays_read_10_int_reg;
                FIR_delays_read_3_reg_178_pp0_iter1_reg <= FIR_delays_read_3_reg_178;
                FIR_delays_read_3_reg_178_pp0_iter2_reg <= FIR_delays_read_3_reg_178_pp0_iter1_reg;
                FIR_delays_read_3_reg_178_pp0_iter3_reg <= FIR_delays_read_3_reg_178_pp0_iter2_reg;
                FIR_delays_read_3_reg_178_pp0_iter4_reg <= FIR_delays_read_3_reg_178_pp0_iter3_reg;
                FIR_delays_read_4_reg_183 <= FIR_delays_read_9_int_reg;
                FIR_delays_read_4_reg_183_pp0_iter1_reg <= FIR_delays_read_4_reg_183;
                FIR_delays_read_4_reg_183_pp0_iter2_reg <= FIR_delays_read_4_reg_183_pp0_iter1_reg;
                FIR_delays_read_4_reg_183_pp0_iter3_reg <= FIR_delays_read_4_reg_183_pp0_iter2_reg;
                FIR_delays_read_4_reg_183_pp0_iter4_reg <= FIR_delays_read_4_reg_183_pp0_iter3_reg;
                FIR_delays_write_read_reg_161 <= FIR_delays_write_int_reg;
                FIR_delays_write_read_reg_161_pp0_iter1_reg <= FIR_delays_write_read_reg_161;
                FIR_delays_write_read_reg_161_pp0_iter2_reg <= FIR_delays_write_read_reg_161_pp0_iter1_reg;
                FIR_delays_write_read_reg_161_pp0_iter3_reg <= FIR_delays_write_read_reg_161_pp0_iter2_reg;
                FIR_delays_write_read_reg_161_pp0_iter4_reg <= FIR_delays_write_read_reg_161_pp0_iter3_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                FIR_delays_read_10_int_reg <= FIR_delays_read_10;
                FIR_delays_read_11_int_reg <= FIR_delays_read_11;
                FIR_delays_read_12_int_reg <= FIR_delays_read_12;
                FIR_delays_read_9_int_reg <= FIR_delays_read_9;
                FIR_delays_read_int_reg <= FIR_delays_read;
                FIR_delays_write_int_reg <= FIR_delays_write;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= grp_fu_150_p4(31 downto 16);
                ap_return_1_int_reg <= FIR_delays_read_4_reg_183_pp0_iter4_reg;
                ap_return_2_int_reg <= FIR_delays_read_3_reg_178_pp0_iter4_reg;
                ap_return_3_int_reg <= FIR_delays_read_2_reg_173_pp0_iter4_reg;
                ap_return_4_int_reg <= FIR_delays_read_1_reg_167_pp0_iter4_reg;
                ap_return_5_int_reg <= FIR_delays_write_read_reg_161_pp0_iter4_reg;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(grp_fu_150_p4, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= grp_fu_150_p4(31 downto 16);
        else 
            ap_return_0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_1_assign_proc : process(FIR_delays_read_4_reg_183_pp0_iter4_reg, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= FIR_delays_read_4_reg_183_pp0_iter4_reg;
        else 
            ap_return_1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_2_assign_proc : process(FIR_delays_read_3_reg_178_pp0_iter4_reg, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= FIR_delays_read_3_reg_178_pp0_iter4_reg;
        else 
            ap_return_2 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_3_assign_proc : process(FIR_delays_read_2_reg_173_pp0_iter4_reg, ap_ce_reg, ap_return_3_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_3 <= ap_return_3_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_3 <= FIR_delays_read_2_reg_173_pp0_iter4_reg;
        else 
            ap_return_3 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_4_assign_proc : process(FIR_delays_read_1_reg_167_pp0_iter4_reg, ap_ce_reg, ap_return_4_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_4 <= ap_return_4_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_4 <= FIR_delays_read_1_reg_167_pp0_iter4_reg;
        else 
            ap_return_4 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_5_assign_proc : process(FIR_delays_write_read_reg_161_pp0_iter4_reg, ap_ce_reg, ap_return_5_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_5 <= ap_return_5_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_5 <= FIR_delays_write_read_reg_161_pp0_iter4_reg;
        else 
            ap_return_5 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_132_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_132_ce <= ap_const_logic_1;
        else 
            grp_fu_132_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_132_p2 <= ap_const_lv32_4D04(15 - 1 downto 0);

    grp_fu_140_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_140_ce <= ap_const_logic_1;
        else 
            grp_fu_140_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_140_p2 <= ap_const_lv28_2CA(10 - 1 downto 0);

    grp_fu_150_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_150_ce <= ap_const_logic_1;
        else 
            grp_fu_150_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_150_p2 <= ap_const_lv31_7FFFEFD4(14 - 1 downto 0);
    sext_ln66_1_fu_72_p0 <= FIR_delays_read_11_int_reg;
    sext_ln66_2_fu_76_p0 <= FIR_delays_read_10_int_reg;
end behav;
