-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FIR_Halfband_v1_FIR_filter_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    FIR_delays_read : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_read_21 : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_read_22 : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_read_23 : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_read_24 : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_write : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of FIR_Halfband_v1_FIR_filter_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_4D2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000100110100101100";
    constant ap_const_lv28_34C : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000001101001100";
    constant ap_const_lv31_7FFFEFB6 : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111110111110110110";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal FIR_delays_write_read_reg_161 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal FIR_delays_write_read_reg_161_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_write_read_reg_161_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_write_read_reg_161_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_write_read_reg_161_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_13_reg_167 : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_13_reg_167_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_13_reg_167_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_13_reg_167_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_13_reg_167_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_14_reg_173 : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_14_reg_173_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_14_reg_173_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_14_reg_173_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_14_reg_173_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_15_reg_178 : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_15_reg_178_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_15_reg_178_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_15_reg_178_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_15_reg_178_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_16_reg_183 : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_16_reg_183_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_16_reg_183_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_16_reg_183_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_16_reg_183_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read11_reg_189 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_132_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_140_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln71_3_fu_72_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sext_ln71_4_fu_76_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_150_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_132_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_140_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_150_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal FIR_delays_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_21_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_22_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_23_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_24_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_write_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component FIR_Halfband_v1_am_addmul_16s_16s_15ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_Halfband_v1_ama_addmuladd_16s_16s_10ns_32s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (9 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_Halfband_v1_ama_addmuladd_16s_16s_14s_32s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (13 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    am_addmul_16s_16s_15ns_32_4_1_U90 : component FIR_Halfband_v1_am_addmul_16s_16s_15ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 15,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sext_ln71_4_fu_76_p0,
        din1 => sext_ln71_3_fu_72_p0,
        din2 => grp_fu_132_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_132_p3);

    ama_addmuladd_16s_16s_10ns_32s_32_4_1_U91 : component FIR_Halfband_v1_ama_addmuladd_16s_16s_10ns_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 10,
        din3_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => FIR_delays_read11_reg_189,
        din1 => FIR_delays_write_read_reg_161,
        din2 => grp_fu_140_p2,
        din3 => grp_fu_132_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_140_p4);

    ama_addmuladd_16s_16s_14s_32s_32_4_1_U92 : component FIR_Halfband_v1_ama_addmuladd_16s_16s_14s_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 14,
        din3_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => FIR_delays_read_16_reg_183_pp0_iter1_reg,
        din1 => FIR_delays_read_13_reg_167_pp0_iter1_reg,
        din2 => grp_fu_150_p2,
        din3 => grp_fu_140_p4,
        ce => ap_const_logic_1,
        dout => grp_fu_150_p4);





    FIR_delays_read_21_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            FIR_delays_read_21_int_reg <= FIR_delays_read_21;
        end if;
    end process;

    FIR_delays_read_22_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            FIR_delays_read_22_int_reg <= FIR_delays_read_22;
        end if;
    end process;

    FIR_delays_read_23_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            FIR_delays_read_23_int_reg <= FIR_delays_read_23;
        end if;
    end process;

    FIR_delays_read_24_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            FIR_delays_read_24_int_reg <= FIR_delays_read_24;
        end if;
    end process;

    FIR_delays_read_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            FIR_delays_read_int_reg <= FIR_delays_read;
        end if;
    end process;

    FIR_delays_write_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            FIR_delays_write_int_reg <= FIR_delays_write;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                FIR_delays_read11_reg_189 <= FIR_delays_read_int_reg;
                FIR_delays_read_13_reg_167 <= FIR_delays_read_24_int_reg;
                FIR_delays_read_13_reg_167_pp0_iter1_reg <= FIR_delays_read_13_reg_167;
                FIR_delays_read_13_reg_167_pp0_iter2_reg <= FIR_delays_read_13_reg_167_pp0_iter1_reg;
                FIR_delays_read_13_reg_167_pp0_iter3_reg <= FIR_delays_read_13_reg_167_pp0_iter2_reg;
                FIR_delays_read_13_reg_167_pp0_iter4_reg <= FIR_delays_read_13_reg_167_pp0_iter3_reg;
                FIR_delays_read_14_reg_173 <= FIR_delays_read_23_int_reg;
                FIR_delays_read_14_reg_173_pp0_iter1_reg <= FIR_delays_read_14_reg_173;
                FIR_delays_read_14_reg_173_pp0_iter2_reg <= FIR_delays_read_14_reg_173_pp0_iter1_reg;
                FIR_delays_read_14_reg_173_pp0_iter3_reg <= FIR_delays_read_14_reg_173_pp0_iter2_reg;
                FIR_delays_read_14_reg_173_pp0_iter4_reg <= FIR_delays_read_14_reg_173_pp0_iter3_reg;
                FIR_delays_read_15_reg_178 <= FIR_delays_read_22_int_reg;
                FIR_delays_read_15_reg_178_pp0_iter1_reg <= FIR_delays_read_15_reg_178;
                FIR_delays_read_15_reg_178_pp0_iter2_reg <= FIR_delays_read_15_reg_178_pp0_iter1_reg;
                FIR_delays_read_15_reg_178_pp0_iter3_reg <= FIR_delays_read_15_reg_178_pp0_iter2_reg;
                FIR_delays_read_15_reg_178_pp0_iter4_reg <= FIR_delays_read_15_reg_178_pp0_iter3_reg;
                FIR_delays_read_16_reg_183 <= FIR_delays_read_21_int_reg;
                FIR_delays_read_16_reg_183_pp0_iter1_reg <= FIR_delays_read_16_reg_183;
                FIR_delays_read_16_reg_183_pp0_iter2_reg <= FIR_delays_read_16_reg_183_pp0_iter1_reg;
                FIR_delays_read_16_reg_183_pp0_iter3_reg <= FIR_delays_read_16_reg_183_pp0_iter2_reg;
                FIR_delays_read_16_reg_183_pp0_iter4_reg <= FIR_delays_read_16_reg_183_pp0_iter3_reg;
                FIR_delays_write_read_reg_161 <= FIR_delays_write_int_reg;
                FIR_delays_write_read_reg_161_pp0_iter1_reg <= FIR_delays_write_read_reg_161;
                FIR_delays_write_read_reg_161_pp0_iter2_reg <= FIR_delays_write_read_reg_161_pp0_iter1_reg;
                FIR_delays_write_read_reg_161_pp0_iter3_reg <= FIR_delays_write_read_reg_161_pp0_iter2_reg;
                FIR_delays_write_read_reg_161_pp0_iter4_reg <= FIR_delays_write_read_reg_161_pp0_iter3_reg;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return_0 <= grp_fu_150_p4(31 downto 16);
    ap_return_1 <= FIR_delays_read_16_reg_183_pp0_iter4_reg;
    ap_return_2 <= FIR_delays_read_15_reg_178_pp0_iter4_reg;
    ap_return_3 <= FIR_delays_read_14_reg_173_pp0_iter4_reg;
    ap_return_4 <= FIR_delays_read_13_reg_167_pp0_iter4_reg;
    ap_return_5 <= FIR_delays_write_read_reg_161_pp0_iter4_reg;
    grp_fu_132_p2 <= ap_const_lv32_4D2C(15 - 1 downto 0);
    grp_fu_140_p2 <= ap_const_lv28_34C(10 - 1 downto 0);
    grp_fu_150_p2 <= ap_const_lv31_7FFFEFB6(14 - 1 downto 0);
    sext_ln71_3_fu_72_p0 <= FIR_delays_read_23_int_reg;
    sext_ln71_4_fu_76_p0 <= FIR_delays_read_22_int_reg;
end behav;
