-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FIR_Cascade_v2_FIR_filter is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    FIR_delays_read : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_read_28 : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_coe_0_0_val : IN STD_LOGIC_VECTOR (12 downto 0);
    FIR_coe_0_2_val : IN STD_LOGIC_VECTOR (12 downto 0);
    FIR_delays_write : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of FIR_Cascade_v2_FIR_filter is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_76EE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000111011011101110";

attribute shreg_extract : string;
    signal FIR_delays_write_read_reg_143 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal FIR_delays_write_read_reg_143_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_write_read_reg_143_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_write_read_reg_143_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_coe_0_2_val_read_reg_148 : STD_LOGIC_VECTOR (12 downto 0);
    signal FIR_coe_0_2_val_read_reg_148_pp0_iter1_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal FIR_delays_read_25_reg_153 : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_25_reg_153_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_25_reg_153_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_25_reg_153_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_26_reg_159 : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_26_reg_159_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln66_1_fu_83_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal FIR_delays_write_cast_fu_66_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal grp_fu_125_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal tmp_1_fu_89_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_fu_134_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_134_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_125_ce : STD_LOGIC;
    signal grp_fu_134_ce : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;
    signal FIR_delays_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_28_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_coe_0_0_val_int_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal FIR_coe_0_2_val_int_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal FIR_delays_write_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (15 downto 0);

    component FIR_Cascade_v2_mul_16s_13s_29_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component FIR_Cascade_v2_mac_muladd_16s_13s_29s_29_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        din2 : IN STD_LOGIC_VECTOR (28 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (28 downto 0) );
    end component;


    component FIR_Cascade_v2_mac_muladd_16s_15ns_30s_32_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (29 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    mul_16s_13s_29_1_0_U1 : component FIR_Cascade_v2_mul_16s_13s_29_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 29)
    port map (
        din0 => FIR_delays_read_26_reg_159_pp0_iter1_reg,
        din1 => FIR_coe_0_2_val_read_reg_148_pp0_iter1_reg,
        dout => mul_ln66_1_fu_83_p2);

    mac_muladd_16s_13s_29s_29_4_0_U2 : component FIR_Cascade_v2_mac_muladd_16s_13s_29s_29_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        din2_WIDTH => 29,
        dout_WIDTH => 29)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => FIR_delays_write_cast_fu_66_p0,
        din1 => FIR_coe_0_0_val_int_reg,
        din2 => mul_ln66_1_fu_83_p2,
        ce => grp_fu_125_ce,
        dout => grp_fu_125_p3);

    mac_muladd_16s_15ns_30s_32_4_0_U3 : component FIR_Cascade_v2_mac_muladd_16s_15ns_30s_32_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 30,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => FIR_delays_read_25_reg_153,
        din1 => grp_fu_134_p1,
        din2 => tmp_1_fu_89_p3,
        ce => grp_fu_134_ce,
        dout => grp_fu_134_p3);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                FIR_coe_0_0_val_int_reg <= FIR_coe_0_0_val;
                FIR_coe_0_2_val_int_reg <= FIR_coe_0_2_val;
                FIR_delays_read_28_int_reg <= FIR_delays_read_28;
                FIR_delays_read_int_reg <= FIR_delays_read;
                FIR_delays_write_int_reg <= FIR_delays_write;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                FIR_coe_0_2_val_read_reg_148 <= FIR_coe_0_2_val_int_reg;
                FIR_coe_0_2_val_read_reg_148_pp0_iter1_reg <= FIR_coe_0_2_val_read_reg_148;
                FIR_delays_read_25_reg_153 <= FIR_delays_read_28_int_reg;
                FIR_delays_read_25_reg_153_pp0_iter1_reg <= FIR_delays_read_25_reg_153;
                FIR_delays_read_25_reg_153_pp0_iter2_reg <= FIR_delays_read_25_reg_153_pp0_iter1_reg;
                FIR_delays_read_25_reg_153_pp0_iter3_reg <= FIR_delays_read_25_reg_153_pp0_iter2_reg;
                FIR_delays_read_26_reg_159 <= FIR_delays_read_int_reg;
                FIR_delays_read_26_reg_159_pp0_iter1_reg <= FIR_delays_read_26_reg_159;
                FIR_delays_write_read_reg_143 <= FIR_delays_write_int_reg;
                FIR_delays_write_read_reg_143_pp0_iter1_reg <= FIR_delays_write_read_reg_143;
                FIR_delays_write_read_reg_143_pp0_iter2_reg <= FIR_delays_write_read_reg_143_pp0_iter1_reg;
                FIR_delays_write_read_reg_143_pp0_iter3_reg <= FIR_delays_write_read_reg_143_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= grp_fu_134_p3(31 downto 16);
                ap_return_1_int_reg <= FIR_delays_read_25_reg_153_pp0_iter3_reg;
                ap_return_2_int_reg <= FIR_delays_write_read_reg_143_pp0_iter3_reg;
            end if;
        end if;
    end process;
    FIR_delays_write_cast_fu_66_p0 <= FIR_delays_write_int_reg;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(grp_fu_134_p3, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= grp_fu_134_p3(31 downto 16);
        else 
            ap_return_0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_1_assign_proc : process(FIR_delays_read_25_reg_153_pp0_iter3_reg, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= FIR_delays_read_25_reg_153_pp0_iter3_reg;
        else 
            ap_return_1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_2_assign_proc : process(FIR_delays_write_read_reg_143_pp0_iter3_reg, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= FIR_delays_write_read_reg_143_pp0_iter3_reg;
        else 
            ap_return_2 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_125_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_125_ce <= ap_const_logic_1;
        else 
            grp_fu_125_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_134_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_134_ce <= ap_const_logic_1;
        else 
            grp_fu_134_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_134_p1 <= ap_const_lv32_76EE(15 - 1 downto 0);
    tmp_1_fu_89_p3 <= (grp_fu_125_p3 & ap_const_lv1_0);
end behav;
