-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FIR_Halfband_v1_FIR_filter_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    FIR_delays_read : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_read_8 : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_read_9 : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_write : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of FIR_Halfband_v1_FIR_filter_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_48E6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000100100011100110";
    constant ap_const_lv30_3FFFF706 : STD_LOGIC_VECTOR (29 downto 0) := "111111111111111111011100000110";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal FIR_delays_write_read_reg_117 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal FIR_delays_write_read_reg_117_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_write_read_reg_117_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_write_read_reg_117_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_1_reg_123 : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_1_reg_123_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_1_reg_123_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_1_reg_123_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_2_reg_128 : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_2_reg_128_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_2_reg_128_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_2_reg_128_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_5_reg_133 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_98_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln71_fu_54_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sext_ln71_1_fu_58_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_106_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_98_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_106_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal FIR_delays_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_8_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_9_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_write_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component FIR_Halfband_v1_am_addmul_16s_16s_15ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FIR_Halfband_v1_ama_addmuladd_16s_16s_13s_32s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (12 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    am_addmul_16s_16s_15ns_32_4_1_U100 : component FIR_Halfband_v1_am_addmul_16s_16s_15ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 15,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => sext_ln71_1_fu_58_p0,
        din1 => sext_ln71_fu_54_p0,
        din2 => grp_fu_98_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_98_p3);

    ama_addmuladd_16s_16s_13s_32s_32_4_1_U101 : component FIR_Halfband_v1_ama_addmuladd_16s_16s_13s_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 13,
        din3_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => FIR_delays_read_5_reg_133,
        din1 => FIR_delays_write_read_reg_117,
        din2 => grp_fu_106_p2,
        din3 => grp_fu_98_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_106_p4);





    FIR_delays_read_8_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            FIR_delays_read_8_int_reg <= FIR_delays_read_8;
        end if;
    end process;

    FIR_delays_read_9_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            FIR_delays_read_9_int_reg <= FIR_delays_read_9;
        end if;
    end process;

    FIR_delays_read_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            FIR_delays_read_int_reg <= FIR_delays_read;
        end if;
    end process;

    FIR_delays_write_int_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            FIR_delays_write_int_reg <= FIR_delays_write;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                FIR_delays_read_1_reg_123 <= FIR_delays_read_9_int_reg;
                FIR_delays_read_1_reg_123_pp0_iter1_reg <= FIR_delays_read_1_reg_123;
                FIR_delays_read_1_reg_123_pp0_iter2_reg <= FIR_delays_read_1_reg_123_pp0_iter1_reg;
                FIR_delays_read_1_reg_123_pp0_iter3_reg <= FIR_delays_read_1_reg_123_pp0_iter2_reg;
                FIR_delays_read_2_reg_128 <= FIR_delays_read_8_int_reg;
                FIR_delays_read_2_reg_128_pp0_iter1_reg <= FIR_delays_read_2_reg_128;
                FIR_delays_read_2_reg_128_pp0_iter2_reg <= FIR_delays_read_2_reg_128_pp0_iter1_reg;
                FIR_delays_read_2_reg_128_pp0_iter3_reg <= FIR_delays_read_2_reg_128_pp0_iter2_reg;
                FIR_delays_read_5_reg_133 <= FIR_delays_read_int_reg;
                FIR_delays_write_read_reg_117 <= FIR_delays_write_int_reg;
                FIR_delays_write_read_reg_117_pp0_iter1_reg <= FIR_delays_write_read_reg_117;
                FIR_delays_write_read_reg_117_pp0_iter2_reg <= FIR_delays_write_read_reg_117_pp0_iter1_reg;
                FIR_delays_write_read_reg_117_pp0_iter3_reg <= FIR_delays_write_read_reg_117_pp0_iter2_reg;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return_0 <= grp_fu_106_p4(31 downto 16);
    ap_return_1 <= FIR_delays_read_2_reg_128_pp0_iter3_reg;
    ap_return_2 <= FIR_delays_read_1_reg_123_pp0_iter3_reg;
    ap_return_3 <= FIR_delays_write_read_reg_117_pp0_iter3_reg;
    grp_fu_106_p2 <= ap_const_lv30_3FFFF706(13 - 1 downto 0);
    grp_fu_98_p2 <= ap_const_lv32_48E6(15 - 1 downto 0);
    sext_ln71_1_fu_58_p0 <= FIR_delays_read_8_int_reg;
    sext_ln71_fu_54_p0 <= FIR_delays_read_9_int_reg;
end behav;
