// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="FIR_Halfband_v1_FIR_Halfband_v1,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.736000,HLS_SYN_LAT=7,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=5876,HLS_SYN_LUT=2766,HLS_VERSION=2024_2}" *)

module FIR_Halfband_v1 (
        ap_clk,
        ap_rst_n,
        input_r_TDATA,
        input_r_TVALID,
        input_r_TREADY,
        output_r_TDATA,
        output_r_TVALID,
        output_r_TREADY
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_state3 = 19'd4;
parameter    ap_ST_fsm_state4 = 19'd8;
parameter    ap_ST_fsm_state5 = 19'd16;
parameter    ap_ST_fsm_state6 = 19'd32;
parameter    ap_ST_fsm_state7 = 19'd64;
parameter    ap_ST_fsm_state8 = 19'd128;
parameter    ap_ST_fsm_state9 = 19'd256;
parameter    ap_ST_fsm_state10 = 19'd512;
parameter    ap_ST_fsm_state11 = 19'd1024;
parameter    ap_ST_fsm_state12 = 19'd2048;
parameter    ap_ST_fsm_state13 = 19'd4096;
parameter    ap_ST_fsm_state14 = 19'd8192;
parameter    ap_ST_fsm_state15 = 19'd16384;
parameter    ap_ST_fsm_state16 = 19'd32768;
parameter    ap_ST_fsm_state17 = 19'd65536;
parameter    ap_ST_fsm_state18 = 19'd131072;
parameter    ap_ST_fsm_state19 = 19'd262144;

input   ap_clk;
input   ap_rst_n;
input  [15:0] input_r_TDATA;
input   input_r_TVALID;
output   input_r_TREADY;
output  [15:0] output_r_TDATA;
output   output_r_TVALID;
input   output_r_TREADY;

 reg    ap_rst_n_inv;
reg   [0:0] mod_value1;
reg   [15:0] y1_phase1;
reg   [0:0] mod_value2;
reg   [15:0] y2_phase1;
reg   [15:0] y3;
reg   [15:0] p_ZL21H_filter_FIR_dec_2_21_0;
reg   [15:0] p_ZL21H_filter_FIR_dec_2_21_1;
reg   [15:0] p_ZL21H_filter_FIR_dec_2_21_2;
reg   [15:0] p_ZL21H_filter_FIR_dec_2_21_3;
reg   [15:0] p_ZL21H_filter_FIR_dec_2_21_4;
reg   [15:0] p_ZL21H_filter_FIR_int_2_21_0;
reg   [15:0] p_ZL21H_filter_FIR_int_2_21_1;
reg   [15:0] p_ZL21H_filter_FIR_int_2_21_2;
reg   [15:0] p_ZL21H_filter_FIR_int_2_21_3;
reg   [15:0] p_ZL21H_filter_FIR_int_2_21_4;
reg   [15:0] y4;
reg   [15:0] p_ZL21H_filter_FIR_dec_1_21_0;
reg   [15:0] p_ZL21H_filter_FIR_dec_1_21_1;
reg   [15:0] p_ZL21H_filter_FIR_dec_1_21_2;
reg   [15:0] p_ZL21H_filter_FIR_int_1_21_0;
reg   [15:0] p_ZL21H_filter_FIR_int_1_21_1;
reg   [15:0] p_ZL21H_filter_FIR_int_1_21_2;
reg    Halfband_delay10_V_ce0;
reg    Halfband_delay10_V_we0;
wire   [15:0] Halfband_delay10_V_q0;
reg    Halfband_delay20_V_ce0;
reg    Halfband_delay20_V_we0;
wire   [15:0] Halfband_delay20_V_q0;
reg    Halfband_delay21_V_ce0;
reg    Halfband_delay21_V_we0;
wire   [15:0] Halfband_delay21_V_q0;
reg    Halfband_delay11_V_ce0;
reg    Halfband_delay11_V_we0;
wire   [15:0] Halfband_delay11_V_q0;
reg    input_r_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    output_r_TDATA_blk_n;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state13;
reg   [0:0] mod_value1_load_reg_1198;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire   [0:0] mod_value1_load_load_fu_699_p1;
wire   [15:0] add_ln29_fu_773_p2;
reg   [15:0] add_ln29_reg_1207;
wire   [0:0] mod_value2_load_load_fu_780_p1;
reg   [0:0] mod_value2_load_reg_1213;
wire   [15:0] shl_ln52_fu_1191_p2;
wire   [15:0] grp_FIR_filter_1_fu_411_FIR_delays_write;
wire   [15:0] grp_FIR_filter_1_fu_411_ap_return_0;
wire   [15:0] grp_FIR_filter_1_fu_411_ap_return_1;
wire   [15:0] grp_FIR_filter_1_fu_411_ap_return_2;
wire   [15:0] grp_FIR_filter_1_fu_411_ap_return_3;
wire   [15:0] grp_FIR_filter_1_fu_411_ap_return_4;
wire   [15:0] grp_FIR_filter_1_fu_411_ap_return_5;
wire   [15:0] grp_FIR_filter_1_fu_421_ap_return_0;
wire   [15:0] grp_FIR_filter_1_fu_421_ap_return_1;
wire   [15:0] grp_FIR_filter_1_fu_421_ap_return_2;
wire   [15:0] grp_FIR_filter_1_fu_421_ap_return_3;
wire   [15:0] grp_FIR_filter_1_fu_421_ap_return_4;
wire   [15:0] grp_FIR_filter_1_fu_421_ap_return_5;
wire   [15:0] grp_FIR_filter_2_fu_431_ap_return_0;
wire   [15:0] grp_FIR_filter_2_fu_431_ap_return_1;
wire   [15:0] grp_FIR_filter_2_fu_431_ap_return_2;
wire   [15:0] grp_FIR_filter_2_fu_431_ap_return_3;
wire   [15:0] grp_FIR_filter_2_fu_440_ap_return_0;
wire   [15:0] grp_FIR_filter_2_fu_440_ap_return_1;
wire   [15:0] grp_FIR_filter_2_fu_440_ap_return_2;
wire   [15:0] grp_FIR_filter_2_fu_440_ap_return_3;
wire    grp_FIR_filter_fu_448_ap_start;
wire    grp_FIR_filter_fu_448_ap_done;
wire    grp_FIR_filter_fu_448_ap_idle;
wire    grp_FIR_filter_fu_448_ap_ready;
wire   [15:0] grp_FIR_filter_fu_448_x_n;
wire   [15:0] grp_FIR_filter_fu_448_ap_return;
wire   [15:0] shl_ln43_fu_1081_p2;
reg   [15:0] ap_phi_mux_p_013_0_0_0_phi_fu_380_p4;
reg   [0:0] storemerge1_reg_386;
reg   [0:0] ap_phi_mux_storemerge_phi_fu_403_p4;
reg   [0:0] storemerge_reg_399;
wire    regslice_both_output_r_U_apdone_blk;
reg    ap_block_state13;
reg    grp_FIR_filter_fu_448_ap_start_reg;
reg   [18:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
wire    ap_CS_fsm_state2;
wire  signed [15:0] sext_ln29_fu_713_p0;
wire  signed [15:0] tmp_fu_717_p1;
wire  signed [16:0] sext_ln29_fu_713_p1;
wire   [16:0] sub_ln29_fu_725_p2;
wire  signed [15:0] trunc_ln29_2_fu_741_p1;
wire   [14:0] trunc_ln29_1_cast_fu_731_p4;
wire   [0:0] tmp_fu_717_p3;
wire   [14:0] sub_ln29_1_fu_751_p2;
wire   [14:0] trunc_ln29_2_fu_741_p4;
wire   [14:0] select_ln29_fu_757_p3;
wire  signed [15:0] sext_ln29_1_fu_765_p1;
wire  signed [15:0] sext_ln35_fu_883_p0;
wire  signed [15:0] tmp_23_fu_887_p1;
wire  signed [16:0] sext_ln35_fu_883_p1;
wire   [16:0] sub_ln35_fu_895_p2;
wire  signed [15:0] trunc_ln35_2_fu_911_p1;
wire   [14:0] trunc_ln35_1_cast_fu_901_p4;
wire   [0:0] tmp_23_fu_887_p3;
wire   [14:0] sub_ln35_1_fu_921_p2;
wire   [14:0] trunc_ln35_2_fu_911_p4;
wire   [14:0] select_ln35_fu_927_p3;
wire  signed [15:0] sext_ln35_1_fu_935_p1;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    regslice_both_input_r_U_apdone_blk;
wire   [15:0] input_r_TDATA_int_regslice;
wire    input_r_TVALID_int_regslice;
reg    input_r_TREADY_int_regslice;
wire    regslice_both_input_r_U_ack_in;
reg   [15:0] output_r_TDATA_int_regslice;
reg    output_r_TVALID_int_regslice;
wire    output_r_TREADY_int_regslice;
wire    regslice_both_output_r_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 mod_value1 = 1'd0;
#0 y1_phase1 = 16'd0;
#0 mod_value2 = 1'd0;
#0 y2_phase1 = 16'd0;
#0 y3 = 16'd0;
#0 p_ZL21H_filter_FIR_dec_2_21_0 = 16'd0;
#0 p_ZL21H_filter_FIR_dec_2_21_1 = 16'd0;
#0 p_ZL21H_filter_FIR_dec_2_21_2 = 16'd0;
#0 p_ZL21H_filter_FIR_dec_2_21_3 = 16'd0;
#0 p_ZL21H_filter_FIR_dec_2_21_4 = 16'd0;
#0 p_ZL21H_filter_FIR_int_2_21_0 = 16'd0;
#0 p_ZL21H_filter_FIR_int_2_21_1 = 16'd0;
#0 p_ZL21H_filter_FIR_int_2_21_2 = 16'd0;
#0 p_ZL21H_filter_FIR_int_2_21_3 = 16'd0;
#0 p_ZL21H_filter_FIR_int_2_21_4 = 16'd0;
#0 y4 = 16'd0;
#0 p_ZL21H_filter_FIR_dec_1_21_0 = 16'd0;
#0 p_ZL21H_filter_FIR_dec_1_21_1 = 16'd0;
#0 p_ZL21H_filter_FIR_dec_1_21_2 = 16'd0;
#0 p_ZL21H_filter_FIR_int_1_21_0 = 16'd0;
#0 p_ZL21H_filter_FIR_int_1_21_1 = 16'd0;
#0 p_ZL21H_filter_FIR_int_1_21_2 = 16'd0;
#0 ap_CS_fsm = 19'd1;
#0 grp_FIR_filter_fu_448_ap_start_reg = 1'b0;
end

FIR_Halfband_v1_Halfband_delay10_V_SHIFTREG_AUTO_0R0W #(
    .DataWidth( 16 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
Halfband_delay10_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(2'd1),
    .ce0(Halfband_delay10_V_ce0),
    .we0(Halfband_delay10_V_we0),
    .d0(input_r_TDATA_int_regslice),
    .q0(Halfband_delay10_V_q0)
);

FIR_Halfband_v1_Halfband_delay20_V_SHIFTREG_AUTO_0R0W #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
Halfband_delay20_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(2'd2),
    .ce0(Halfband_delay20_V_ce0),
    .we0(Halfband_delay20_V_we0),
    .d0(add_ln29_reg_1207),
    .q0(Halfband_delay20_V_q0)
);

FIR_Halfband_v1_Halfband_delay20_V_SHIFTREG_AUTO_0R0W #(
    .DataWidth( 16 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
Halfband_delay21_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(2'd2),
    .ce0(Halfband_delay21_V_ce0),
    .we0(Halfband_delay21_V_we0),
    .d0(grp_FIR_filter_fu_448_ap_return),
    .q0(Halfband_delay21_V_q0)
);

FIR_Halfband_v1_Halfband_delay10_V_SHIFTREG_AUTO_0R0W #(
    .DataWidth( 16 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
Halfband_delay11_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(2'd1),
    .ce0(Halfband_delay11_V_ce0),
    .we0(Halfband_delay11_V_we0),
    .d0(ap_phi_mux_p_013_0_0_0_phi_fu_380_p4),
    .q0(Halfband_delay11_V_q0)
);

FIR_Halfband_v1_FIR_filter_1 grp_FIR_filter_1_fu_411(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .FIR_delays_read(p_ZL21H_filter_FIR_dec_2_21_0),
    .FIR_delays_read_21(p_ZL21H_filter_FIR_dec_2_21_1),
    .FIR_delays_read_22(p_ZL21H_filter_FIR_dec_2_21_2),
    .FIR_delays_read_23(p_ZL21H_filter_FIR_dec_2_21_3),
    .FIR_delays_read_24(p_ZL21H_filter_FIR_dec_2_21_4),
    .FIR_delays_write(grp_FIR_filter_1_fu_411_FIR_delays_write),
    .ap_return_0(grp_FIR_filter_1_fu_411_ap_return_0),
    .ap_return_1(grp_FIR_filter_1_fu_411_ap_return_1),
    .ap_return_2(grp_FIR_filter_1_fu_411_ap_return_2),
    .ap_return_3(grp_FIR_filter_1_fu_411_ap_return_3),
    .ap_return_4(grp_FIR_filter_1_fu_411_ap_return_4),
    .ap_return_5(grp_FIR_filter_1_fu_411_ap_return_5)
);

FIR_Halfband_v1_FIR_filter_1 grp_FIR_filter_1_fu_421(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .FIR_delays_read(p_ZL21H_filter_FIR_int_2_21_0),
    .FIR_delays_read_21(p_ZL21H_filter_FIR_int_2_21_1),
    .FIR_delays_read_22(p_ZL21H_filter_FIR_int_2_21_2),
    .FIR_delays_read_23(p_ZL21H_filter_FIR_int_2_21_3),
    .FIR_delays_read_24(p_ZL21H_filter_FIR_int_2_21_4),
    .FIR_delays_write(y3),
    .ap_return_0(grp_FIR_filter_1_fu_421_ap_return_0),
    .ap_return_1(grp_FIR_filter_1_fu_421_ap_return_1),
    .ap_return_2(grp_FIR_filter_1_fu_421_ap_return_2),
    .ap_return_3(grp_FIR_filter_1_fu_421_ap_return_3),
    .ap_return_4(grp_FIR_filter_1_fu_421_ap_return_4),
    .ap_return_5(grp_FIR_filter_1_fu_421_ap_return_5)
);

FIR_Halfband_v1_FIR_filter_2 grp_FIR_filter_2_fu_431(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .FIR_delays_read(p_ZL21H_filter_FIR_dec_1_21_0),
    .FIR_delays_read_8(p_ZL21H_filter_FIR_dec_1_21_1),
    .FIR_delays_read_9(p_ZL21H_filter_FIR_dec_1_21_2),
    .FIR_delays_write(input_r_TDATA_int_regslice),
    .ap_return_0(grp_FIR_filter_2_fu_431_ap_return_0),
    .ap_return_1(grp_FIR_filter_2_fu_431_ap_return_1),
    .ap_return_2(grp_FIR_filter_2_fu_431_ap_return_2),
    .ap_return_3(grp_FIR_filter_2_fu_431_ap_return_3)
);

FIR_Halfband_v1_FIR_filter_2 grp_FIR_filter_2_fu_440(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .FIR_delays_read(p_ZL21H_filter_FIR_int_1_21_0),
    .FIR_delays_read_8(p_ZL21H_filter_FIR_int_1_21_1),
    .FIR_delays_read_9(p_ZL21H_filter_FIR_int_1_21_2),
    .FIR_delays_write(y4),
    .ap_return_0(grp_FIR_filter_2_fu_440_ap_return_0),
    .ap_return_1(grp_FIR_filter_2_fu_440_ap_return_1),
    .ap_return_2(grp_FIR_filter_2_fu_440_ap_return_2),
    .ap_return_3(grp_FIR_filter_2_fu_440_ap_return_3)
);

FIR_Halfband_v1_FIR_filter grp_FIR_filter_fu_448(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_FIR_filter_fu_448_ap_start),
    .ap_done(grp_FIR_filter_fu_448_ap_done),
    .ap_idle(grp_FIR_filter_fu_448_ap_idle),
    .ap_ready(grp_FIR_filter_fu_448_ap_ready),
    .x_n(grp_FIR_filter_fu_448_x_n),
    .ap_return(grp_FIR_filter_fu_448_ap_return)
);

FIR_Halfband_v1_regslice_both #(
    .DataWidth( 16 ))
regslice_both_input_r_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_r_TDATA),
    .vld_in(input_r_TVALID),
    .ack_in(regslice_both_input_r_U_ack_in),
    .data_out(input_r_TDATA_int_regslice),
    .vld_out(input_r_TVALID_int_regslice),
    .ack_out(input_r_TREADY_int_regslice),
    .apdone_blk(regslice_both_input_r_U_apdone_blk)
);

FIR_Halfband_v1_regslice_both #(
    .DataWidth( 16 ))
regslice_both_output_r_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_r_TDATA_int_regslice),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(output_r_TREADY_int_regslice),
    .data_out(output_r_TDATA),
    .vld_out(regslice_both_output_r_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_FIR_filter_fu_448_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b1 == ap_NS_fsm_state2))) begin
            grp_FIR_filter_fu_448_ap_start_reg <= 1'b1;
        end else if ((grp_FIR_filter_fu_448_ap_ready == 1'b1)) begin
            grp_FIR_filter_fu_448_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (output_r_TREADY_int_regslice == 1'b1))) begin
        if ((mod_value2_load_reg_1213 == 1'd0)) begin
            storemerge1_reg_386 <= 1'd1;
        end else if ((mod_value2_load_reg_1213 == 1'd1)) begin
            storemerge1_reg_386 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13) & (mod_value1_load_reg_1198 == 1'd0))) begin
        storemerge_reg_399 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state19) & (output_r_TREADY_int_regslice == 1'b1))) begin
        storemerge_reg_399 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln29_reg_1207 <= add_ln29_fu_773_p2;
        mod_value1_load_reg_1198 <= mod_value1;
        mod_value2_load_reg_1213 <= mod_value2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13))) begin
        mod_value1 <= ap_phi_mux_storemerge_phi_fu_403_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13) & (mod_value1_load_reg_1198 == 1'd0))) begin
        mod_value2 <= storemerge1_reg_386;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) & (output_r_TREADY_int_regslice == 1'b1))) begin
        p_ZL21H_filter_FIR_dec_1_21_0 <= grp_FIR_filter_2_fu_431_ap_return_1;
        p_ZL21H_filter_FIR_dec_1_21_1 <= grp_FIR_filter_2_fu_431_ap_return_2;
        p_ZL21H_filter_FIR_dec_1_21_2 <= grp_FIR_filter_2_fu_431_ap_return_3;
        p_ZL21H_filter_FIR_int_1_21_0 <= grp_FIR_filter_2_fu_440_ap_return_1;
        p_ZL21H_filter_FIR_int_1_21_1 <= grp_FIR_filter_2_fu_440_ap_return_2;
        p_ZL21H_filter_FIR_int_1_21_2 <= grp_FIR_filter_2_fu_440_ap_return_3;
        y1_phase1 <= grp_FIR_filter_2_fu_431_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (mod_value2_load_reg_1213 == 1'd1) & (output_r_TREADY_int_regslice == 1'b1))) begin
        p_ZL21H_filter_FIR_dec_2_21_0 <= grp_FIR_filter_1_fu_411_ap_return_1;
        p_ZL21H_filter_FIR_dec_2_21_1 <= grp_FIR_filter_1_fu_411_ap_return_2;
        p_ZL21H_filter_FIR_dec_2_21_2 <= grp_FIR_filter_1_fu_411_ap_return_3;
        p_ZL21H_filter_FIR_dec_2_21_3 <= grp_FIR_filter_1_fu_411_ap_return_4;
        p_ZL21H_filter_FIR_dec_2_21_4 <= grp_FIR_filter_1_fu_411_ap_return_5;
        p_ZL21H_filter_FIR_int_2_21_0 <= grp_FIR_filter_1_fu_421_ap_return_1;
        p_ZL21H_filter_FIR_int_2_21_1 <= grp_FIR_filter_1_fu_421_ap_return_2;
        p_ZL21H_filter_FIR_int_2_21_2 <= grp_FIR_filter_1_fu_421_ap_return_3;
        p_ZL21H_filter_FIR_int_2_21_3 <= grp_FIR_filter_1_fu_421_ap_return_4;
        p_ZL21H_filter_FIR_int_2_21_4 <= grp_FIR_filter_1_fu_421_ap_return_5;
        y2_phase1 <= grp_FIR_filter_1_fu_411_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (mod_value2_load_reg_1213 == 1'd0) & (output_r_TREADY_int_regslice == 1'b1))) begin
        y3 <= grp_FIR_filter_fu_448_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (output_r_TREADY_int_regslice == 1'b1))) begin
        y4 <= ap_phi_mux_p_013_0_0_0_phi_fu_380_p4;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (mod_value1_load_load_fu_699_p1 == 1'd0) & (input_r_TVALID_int_regslice == 1'b1))) begin
        Halfband_delay10_V_ce0 = 1'd1;
    end else begin
        Halfband_delay10_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (mod_value1_load_load_fu_699_p1 == 1'd0) & (input_r_TVALID_int_regslice == 1'b1))) begin
        Halfband_delay10_V_we0 = 1'd1;
    end else begin
        Halfband_delay10_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (output_r_TREADY_int_regslice == 1'b1))) begin
        Halfband_delay11_V_ce0 = 1'd1;
    end else begin
        Halfband_delay11_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (output_r_TREADY_int_regslice == 1'b1))) begin
        Halfband_delay11_V_we0 = 1'd1;
    end else begin
        Halfband_delay11_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Halfband_delay20_V_ce0 = 1'd1;
    end else begin
        Halfband_delay20_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Halfband_delay20_V_we0 = 1'd1;
    end else begin
        Halfband_delay20_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (mod_value2_load_reg_1213 == 1'd0) & (output_r_TREADY_int_regslice == 1'b1))) begin
        Halfband_delay21_V_ce0 = 1'd1;
    end else begin
        Halfband_delay21_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (mod_value2_load_reg_1213 == 1'd0) & (output_r_TREADY_int_regslice == 1'b1))) begin
        Halfband_delay21_V_we0 = 1'd1;
    end else begin
        Halfband_delay21_V_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state13)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((output_r_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((output_r_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((input_r_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((output_r_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        if ((mod_value2_load_reg_1213 == 1'd0)) begin
            ap_phi_mux_p_013_0_0_0_phi_fu_380_p4 = Halfband_delay21_V_q0;
        end else if ((mod_value2_load_reg_1213 == 1'd1)) begin
            ap_phi_mux_p_013_0_0_0_phi_fu_380_p4 = shl_ln43_fu_1081_p2;
        end else begin
            ap_phi_mux_p_013_0_0_0_phi_fu_380_p4 = 'bx;
        end
    end else begin
        ap_phi_mux_p_013_0_0_0_phi_fu_380_p4 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) & (mod_value1_load_reg_1198 == 1'd0))) begin
        ap_phi_mux_storemerge_phi_fu_403_p4 = 1'd1;
    end else begin
        ap_phi_mux_storemerge_phi_fu_403_p4 = storemerge_reg_399;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        input_r_TDATA_blk_n = input_r_TVALID_int_regslice;
    end else begin
        input_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (input_r_TVALID_int_regslice == 1'b1))) begin
        input_r_TREADY_int_regslice = 1'b1;
    end else begin
        input_r_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state13) & (mod_value1_load_reg_1198 == 1'd0)))) begin
        output_r_TDATA_blk_n = output_r_TREADY_int_regslice;
    end else begin
        output_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((output_r_TREADY_int_regslice == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            output_r_TDATA_int_regslice = shl_ln52_fu_1191_p2;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            output_r_TDATA_int_regslice = Halfband_delay11_V_q0;
        end else begin
            output_r_TDATA_int_regslice = 'bx;
        end
    end else begin
        output_r_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state18) & (output_r_TREADY_int_regslice == 1'b1)) | ((1'b1 == ap_CS_fsm_state7) & (output_r_TREADY_int_regslice == 1'b1)))) begin
        output_r_TVALID_int_regslice = 1'b1;
    end else begin
        output_r_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (mod_value2_load_load_fu_780_p1 == 1'd1) & (mod_value1_load_load_fu_699_p1 == 1'd0) & (input_r_TVALID_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((1'b1 == ap_CS_fsm_state1) & (mod_value2_load_load_fu_780_p1 == 1'd0) & (mod_value1_load_load_fu_699_p1 == 1'd0) & (input_r_TVALID_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((1'b1 == ap_CS_fsm_state1) & (mod_value1_load_load_fu_699_p1 == 1'd1) & (input_r_TVALID_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (output_r_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state13 : begin
            if (((1'b0 == ap_block_state13) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((1'b1 == ap_CS_fsm_state18) & (output_r_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((1'b1 == ap_CS_fsm_state19) & (output_r_TREADY_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln29_fu_773_p2 = ($signed(y1_phase1) + $signed(sext_ln29_1_fu_765_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

always @ (*) begin
    ap_block_state13 = ((regslice_both_output_r_U_apdone_blk == 1'b1) | ((mod_value1_load_reg_1198 == 1'd0) & (output_r_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_FIR_filter_1_fu_411_FIR_delays_write = ($signed(y1_phase1) + $signed(sext_ln29_1_fu_765_p1));

assign grp_FIR_filter_fu_448_ap_start = grp_FIR_filter_fu_448_ap_start_reg;

assign grp_FIR_filter_fu_448_x_n = ($signed(y2_phase1) + $signed(sext_ln35_1_fu_935_p1));

assign input_r_TREADY = regslice_both_input_r_U_ack_in;

assign mod_value1_load_load_fu_699_p1 = mod_value1;

assign mod_value2_load_load_fu_780_p1 = mod_value2;

assign output_r_TVALID = regslice_both_output_r_U_vld_out;

assign select_ln29_fu_757_p3 = ((tmp_fu_717_p3[0:0] == 1'b1) ? sub_ln29_1_fu_751_p2 : trunc_ln29_2_fu_741_p4);

assign select_ln35_fu_927_p3 = ((tmp_23_fu_887_p3[0:0] == 1'b1) ? sub_ln35_1_fu_921_p2 : trunc_ln35_2_fu_911_p4);

assign sext_ln29_1_fu_765_p1 = $signed(select_ln29_fu_757_p3);

assign sext_ln29_fu_713_p0 = Halfband_delay10_V_q0;

assign sext_ln29_fu_713_p1 = sext_ln29_fu_713_p0;

assign sext_ln35_1_fu_935_p1 = $signed(select_ln35_fu_927_p3);

assign sext_ln35_fu_883_p0 = Halfband_delay20_V_q0;

assign sext_ln35_fu_883_p1 = sext_ln35_fu_883_p0;

assign shl_ln43_fu_1081_p2 = grp_FIR_filter_1_fu_421_ap_return_0 << 16'd1;

assign shl_ln52_fu_1191_p2 = grp_FIR_filter_2_fu_440_ap_return_0 << 16'd1;

assign sub_ln29_1_fu_751_p2 = (15'd0 - trunc_ln29_1_cast_fu_731_p4);

assign sub_ln29_fu_725_p2 = ($signed(17'd0) - $signed(sext_ln29_fu_713_p1));

assign sub_ln35_1_fu_921_p2 = (15'd0 - trunc_ln35_1_cast_fu_901_p4);

assign sub_ln35_fu_895_p2 = ($signed(17'd0) - $signed(sext_ln35_fu_883_p1));

assign tmp_23_fu_887_p1 = Halfband_delay20_V_q0;

assign tmp_23_fu_887_p3 = tmp_23_fu_887_p1[32'd15];

assign tmp_fu_717_p1 = Halfband_delay10_V_q0;

assign tmp_fu_717_p3 = tmp_fu_717_p1[32'd15];

assign trunc_ln29_1_cast_fu_731_p4 = {{sub_ln29_fu_725_p2[15:1]}};

assign trunc_ln29_2_fu_741_p1 = Halfband_delay10_V_q0;

assign trunc_ln29_2_fu_741_p4 = {{trunc_ln29_2_fu_741_p1[15:1]}};

assign trunc_ln35_1_cast_fu_901_p4 = {{sub_ln35_fu_895_p2[15:1]}};

assign trunc_ln35_2_fu_911_p1 = Halfband_delay20_V_q0;

assign trunc_ln35_2_fu_911_p4 = {{trunc_ln35_2_fu_911_p1[15:1]}};

endmodule //FIR_Halfband_v1
