// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module FIR_Halfband_v1_FIR_filter (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_n,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] x_n;
output  [15:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
reg   [15:0] p_ZL19H_filter_FIR_kernel_122;
reg   [15:0] p_ZL19H_filter_FIR_kernel_121;
reg   [15:0] p_ZL19H_filter_FIR_kernel_120;
reg   [15:0] p_ZL19H_filter_FIR_kernel_119;
reg   [15:0] p_ZL19H_filter_FIR_kernel_118;
reg   [15:0] p_ZL19H_filter_FIR_kernel_117;
reg   [15:0] p_ZL19H_filter_FIR_kernel_116;
reg   [15:0] p_ZL19H_filter_FIR_kernel_115;
reg   [15:0] p_ZL19H_filter_FIR_kernel_114;
reg   [15:0] p_ZL19H_filter_FIR_kernel_113;
reg   [15:0] p_ZL19H_filter_FIR_kernel_112;
reg   [15:0] p_ZL19H_filter_FIR_kernel_111;
reg   [15:0] p_ZL19H_filter_FIR_kernel_110;
reg   [15:0] p_ZL19H_filter_FIR_kernel_109;
reg   [15:0] p_ZL19H_filter_FIR_kernel_108;
reg   [15:0] p_ZL19H_filter_FIR_kernel_107;
reg   [15:0] p_ZL19H_filter_FIR_kernel_106;
reg   [15:0] p_ZL19H_filter_FIR_kernel_105;
reg   [15:0] p_ZL19H_filter_FIR_kernel_104;
reg   [15:0] p_ZL19H_filter_FIR_kernel_103;
reg   [15:0] p_ZL19H_filter_FIR_kernel_102;
reg   [15:0] p_ZL19H_filter_FIR_kernel_101;
reg   [15:0] p_ZL19H_filter_FIR_kernel_100;
reg   [15:0] p_ZL19H_filter_FIR_kernel_99;
reg   [15:0] p_ZL19H_filter_FIR_kernel_98;
reg   [15:0] p_ZL19H_filter_FIR_kernel_97;
reg   [15:0] p_ZL19H_filter_FIR_kernel_96;
reg   [15:0] p_ZL19H_filter_FIR_kernel_95;
reg   [15:0] p_ZL19H_filter_FIR_kernel_94;
reg   [15:0] p_ZL19H_filter_FIR_kernel_93;
reg   [15:0] p_ZL19H_filter_FIR_kernel_92;
reg   [15:0] p_ZL19H_filter_FIR_kernel_91;
reg   [15:0] p_ZL19H_filter_FIR_kernel_90;
reg   [15:0] p_ZL19H_filter_FIR_kernel_89;
reg   [15:0] p_ZL19H_filter_FIR_kernel_88;
reg   [15:0] p_ZL19H_filter_FIR_kernel_87;
reg   [15:0] p_ZL19H_filter_FIR_kernel_86;
reg   [15:0] p_ZL19H_filter_FIR_kernel_85;
reg   [15:0] p_ZL19H_filter_FIR_kernel_84;
reg   [15:0] p_ZL19H_filter_FIR_kernel_83;
reg   [15:0] p_ZL19H_filter_FIR_kernel_82;
reg   [15:0] p_ZL19H_filter_FIR_kernel_81;
reg   [15:0] p_ZL19H_filter_FIR_kernel_80;
reg   [15:0] p_ZL19H_filter_FIR_kernel_79;
reg   [15:0] p_ZL19H_filter_FIR_kernel_78;
reg   [15:0] p_ZL19H_filter_FIR_kernel_77;
reg   [15:0] p_ZL19H_filter_FIR_kernel_76;
reg   [15:0] p_ZL19H_filter_FIR_kernel_75;
reg   [15:0] p_ZL19H_filter_FIR_kernel_74;
reg   [15:0] p_ZL19H_filter_FIR_kernel_73;
reg   [15:0] p_ZL19H_filter_FIR_kernel_72;
reg   [15:0] p_ZL19H_filter_FIR_kernel_71;
reg   [15:0] p_ZL19H_filter_FIR_kernel_70;
reg   [15:0] p_ZL19H_filter_FIR_kernel_69;
reg   [15:0] p_ZL19H_filter_FIR_kernel_68;
reg   [15:0] p_ZL19H_filter_FIR_kernel_67;
reg   [15:0] p_ZL19H_filter_FIR_kernel_66;
reg   [15:0] p_ZL19H_filter_FIR_kernel_65;
reg   [15:0] p_ZL19H_filter_FIR_kernel_64;
reg   [15:0] p_ZL19H_filter_FIR_kernel_63;
reg   [15:0] p_ZL19H_filter_FIR_kernel_62;
reg   [15:0] p_ZL19H_filter_FIR_kernel_61;
reg   [15:0] p_ZL19H_filter_FIR_kernel_60;
reg   [15:0] p_ZL19H_filter_FIR_kernel_59;
reg   [15:0] p_ZL19H_filter_FIR_kernel_58;
reg   [15:0] p_ZL19H_filter_FIR_kernel_57;
reg   [15:0] p_ZL19H_filter_FIR_kernel_56;
reg   [15:0] p_ZL19H_filter_FIR_kernel_55;
reg   [15:0] p_ZL19H_filter_FIR_kernel_54;
reg   [15:0] p_ZL19H_filter_FIR_kernel_53;
reg   [15:0] p_ZL19H_filter_FIR_kernel_52;
reg   [15:0] p_ZL19H_filter_FIR_kernel_51;
reg   [15:0] p_ZL19H_filter_FIR_kernel_50;
reg   [15:0] p_ZL19H_filter_FIR_kernel_49;
reg   [15:0] p_ZL19H_filter_FIR_kernel_48;
reg   [15:0] p_ZL19H_filter_FIR_kernel_47;
reg   [15:0] p_ZL19H_filter_FIR_kernel_46;
reg   [15:0] p_ZL19H_filter_FIR_kernel_45;
reg   [15:0] p_ZL19H_filter_FIR_kernel_44;
reg   [15:0] p_ZL19H_filter_FIR_kernel_43;
reg   [15:0] p_ZL19H_filter_FIR_kernel_42;
reg   [15:0] p_ZL19H_filter_FIR_kernel_41;
reg   [15:0] p_ZL19H_filter_FIR_kernel_40;
reg   [15:0] p_ZL19H_filter_FIR_kernel_39;
reg   [15:0] p_ZL19H_filter_FIR_kernel_38;
reg   [15:0] p_ZL19H_filter_FIR_kernel_37;
reg   [15:0] p_ZL19H_filter_FIR_kernel_36;
reg   [15:0] p_ZL19H_filter_FIR_kernel_35;
reg   [15:0] p_ZL19H_filter_FIR_kernel_34;
reg   [15:0] p_ZL19H_filter_FIR_kernel_33;
reg   [15:0] p_ZL19H_filter_FIR_kernel_32;
reg   [15:0] p_ZL19H_filter_FIR_kernel_31;
reg   [15:0] p_ZL19H_filter_FIR_kernel_30;
reg   [15:0] p_ZL19H_filter_FIR_kernel_29;
reg   [15:0] p_ZL19H_filter_FIR_kernel_28;
reg   [15:0] p_ZL19H_filter_FIR_kernel_27;
reg   [15:0] p_ZL19H_filter_FIR_kernel_26;
reg   [15:0] p_ZL19H_filter_FIR_kernel_25;
reg   [15:0] p_ZL19H_filter_FIR_kernel_24;
reg   [15:0] p_ZL19H_filter_FIR_kernel_23;
reg   [15:0] p_ZL19H_filter_FIR_kernel_22;
reg   [15:0] p_ZL19H_filter_FIR_kernel_21;
reg   [15:0] p_ZL19H_filter_FIR_kernel_20;
reg   [15:0] p_ZL19H_filter_FIR_kernel_19;
reg   [15:0] p_ZL19H_filter_FIR_kernel_18;
reg   [15:0] p_ZL19H_filter_FIR_kernel_17;
reg   [15:0] p_ZL19H_filter_FIR_kernel_16;
reg   [15:0] p_ZL19H_filter_FIR_kernel_15;
reg   [15:0] p_ZL19H_filter_FIR_kernel_14;
reg   [15:0] p_ZL19H_filter_FIR_kernel_13;
reg   [15:0] p_ZL19H_filter_FIR_kernel_12;
reg   [15:0] p_ZL19H_filter_FIR_kernel_11;
reg   [15:0] p_ZL19H_filter_FIR_kernel_10;
reg   [15:0] p_ZL19H_filter_FIR_kernel_9;
reg   [15:0] p_ZL19H_filter_FIR_kernel_8;
reg   [15:0] p_ZL19H_filter_FIR_kernel_7;
reg   [15:0] p_ZL19H_filter_FIR_kernel_6;
reg   [15:0] p_ZL19H_filter_FIR_kernel_5;
reg   [15:0] p_ZL19H_filter_FIR_kernel_4;
reg   [15:0] p_ZL19H_filter_FIR_kernel_3;
reg   [15:0] p_ZL19H_filter_FIR_kernel_2;
reg   [15:0] p_ZL19H_filter_FIR_kernel_1;
reg   [15:0] p_ZL19H_filter_FIR_kernel_0;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_109_load_reg_3361;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_106_load_reg_3366;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_106_load_reg_3366_pp0_iter1_reg;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_104_load_reg_3371;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_99_load_reg_3376;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_98_load_reg_3381;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_94_load_reg_3386;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_92_load_reg_3391;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_92_load_reg_3391_pp0_iter1_reg;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_91_load_reg_3396;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_89_load_reg_3401;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_87_load_reg_3406;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_84_load_reg_3411;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_81_load_reg_3416;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_79_load_reg_3421;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_77_load_reg_3426;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_76_load_reg_3431;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_76_load_reg_3431_pp0_iter1_reg;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_73_load_reg_3436;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_69_load_reg_3441;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_67_load_reg_3446;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_64_load_reg_3451;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_63_load_reg_3456;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_63_load_reg_3456_pp0_iter1_reg;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_60_load_reg_3461;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_60_load_reg_3461_pp0_iter1_reg;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_59_load_reg_3466;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_56_load_reg_3471;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_54_load_reg_3476;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_50_load_reg_3481;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_47_load_reg_3486;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_47_load_reg_3486_pp0_iter1_reg;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_46_load_reg_3491;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_44_load_reg_3496;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_42_load_reg_3501;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_39_load_reg_3506;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_36_load_reg_3511;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_34_load_reg_3516;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_32_load_reg_3521;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_31_load_reg_3526;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_31_load_reg_3526_pp0_iter1_reg;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_29_load_reg_3531;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_25_load_reg_3536;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_24_load_reg_3541;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_19_load_reg_3546;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_17_load_reg_3551;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_17_load_reg_3551_pp0_iter1_reg;
reg  signed [15:0] p_ZL19H_filter_FIR_kernel_14_load_reg_3556;
wire   [17:0] tmp7_fu_1262_p2;
reg   [17:0] tmp7_reg_3561;
reg  signed [17:0] tmp7_reg_3561_pp0_iter1_reg;
wire   [16:0] tmp25_fu_1308_p2;
reg   [16:0] tmp25_reg_3566;
reg   [16:0] tmp25_reg_3566_pp0_iter1_reg;
wire   [16:0] tmp35_fu_1314_p2;
reg   [16:0] tmp35_reg_3572;
reg   [16:0] tmp35_reg_3572_pp0_iter1_reg;
wire   [16:0] tmp43_fu_1320_p2;
reg   [16:0] tmp43_reg_3578;
reg   [16:0] tmp43_reg_3578_pp0_iter1_reg;
wire   [16:0] tmp81_fu_1326_p2;
reg   [16:0] tmp81_reg_3584;
reg   [16:0] tmp81_reg_3584_pp0_iter1_reg;
wire   [16:0] tmp91_fu_1332_p2;
reg   [16:0] tmp91_reg_3590;
reg   [16:0] tmp91_reg_3590_pp0_iter1_reg;
wire   [16:0] tmp931_fu_1346_p2;
reg   [16:0] tmp931_reg_3596;
reg   [16:0] tmp931_reg_3596_pp0_iter1_reg;
wire   [16:0] tmp113_fu_1424_p2;
reg   [16:0] tmp113_reg_3601;
reg   [16:0] tmp113_reg_3601_pp0_iter1_reg;
wire   [16:0] tmp115_fu_1430_p2;
reg   [16:0] tmp115_reg_3607;
reg   [16:0] tmp115_reg_3607_pp0_iter1_reg;
wire   [16:0] tmp117_fu_1436_p2;
reg   [16:0] tmp117_reg_3613;
reg   [16:0] tmp117_reg_3613_pp0_iter1_reg;
wire   [16:0] tmp121_fu_1442_p2;
reg   [16:0] tmp121_reg_3619;
reg   [16:0] tmp121_reg_3619_pp0_iter1_reg;
wire   [24:0] add_ln71_44_fu_1448_p2;
reg   [24:0] add_ln71_44_reg_3625;
reg   [24:0] add_ln71_44_reg_3625_pp0_iter1_reg;
reg   [24:0] add_ln71_44_reg_3625_pp0_iter2_reg;
wire  signed [24:0] tmp8_fu_2315_p2;
wire  signed [26:0] grp_fu_2915_p3;
wire  signed [31:0] grp_fu_2945_p3;
wire  signed [29:0] grp_fu_2963_p3;
wire  signed [28:0] grp_fu_2981_p3;
wire  signed [27:0] grp_fu_2999_p3;
wire  signed [27:0] grp_fu_3007_p3;
wire  signed [27:0] grp_fu_3015_p3;
wire  signed [26:0] grp_fu_3023_p3;
wire  signed [26:0] grp_fu_3031_p3;
wire  signed [26:0] grp_fu_3039_p3;
wire  signed [26:0] grp_fu_3047_p3;
wire  signed [25:0] grp_fu_3065_p3;
wire  signed [24:0] grp_fu_3094_p3;
wire  signed [25:0] grp_fu_3102_p3;
wire  signed [29:0] grp_fu_2953_p4;
reg  signed [29:0] add_ln71_3_reg_3755;
wire  signed [28:0] grp_fu_2971_p4;
wire  signed [27:0] grp_fu_2989_p4;
reg  signed [27:0] add_ln71_10_reg_3765;
wire  signed [25:0] grp_fu_3055_p4;
reg  signed [25:0] add_ln71_31_reg_3770;
wire  signed [24:0] grp_fu_3084_p4;
reg  signed [24:0] add_ln71_37_reg_3780;
wire   [25:0] add_ln71_46_fu_2617_p2;
reg   [25:0] add_ln71_46_reg_3785;
reg   [25:0] add_ln71_46_reg_3785_pp0_iter4_reg;
wire   [26:0] add_ln71_54_fu_2651_p2;
reg   [26:0] add_ln71_54_reg_3790;
reg   [26:0] add_ln71_54_reg_3790_pp0_iter4_reg;
wire  signed [31:0] grp_fu_3143_p4;
wire   [30:0] add_ln71_5_fu_2663_p2;
reg   [30:0] add_ln71_5_reg_3800;
wire   [29:0] add_ln71_12_fu_2684_p2;
reg   [29:0] add_ln71_12_reg_3805;
wire   [28:0] add_ln71_18_fu_2699_p2;
reg   [28:0] add_ln71_18_reg_3815;
wire   [28:0] add_ln71_26_fu_2737_p2;
reg   [28:0] add_ln71_26_reg_3820;
wire   [26:0] add_ln71_33_fu_2752_p2;
reg   [26:0] add_ln71_33_reg_3830;
wire   [27:0] add_ln71_40_fu_2777_p2;
reg   [27:0] add_ln71_40_reg_3835;
wire  signed [25:0] grp_fu_3307_p4;
wire    ap_block_pp0_stage0;
wire  signed [15:0] sext_ln66_fu_406_p0;
wire  signed [15:0] sext_ln71_fu_414_p0;
wire  signed [15:0] sext_ln71_7_fu_422_p0;
wire  signed [15:0] sext_ln71_8_fu_430_p0;
wire  signed [15:0] sext_ln71_9_fu_438_p0;
wire  signed [15:0] sext_ln71_10_fu_446_p0;
wire  signed [15:0] sext_ln71_11_fu_454_p0;
wire  signed [15:0] sext_ln71_12_fu_462_p0;
wire  signed [15:0] sext_ln71_13_fu_470_p0;
wire  signed [15:0] sext_ln71_14_fu_478_p0;
wire  signed [15:0] sext_ln71_15_fu_486_p0;
wire  signed [15:0] sext_ln71_16_fu_494_p0;
wire  signed [15:0] sext_ln71_17_fu_502_p0;
wire  signed [15:0] sext_ln71_18_fu_510_p0;
wire  signed [15:0] sext_ln71_20_fu_522_p0;
wire  signed [15:0] sext_ln71_21_fu_530_p0;
wire  signed [15:0] sext_ln71_23_fu_542_p0;
wire  signed [15:0] sext_ln71_25_fu_554_p0;
wire  signed [15:0] sext_ln71_26_fu_566_p0;
wire  signed [15:0] sext_ln71_27_fu_574_p0;
wire  signed [15:0] sext_ln71_30_fu_590_p0;
wire  signed [15:0] sext_ln71_31_fu_598_p0;
wire  signed [15:0] sext_ln71_32_fu_606_p0;
wire  signed [15:0] sext_ln71_34_fu_618_p0;
wire  signed [15:0] sext_ln71_37_fu_634_p0;
wire  signed [15:0] sext_ln71_39_fu_646_p0;
wire  signed [15:0] sext_ln71_41_fu_658_p0;
wire  signed [15:0] sext_ln71_42_fu_666_p0;
wire  signed [15:0] sext_ln71_44_fu_678_p0;
wire  signed [15:0] sext_ln71_45_fu_686_p0;
wire  signed [15:0] sext_ln71_47_fu_698_p0;
wire  signed [15:0] sext_ln71_49_fu_710_p0;
wire  signed [15:0] sext_ln71_52_fu_726_p0;
wire  signed [15:0] sext_ln71_53_fu_734_p0;
wire  signed [15:0] sext_ln71_55_fu_746_p0;
wire  signed [15:0] sext_ln71_56_fu_754_p0;
wire  signed [15:0] sext_ln71_57_fu_762_p0;
wire  signed [15:0] sext_ln71_59_fu_774_p0;
wire  signed [15:0] sext_ln71_61_fu_786_p0;
wire  signed [15:0] sext_ln71_62_fu_794_p0;
wire  signed [15:0] sext_ln71_65_fu_810_p0;
wire  signed [15:0] sext_ln71_66_fu_818_p0;
wire  signed [15:0] sext_ln71_69_fu_834_p0;
wire  signed [15:0] sext_ln71_70_fu_842_p0;
wire  signed [15:0] sext_ln71_72_fu_854_p0;
wire  signed [15:0] sext_ln71_74_fu_866_p0;
wire  signed [15:0] sext_ln71_75_fu_874_p0;
wire  signed [15:0] sext_ln71_76_fu_882_p0;
wire  signed [15:0] sext_ln71_78_fu_894_p0;
wire  signed [15:0] sext_ln71_79_fu_902_p0;
wire  signed [15:0] sext_ln71_82_fu_918_p0;
wire  signed [15:0] sext_ln71_84_fu_930_p0;
wire  signed [15:0] sext_ln71_86_fu_942_p0;
wire  signed [15:0] sext_ln71_87_fu_950_p0;
wire  signed [15:0] sext_ln71_89_fu_962_p0;
wire  signed [15:0] sext_ln71_90_fu_970_p0;
wire  signed [15:0] sext_ln71_92_fu_982_p0;
wire  signed [15:0] sext_ln71_94_fu_994_p0;
wire  signed [15:0] sext_ln71_97_fu_1010_p0;
wire  signed [15:0] sext_ln71_99_fu_1022_p0;
wire  signed [15:0] sext_ln71_100_fu_1030_p0;
wire  signed [15:0] sext_ln71_101_fu_1038_p0;
wire  signed [15:0] sext_ln71_104_fu_1054_p0;
wire  signed [15:0] sext_ln71_105_fu_1062_p0;
wire  signed [15:0] sext_ln71_106_fu_1074_p0;
wire  signed [15:0] sext_ln71_108_fu_1086_p0;
wire  signed [15:0] sext_ln71_110_fu_1098_p0;
wire  signed [15:0] sext_ln71_111_fu_1106_p0;
wire  signed [15:0] sext_ln71_113_fu_1118_p0;
wire  signed [15:0] sext_ln71_114_fu_1126_p0;
wire  signed [15:0] sext_ln71_115_fu_1134_p0;
wire  signed [15:0] sext_ln71_116_fu_1142_p0;
wire  signed [15:0] sext_ln71_117_fu_1150_p0;
wire  signed [15:0] sext_ln71_118_fu_1158_p0;
wire  signed [15:0] sext_ln71_119_fu_1166_p0;
wire  signed [15:0] sext_ln71_120_fu_1174_p0;
wire  signed [15:0] sext_ln71_121_fu_1182_p0;
wire  signed [15:0] sext_ln71_122_fu_1190_p0;
wire  signed [15:0] sext_ln71_123_fu_1198_p0;
wire  signed [15:0] sext_ln71_124_fu_1206_p0;
wire  signed [15:0] sext_ln71_125_fu_1214_p0;
wire  signed [15:0] p_ZL19H_filter_FIR_kernel_0_load_cast_fu_1222_p0;
wire  signed [16:0] sext_ln71_42_fu_666_p1;
wire  signed [16:0] sext_ln71_34_fu_618_p1;
wire  signed [16:0] tmp4_fu_1226_p2;
wire  signed [16:0] sext_ln71_89_fu_962_p1;
wire  signed [16:0] sext_ln71_97_fu_1010_p1;
wire  signed [16:0] tmp93_fu_1236_p2;
wire  signed [16:0] sext_ln71_12_fu_462_p1;
wire  signed [16:0] sext_ln71_18_fu_510_p1;
wire   [16:0] tmp5_fu_1246_p2;
wire  signed [17:0] tmp5_cast_fu_1252_p1;
wire  signed [17:0] sext_ln71_113_fu_1118_p1;
wire   [17:0] tmp6_fu_1256_p2;
wire  signed [17:0] sext_ln71_119_fu_1166_p1;
wire  signed [16:0] sext_ln71_20_fu_522_p1;
wire  signed [16:0] sext_ln71_11_fu_454_p1;
wire  signed [16:0] tmp125_fu_1268_p2;
wire  signed [16:0] sext_ln71_111_fu_1106_p1;
wire  signed [16:0] sext_ln71_120_fu_1174_p1;
wire  signed [16:0] tmp126_fu_1278_p2;
wire  signed [16:0] sext_ln71_14_fu_478_p1;
wire  signed [16:0] sext_ln71_10_fu_446_p1;
wire  signed [16:0] tmp127_fu_1288_p2;
wire  signed [16:0] sext_ln71_117_fu_1150_p1;
wire  signed [16:0] sext_ln71_121_fu_1182_p1;
wire  signed [16:0] tmp128_fu_1298_p2;
wire  signed [16:0] sext_ln71_70_fu_842_p1;
wire  signed [16:0] sext_ln71_61_fu_786_p1;
wire  signed [16:0] sext_ln71_75_fu_874_p1;
wire  signed [16:0] sext_ln71_56_fu_754_p1;
wire  signed [16:0] sext_ln71_79_fu_902_p1;
wire  signed [16:0] sext_ln71_52_fu_726_p1;
wire  signed [16:0] sext_ln71_100_fu_1030_p1;
wire  signed [16:0] sext_ln71_31_fu_598_p1;
wire  signed [16:0] sext_ln71_105_fu_1062_p1;
wire  signed [16:0] sext_ln71_26_fu_566_p1;
wire  signed [15:0] p_ZL19H_filter_FIR_kernel_102_load_cast_fu_1338_p0;
wire  signed [15:0] p_ZL19H_filter_FIR_kernel_21_load_cast_fu_1342_p0;
wire  signed [16:0] p_ZL19H_filter_FIR_kernel_21_load_cast_fu_1342_p1;
wire  signed [16:0] p_ZL19H_filter_FIR_kernel_102_load_cast_fu_1338_p1;
wire  signed [16:0] sext_ln71_114_fu_1126_p1;
wire  signed [16:0] sext_ln71_17_fu_502_p1;
wire   [16:0] tmp107_fu_1352_p2;
wire   [23:0] tmp_11_fu_1358_p3;
wire   [18:0] tmp_12_fu_1370_p3;
wire  signed [24:0] p_shl191_fu_1378_p1;
wire  signed [24:0] p_shl189_fu_1366_p1;
wire  signed [16:0] sext_ln71_115_fu_1134_p1;
wire  signed [16:0] sext_ln71_16_fu_494_p1;
wire   [16:0] tmp109_fu_1388_p2;
wire   [22:0] tmp_13_fu_1394_p3;
wire   [19:0] tmp_14_fu_1406_p3;
wire  signed [24:0] p_shl187_fu_1402_p1;
wire  signed [24:0] p_shl188_fu_1414_p1;
wire  signed [16:0] sext_ln71_118_fu_1158_p1;
wire  signed [16:0] sext_ln71_13_fu_470_p1;
wire  signed [16:0] sext_ln71_122_fu_1190_p1;
wire  signed [16:0] sext_ln71_9_fu_438_p1;
wire  signed [16:0] sext_ln71_123_fu_1198_p1;
wire  signed [16:0] sext_ln71_8_fu_430_p1;
wire  signed [16:0] sext_ln71_125_fu_1214_p1;
wire  signed [16:0] sext_ln71_fu_414_p1;
wire   [24:0] tmp108_fu_1382_p2;
wire   [24:0] tmp110_fu_1418_p2;
wire   [7:0] tmp8_fu_2315_p1;
wire   [28:0] tmp_1_fu_2321_p3;
wire   [23:0] tmp_2_fu_2332_p3;
wire  signed [29:0] p_shl201_fu_2328_p1;
wire  signed [29:0] p_shl202_fu_2339_p1;
wire   [25:0] tmp_3_fu_2349_p3;
wire   [17:0] tmp_4_fu_2360_p3;
wire  signed [27:0] p_shl199_fu_2356_p1;
wire  signed [27:0] p_shl200_fu_2367_p1;
wire   [27:0] tmp36_fu_2371_p2;
wire   [21:0] tmp_5_fu_2381_p3;
wire   [19:0] tmp_6_fu_2392_p3;
wire  signed [22:0] p_shl197_fu_2388_p1;
wire  signed [22:0] p_shl198_fu_2399_p1;
wire  signed [22:0] tmp44_fu_2403_p2;
wire   [23:0] tmp_7_fu_2413_p3;
wire  signed [25:0] p_shl194_fu_2420_p1;
wire   [19:0] tmp_8_fu_2430_p3;
wire   [25:0] p_neg195_fu_2424_p2;
wire  signed [25:0] p_shl196_fu_2437_p1;
wire   [24:0] tmp_9_fu_2447_p3;
wire   [20:0] tmp_10_fu_2458_p3;
wire  signed [25:0] p_shl192_fu_2454_p1;
wire  signed [25:0] p_shl193_fu_2465_p1;
wire  signed [18:0] tmp_fu_2475_p3;
wire   [22:0] tmp_15_fu_2486_p3;
wire  signed [24:0] p_shl184_fu_2493_p1;
wire   [20:0] tmp_16_fu_2503_p3;
wire   [24:0] p_neg185_fu_2497_p2;
wire  signed [24:0] p_shl186_fu_2510_p1;
wire   [22:0] tmp_17_fu_2520_p3;
wire   [17:0] tmp_18_fu_2531_p3;
wire  signed [23:0] p_shl183_fu_2538_p1;
wire  signed [23:0] p_shl181_fu_2527_p1;
wire  signed [23:0] tmp116_fu_2542_p2;
wire   [22:0] tmp_19_fu_2552_p3;
wire   [18:0] tmp_20_fu_2563_p3;
wire  signed [23:0] p_shl179_fu_2559_p1;
wire  signed [23:0] p_shl180_fu_2570_p1;
wire   [24:0] tmp_21_fu_2580_p3;
wire   [22:0] tmp_22_fu_2591_p3;
wire  signed [25:0] p_shl178_fu_2598_p1;
wire  signed [25:0] p_shl_fu_2587_p1;
wire  signed [25:0] grp_fu_3073_p4;
wire  signed [24:0] grp_fu_3110_p4;
wire  signed [25:0] sext_ln71_159_fu_2614_p1;
wire  signed [25:0] sext_ln71_158_fu_2611_p1;
wire  signed [24:0] grp_fu_2923_p4;
wire  signed [24:0] grp_fu_2934_p4;
wire  signed [25:0] sext_ln71_163_fu_2626_p1;
wire  signed [25:0] sext_ln71_162_fu_2623_p1;
wire   [25:0] add_ln71_50_fu_2629_p2;
wire  signed [23:0] grp_fu_3121_p4;
wire  signed [25:0] grp_fu_3132_p4;
wire  signed [25:0] sext_ln71_165_fu_2639_p1;
(* use_dsp48 = "no" *) wire   [25:0] add_ln71_53_fu_2642_p2;
wire  signed [26:0] sext_ln71_166_fu_2647_p1;
wire  signed [26:0] sext_ln71_164_fu_2635_p1;
wire  signed [29:0] grp_fu_3153_p4;
wire  signed [30:0] sext_ln71_128_fu_2660_p1;
wire  signed [30:0] sext_ln71_127_fu_2657_p1;
wire  signed [28:0] grp_fu_3164_p4;
wire  signed [28:0] sext_ln71_131_fu_2672_p1;
wire  signed [28:0] grp_fu_3175_p4;
(* use_dsp48 = "no" *) wire   [28:0] add_ln71_11_fu_2675_p2;
wire  signed [29:0] sext_ln71_132_fu_2680_p1;
wire  signed [29:0] sext_ln71_130_fu_2669_p1;
wire  signed [27:0] grp_fu_3186_p4;
wire  signed [27:0] grp_fu_3197_p4;
wire  signed [27:0] grp_fu_3208_p4;
wire  signed [28:0] sext_ln71_137_fu_2696_p1;
wire  signed [28:0] sext_ln71_136_fu_2693_p1;
wire  signed [26:0] grp_fu_3219_p4;
wire  signed [26:0] grp_fu_3230_p4;
wire  signed [27:0] sext_ln71_141_fu_2708_p1;
wire  signed [27:0] sext_ln71_140_fu_2705_p1;
wire   [27:0] add_ln71_22_fu_2711_p2;
wire  signed [26:0] grp_fu_3241_p4;
wire  signed [26:0] grp_fu_3252_p4;
wire  signed [27:0] sext_ln71_144_fu_2724_p1;
wire  signed [27:0] sext_ln71_143_fu_2721_p1;
wire   [27:0] add_ln71_25_fu_2727_p2;
wire  signed [28:0] sext_ln71_145_fu_2733_p1;
wire  signed [28:0] sext_ln71_142_fu_2717_p1;
wire  signed [26:0] grp_fu_3263_p4;
wire  signed [25:0] grp_fu_3274_p4;
wire  signed [26:0] sext_ln71_151_fu_2749_p1;
wire  signed [26:0] sext_ln71_150_fu_2746_p1;
wire  signed [26:0] grp_fu_3285_p4;
wire  signed [24:0] grp_fu_3296_p4;
wire  signed [25:0] sext_ln71_156_fu_2764_p1;
wire  signed [25:0] sext_ln71_155_fu_2761_p1;
wire   [25:0] add_ln71_39_fu_2767_p2;
wire  signed [27:0] sext_ln71_168_fu_2773_p1;
wire  signed [27:0] sext_ln71_154_fu_2758_p1;
wire  signed [31:0] sext_ln71_129_fu_2783_p1;
wire  signed [31:0] grp_fu_3317_p4;
wire  signed [31:0] sext_ln71_133_fu_2791_p1;
(* use_dsp48 = "no" *) wire   [31:0] add_ln71_6_fu_2786_p2;
wire  signed [28:0] grp_fu_3328_p4;
wire  signed [29:0] sext_ln71_138_fu_2803_p1;
wire  signed [29:0] sext_ln71_135_fu_2800_p1;
wire   [29:0] add_ln71_19_fu_2806_p2;
wire  signed [30:0] sext_ln71_146_fu_2816_p1;
wire  signed [30:0] sext_ln71_139_fu_2812_p1;
wire   [30:0] add_ln71_27_fu_2819_p2;
wire  signed [31:0] sext_ln71_147_fu_2825_p1;
wire   [31:0] add_ln71_13_fu_2794_p2;
wire  signed [27:0] grp_fu_3339_p4;
wire  signed [28:0] sext_ln71_152_fu_2838_p1;
wire  signed [28:0] sext_ln71_149_fu_2835_p1;
wire  signed [28:0] sext_ln71_169_fu_2847_p1;
wire   [28:0] add_ln71_34_fu_2841_p2;
wire   [28:0] add_ln71_41_fu_2850_p2;
wire  signed [25:0] grp_fu_3350_p4;
wire  signed [26:0] sext_ln71_160_fu_2863_p1;
wire  signed [26:0] sext_ln71_157_fu_2860_p1;
wire   [26:0] add_ln71_47_fu_2866_p2;
wire  signed [27:0] sext_ln71_167_fu_2876_p1;
wire  signed [27:0] sext_ln71_161_fu_2872_p1;
wire   [27:0] add_ln71_55_fu_2879_p2;
wire  signed [29:0] sext_ln71_171_fu_2885_p1;
wire  signed [29:0] sext_ln71_170_fu_2856_p1;
wire   [29:0] add_ln71_56_fu_2889_p2;
wire  signed [31:0] sext_ln71_172_fu_2895_p1;
wire   [31:0] add_ln71_28_fu_2829_p2;
wire   [31:0] FIR_accu32_fu_2899_p2;
wire   [8:0] grp_fu_2915_p2;
wire   [5:0] grp_fu_2923_p2;
wire  signed [7:0] grp_fu_2934_p2;
wire   [14:0] grp_fu_2945_p2;
wire  signed [12:0] grp_fu_2953_p2;
wire  signed [29:0] grp_fu_2953_p3;
wire  signed [12:0] grp_fu_2963_p2;
wire   [11:0] grp_fu_2971_p2;
wire  signed [26:0] grp_fu_2971_p3;
wire  signed [11:0] grp_fu_2981_p2;
wire   [10:0] grp_fu_2989_p2;
wire   [10:0] grp_fu_2999_p2;
wire  signed [10:0] grp_fu_3007_p2;
wire   [9:0] grp_fu_3015_p2;
wire  signed [9:0] grp_fu_3023_p2;
wire   [9:0] grp_fu_3031_p2;
wire  signed [9:0] grp_fu_3039_p2;
wire   [8:0] grp_fu_3047_p2;
wire  signed [9:0] grp_fu_3055_p2;
wire  signed [25:0] grp_fu_3055_p3;
wire   [8:0] grp_fu_3065_p2;
wire  signed [6:0] grp_fu_3073_p2;
wire  signed [25:0] grp_fu_3073_p3;
wire  signed [8:0] grp_fu_3084_p2;
wire   [7:0] grp_fu_3094_p2;
wire  signed [8:0] grp_fu_3102_p2;
wire   [6:0] grp_fu_3110_p2;
wire  signed [24:0] grp_fu_3110_p3;
wire   [5:0] grp_fu_3121_p2;
wire  signed [23:0] grp_fu_3121_p3;
wire   [6:0] grp_fu_3132_p2;
wire  signed [25:0] grp_fu_3132_p3;
wire  signed [13:0] grp_fu_3143_p2;
wire   [10:0] grp_fu_3153_p2;
wire  signed [10:0] grp_fu_3164_p2;
wire  signed [8:0] grp_fu_3175_p2;
wire   [6:0] grp_fu_3186_p2;
wire  signed [8:0] grp_fu_3197_p2;
wire   [8:0] grp_fu_3208_p2;
wire  signed [10:0] grp_fu_3219_p2;
wire  signed [9:0] grp_fu_3230_p2;
wire   [8:0] grp_fu_3241_p2;
wire  signed [9:0] grp_fu_3252_p2;
wire   [7:0] grp_fu_3263_p2;
wire   [6:0] grp_fu_3274_p2;
wire  signed [9:0] grp_fu_3285_p2;
wire   [4:0] grp_fu_3296_p2;
wire   [7:0] grp_fu_3307_p2;
wire   [13:0] grp_fu_3317_p2;
wire  signed [11:0] grp_fu_3328_p2;
wire  signed [9:0] grp_fu_3339_p2;
wire  signed [6:0] grp_fu_3350_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to4;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 p_ZL19H_filter_FIR_kernel_122 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_121 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_120 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_119 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_118 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_117 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_116 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_115 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_114 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_113 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_112 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_111 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_110 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_109 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_108 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_107 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_106 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_105 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_104 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_103 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_102 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_101 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_100 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_99 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_98 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_97 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_96 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_95 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_94 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_93 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_92 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_91 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_90 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_89 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_88 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_87 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_86 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_85 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_84 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_83 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_82 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_81 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_80 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_79 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_78 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_77 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_76 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_75 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_74 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_73 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_72 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_71 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_70 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_69 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_68 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_67 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_66 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_65 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_64 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_63 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_62 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_61 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_60 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_59 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_58 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_57 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_56 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_55 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_54 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_53 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_52 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_51 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_50 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_49 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_48 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_47 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_46 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_45 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_44 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_43 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_42 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_41 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_40 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_39 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_38 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_37 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_36 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_35 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_34 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_33 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_32 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_31 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_30 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_29 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_28 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_27 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_26 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_25 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_24 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_23 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_22 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_21 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_20 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_19 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_18 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_17 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_16 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_15 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_14 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_13 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_12 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_11 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_10 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_9 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_8 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_7 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_6 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_5 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_4 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_3 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_2 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_1 = 16'd0;
#0 p_ZL19H_filter_FIR_kernel_0 = 16'd0;
end

FIR_Halfband_v1_mul_18s_8ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 25 ))
mul_18s_8ns_25_1_1_U1(
    .din0(tmp7_reg_3561_pp0_iter1_reg),
    .din1(tmp8_fu_2315_p1),
    .dout(tmp8_fu_2315_p2)
);

FIR_Halfband_v1_am_addmul_17s_17s_9ns_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 17 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 27 ))
am_addmul_17s_17s_9ns_27_4_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp93_fu_1236_p2),
    .din1(tmp4_fu_1226_p2),
    .din2(grp_fu_2915_p2),
    .ce(1'b1),
    .dout(grp_fu_2915_p3)
);

FIR_Halfband_v1_ama_addmuladd_17s_17s_6ns_25s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 17 ),
    .din2_WIDTH( 6 ),
    .din3_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
ama_addmuladd_17s_17s_6ns_25s_25_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp126_fu_1278_p2),
    .din1(tmp125_fu_1268_p2),
    .din2(grp_fu_2923_p2),
    .din3(tmp8_fu_2315_p2),
    .ce(1'b1),
    .dout(grp_fu_2923_p4)
);

FIR_Halfband_v1_ama_addmuladd_17s_17s_8s_24s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 17 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 24 ),
    .dout_WIDTH( 25 ))
ama_addmuladd_17s_17s_8s_24s_25_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp128_fu_1298_p2),
    .din1(tmp127_fu_1288_p2),
    .din2(grp_fu_2934_p2),
    .din3(tmp116_fu_2542_p2),
    .ce(1'b1),
    .dout(grp_fu_2934_p4)
);

FIR_Halfband_v1_am_addmul_16s_16s_15ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 32 ))
am_addmul_16s_16s_15ns_32_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_66_fu_818_p0),
    .din1(sext_ln71_65_fu_810_p0),
    .din2(grp_fu_2945_p2),
    .ce(1'b1),
    .dout(grp_fu_2945_p3)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_13s_30s_30_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .din3_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
ama_addmuladd_16s_16s_13s_30s_30_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_69_fu_834_p0),
    .din1(sext_ln71_62_fu_794_p0),
    .din2(grp_fu_2953_p2),
    .din3(grp_fu_2953_p3),
    .ce(1'b1),
    .dout(grp_fu_2953_p4)
);

FIR_Halfband_v1_am_addmul_16s_16s_13s_30_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 30 ))
am_addmul_16s_16s_13s_30_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_72_fu_854_p0),
    .din1(sext_ln71_59_fu_774_p0),
    .din2(grp_fu_2963_p2),
    .ce(1'b1),
    .dout(grp_fu_2963_p3)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_12ns_27s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 27 ),
    .dout_WIDTH( 29 ))
ama_addmuladd_16s_16s_12ns_27s_29_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_74_fu_866_p0),
    .din1(sext_ln71_57_fu_762_p0),
    .din2(grp_fu_2971_p2),
    .din3(grp_fu_2971_p3),
    .ce(1'b1),
    .dout(grp_fu_2971_p4)
);

FIR_Halfband_v1_am_addmul_16s_16s_12s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 29 ))
am_addmul_16s_16s_12s_29_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_76_fu_882_p0),
    .din1(sext_ln71_55_fu_746_p0),
    .din2(grp_fu_2981_p2),
    .ce(1'b1),
    .dout(grp_fu_2981_p3)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_11ns_23s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 11 ),
    .din3_WIDTH( 23 ),
    .dout_WIDTH( 28 ))
ama_addmuladd_16s_16s_11ns_23s_28_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_78_fu_894_p0),
    .din1(sext_ln71_53_fu_734_p0),
    .din2(grp_fu_2989_p2),
    .din3(tmp44_fu_2403_p2),
    .ce(1'b1),
    .dout(grp_fu_2989_p4)
);

FIR_Halfband_v1_am_addmul_16s_16s_11ns_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 28 ))
am_addmul_16s_16s_11ns_28_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_82_fu_918_p0),
    .din1(sext_ln71_49_fu_710_p0),
    .din2(grp_fu_2999_p2),
    .ce(1'b1),
    .dout(grp_fu_2999_p3)
);

FIR_Halfband_v1_am_addmul_16s_16s_11s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 28 ))
am_addmul_16s_16s_11s_28_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_84_fu_930_p0),
    .din1(sext_ln71_47_fu_698_p0),
    .din2(grp_fu_3007_p2),
    .ce(1'b1),
    .dout(grp_fu_3007_p3)
);

FIR_Halfband_v1_am_addmul_16s_16s_10ns_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 28 ))
am_addmul_16s_16s_10ns_28_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_86_fu_942_p0),
    .din1(sext_ln71_45_fu_686_p0),
    .din2(grp_fu_3015_p2),
    .ce(1'b1),
    .dout(grp_fu_3015_p3)
);

FIR_Halfband_v1_am_addmul_16s_16s_10s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 27 ))
am_addmul_16s_16s_10s_27_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_87_fu_950_p0),
    .din1(sext_ln71_44_fu_678_p0),
    .din2(grp_fu_3023_p2),
    .ce(1'b1),
    .dout(grp_fu_3023_p3)
);

FIR_Halfband_v1_am_addmul_16s_16s_10ns_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 27 ))
am_addmul_16s_16s_10ns_27_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_90_fu_970_p0),
    .din1(sext_ln71_41_fu_658_p0),
    .din2(grp_fu_3031_p2),
    .ce(1'b1),
    .dout(grp_fu_3031_p3)
);

FIR_Halfband_v1_am_addmul_16s_16s_10s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 10 ),
    .dout_WIDTH( 27 ))
am_addmul_16s_16s_10s_27_4_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_92_fu_982_p0),
    .din1(sext_ln71_39_fu_646_p0),
    .din2(grp_fu_3039_p2),
    .ce(1'b1),
    .dout(grp_fu_3039_p3)
);

FIR_Halfband_v1_am_addmul_16s_16s_9ns_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 27 ))
am_addmul_16s_16s_9ns_27_4_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_94_fu_994_p0),
    .din1(sext_ln71_37_fu_634_p0),
    .din2(grp_fu_3047_p2),
    .ce(1'b1),
    .dout(grp_fu_3047_p3)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_10s_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
ama_addmuladd_16s_16s_10s_26s_26_4_1_U18(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_99_fu_1022_p0),
    .din1(sext_ln71_32_fu_606_p0),
    .din2(grp_fu_3055_p2),
    .din3(grp_fu_3055_p3),
    .ce(1'b1),
    .dout(grp_fu_3055_p4)
);

FIR_Halfband_v1_am_addmul_16s_16s_9ns_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 26 ))
am_addmul_16s_16s_9ns_26_4_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_101_fu_1038_p0),
    .din1(sext_ln71_30_fu_590_p0),
    .din2(grp_fu_3065_p2),
    .ce(1'b1),
    .dout(grp_fu_3065_p3)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_7s_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
ama_addmuladd_16s_16s_7s_26s_26_4_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_104_fu_1054_p0),
    .din1(sext_ln71_27_fu_574_p0),
    .din2(grp_fu_3073_p2),
    .din3(grp_fu_3073_p3),
    .ce(1'b1),
    .dout(grp_fu_3073_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_9s_19s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 9 ),
    .din3_WIDTH( 19 ),
    .dout_WIDTH( 25 ))
ama_addmuladd_16s_16s_9s_19s_25_4_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_106_fu_1074_p0),
    .din1(sext_ln71_25_fu_554_p0),
    .din2(grp_fu_3084_p2),
    .din3(tmp_fu_2475_p3),
    .ce(1'b1),
    .dout(grp_fu_3084_p4)
);

FIR_Halfband_v1_am_addmul_16s_16s_8ns_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 25 ))
am_addmul_16s_16s_8ns_25_4_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_108_fu_1086_p0),
    .din1(sext_ln71_23_fu_542_p0),
    .din2(grp_fu_3094_p2),
    .ce(1'b1),
    .dout(grp_fu_3094_p3)
);

FIR_Halfband_v1_am_addmul_16s_16s_9s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 26 ))
am_addmul_16s_16s_9s_26_4_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_110_fu_1098_p0),
    .din1(sext_ln71_21_fu_530_p0),
    .din2(grp_fu_3102_p2),
    .ce(1'b1),
    .dout(grp_fu_3102_p3)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_7ns_25s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
ama_addmuladd_16s_16s_7ns_25s_25_4_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_116_fu_1142_p0),
    .din1(sext_ln71_15_fu_486_p0),
    .din2(grp_fu_3110_p2),
    .din3(grp_fu_3110_p3),
    .ce(1'b1),
    .dout(grp_fu_3110_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_6ns_24s_24_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 6 ),
    .din3_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
ama_addmuladd_16s_16s_6ns_24s_24_4_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln71_124_fu_1206_p0),
    .din1(sext_ln71_7_fu_422_p0),
    .din2(grp_fu_3121_p2),
    .din3(grp_fu_3121_p3),
    .ce(1'b1),
    .dout(grp_fu_3121_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_7ns_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
ama_addmuladd_16s_16s_7ns_26s_26_4_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_0_load_cast_fu_1222_p0),
    .din1(sext_ln66_fu_406_p0),
    .din2(grp_fu_3132_p2),
    .din3(grp_fu_3132_p3),
    .ce(1'b1),
    .dout(grp_fu_3132_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_14s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 14 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
ama_addmuladd_16s_16s_14s_32s_32_4_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_59_load_reg_3466),
    .din1(p_ZL19H_filter_FIR_kernel_64_load_reg_3451),
    .din2(grp_fu_3143_p2),
    .din3(grp_fu_2945_p3),
    .ce(1'b1),
    .dout(grp_fu_3143_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_11ns_30s_30_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 11 ),
    .din3_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
ama_addmuladd_16s_16s_11ns_30s_30_4_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_56_load_reg_3471),
    .din1(p_ZL19H_filter_FIR_kernel_67_load_reg_3446),
    .din2(grp_fu_3153_p2),
    .din3(grp_fu_2963_p3),
    .ce(1'b1),
    .dout(grp_fu_3153_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_11s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 11 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_addmuladd_16s_16s_11s_29s_29_4_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_54_load_reg_3476),
    .din1(p_ZL19H_filter_FIR_kernel_69_load_reg_3441),
    .din2(grp_fu_3164_p2),
    .din3(grp_fu_2971_p4),
    .ce(1'b1),
    .dout(grp_fu_3164_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_9s_29s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 9 ),
    .din3_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
ama_addmuladd_16s_16s_9s_29s_29_4_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_50_load_reg_3481),
    .din1(p_ZL19H_filter_FIR_kernel_73_load_reg_3436),
    .din2(grp_fu_3175_p2),
    .din3(grp_fu_2981_p3),
    .ce(1'b1),
    .dout(grp_fu_3175_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_7ns_28s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
ama_addmuladd_16s_16s_7ns_28s_28_4_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_46_load_reg_3491),
    .din1(p_ZL19H_filter_FIR_kernel_77_load_reg_3426),
    .din2(grp_fu_3186_p2),
    .din3(grp_fu_2999_p3),
    .ce(1'b1),
    .dout(grp_fu_3186_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_9s_28s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 9 ),
    .din3_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
ama_addmuladd_16s_16s_9s_28s_28_4_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_44_load_reg_3496),
    .din1(p_ZL19H_filter_FIR_kernel_79_load_reg_3421),
    .din2(grp_fu_3197_p2),
    .din3(grp_fu_3007_p3),
    .ce(1'b1),
    .dout(grp_fu_3197_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_9ns_28s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 9 ),
    .din3_WIDTH( 28 ),
    .dout_WIDTH( 28 ))
ama_addmuladd_16s_16s_9ns_28s_28_4_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_42_load_reg_3501),
    .din1(p_ZL19H_filter_FIR_kernel_81_load_reg_3416),
    .din2(grp_fu_3208_p2),
    .din3(grp_fu_3015_p3),
    .ce(1'b1),
    .dout(grp_fu_3208_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_11s_27s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 11 ),
    .din3_WIDTH( 27 ),
    .dout_WIDTH( 27 ))
ama_addmuladd_16s_16s_11s_27s_27_4_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_39_load_reg_3506),
    .din1(p_ZL19H_filter_FIR_kernel_84_load_reg_3411),
    .din2(grp_fu_3219_p2),
    .din3(grp_fu_3023_p3),
    .ce(1'b1),
    .dout(grp_fu_3219_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_10s_27s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 27 ),
    .dout_WIDTH( 27 ))
ama_addmuladd_16s_16s_10s_27s_27_4_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_36_load_reg_3511),
    .din1(p_ZL19H_filter_FIR_kernel_87_load_reg_3406),
    .din2(grp_fu_3230_p2),
    .din3(grp_fu_3031_p3),
    .ce(1'b1),
    .dout(grp_fu_3230_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_9ns_27s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 9 ),
    .din3_WIDTH( 27 ),
    .dout_WIDTH( 27 ))
ama_addmuladd_16s_16s_9ns_27s_27_4_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_34_load_reg_3516),
    .din1(p_ZL19H_filter_FIR_kernel_89_load_reg_3401),
    .din2(grp_fu_3241_p2),
    .din3(grp_fu_3039_p3),
    .ce(1'b1),
    .dout(grp_fu_3241_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_10s_27s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 27 ),
    .dout_WIDTH( 27 ))
ama_addmuladd_16s_16s_10s_27s_27_4_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_32_load_reg_3521),
    .din1(p_ZL19H_filter_FIR_kernel_91_load_reg_3396),
    .din2(grp_fu_3252_p2),
    .din3(grp_fu_3047_p3),
    .ce(1'b1),
    .dout(grp_fu_3252_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_8ns_27s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 27 ),
    .dout_WIDTH( 27 ))
ama_addmuladd_16s_16s_8ns_27s_27_4_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_29_load_reg_3531),
    .din1(p_ZL19H_filter_FIR_kernel_94_load_reg_3386),
    .din2(grp_fu_3263_p2),
    .din3(grp_fu_2915_p3),
    .ce(1'b1),
    .dout(grp_fu_3263_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_7ns_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
ama_addmuladd_16s_16s_7ns_26s_26_4_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_25_load_reg_3536),
    .din1(p_ZL19H_filter_FIR_kernel_98_load_reg_3381),
    .din2(grp_fu_3274_p2),
    .din3(grp_fu_3065_p3),
    .ce(1'b1),
    .dout(grp_fu_3274_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_10s_26s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 26 ),
    .dout_WIDTH( 27 ))
ama_addmuladd_16s_16s_10s_26s_27_4_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_24_load_reg_3541),
    .din1(p_ZL19H_filter_FIR_kernel_99_load_reg_3376),
    .din2(grp_fu_3285_p2),
    .din3(grp_fu_3073_p4),
    .ce(1'b1),
    .dout(grp_fu_3285_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_5ns_25s_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 5 ),
    .din3_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
ama_addmuladd_16s_16s_5ns_25s_25_4_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_19_load_reg_3546),
    .din1(p_ZL19H_filter_FIR_kernel_104_load_reg_3371),
    .din2(grp_fu_3296_p2),
    .din3(grp_fu_3094_p3),
    .ce(1'b1),
    .dout(grp_fu_3296_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_8ns_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
ama_addmuladd_16s_16s_8ns_26s_26_4_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_14_load_reg_3556),
    .din1(p_ZL19H_filter_FIR_kernel_109_load_reg_3361),
    .din2(grp_fu_3307_p2),
    .din3(grp_fu_3102_p3),
    .ce(1'b1),
    .dout(grp_fu_3307_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_14ns_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 14 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
ama_addmuladd_16s_16s_14ns_32s_32_4_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_60_load_reg_3461_pp0_iter1_reg),
    .din1(p_ZL19H_filter_FIR_kernel_63_load_reg_3456_pp0_iter1_reg),
    .din2(grp_fu_3317_p2),
    .din3(grp_fu_3143_p4),
    .ce(1'b1),
    .dout(grp_fu_3317_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_12s_28s_29_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 28 ),
    .dout_WIDTH( 29 ))
ama_addmuladd_16s_16s_12s_28s_29_4_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_47_load_reg_3486_pp0_iter1_reg),
    .din1(p_ZL19H_filter_FIR_kernel_76_load_reg_3431_pp0_iter1_reg),
    .din2(grp_fu_3328_p2),
    .din3(grp_fu_3186_p4),
    .ce(1'b1),
    .dout(grp_fu_3328_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_10s_27s_28_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 27 ),
    .dout_WIDTH( 28 ))
ama_addmuladd_16s_16s_10s_27s_28_4_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_31_load_reg_3526_pp0_iter1_reg),
    .din1(p_ZL19H_filter_FIR_kernel_92_load_reg_3391_pp0_iter1_reg),
    .din2(grp_fu_3339_p2),
    .din3(grp_fu_3263_p4),
    .ce(1'b1),
    .dout(grp_fu_3339_p4)
);

FIR_Halfband_v1_ama_addmuladd_16s_16s_7s_26s_26_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
ama_addmuladd_16s_16s_7s_26s_26_4_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(p_ZL19H_filter_FIR_kernel_17_load_reg_3551_pp0_iter1_reg),
    .din1(p_ZL19H_filter_FIR_kernel_106_load_reg_3366_pp0_iter1_reg),
    .din2(grp_fu_3350_p2),
    .din3(grp_fu_3307_p4),
    .ce(1'b1),
    .dout(grp_fu_3350_p4)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        add_ln71_10_reg_3765 <= grp_fu_2989_p4;
        add_ln71_31_reg_3770 <= grp_fu_3055_p4;
        add_ln71_37_reg_3780 <= grp_fu_3084_p4;
        add_ln71_3_reg_3755 <= grp_fu_2953_p4;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln71_12_reg_3805 <= add_ln71_12_fu_2684_p2;
        add_ln71_18_reg_3815 <= add_ln71_18_fu_2699_p2;
        add_ln71_26_reg_3820 <= add_ln71_26_fu_2737_p2;
        add_ln71_33_reg_3830 <= add_ln71_33_fu_2752_p2;
        add_ln71_40_reg_3835 <= add_ln71_40_fu_2777_p2;
        add_ln71_44_reg_3625_pp0_iter2_reg[24 : 2] <= add_ln71_44_reg_3625_pp0_iter1_reg[24 : 2];
        add_ln71_46_reg_3785 <= add_ln71_46_fu_2617_p2;
        add_ln71_46_reg_3785_pp0_iter4_reg <= add_ln71_46_reg_3785;
        add_ln71_54_reg_3790 <= add_ln71_54_fu_2651_p2;
        add_ln71_54_reg_3790_pp0_iter4_reg <= add_ln71_54_reg_3790;
        add_ln71_5_reg_3800 <= add_ln71_5_fu_2663_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln71_44_reg_3625[24 : 2] <= add_ln71_44_fu_1448_p2[24 : 2];
        add_ln71_44_reg_3625_pp0_iter1_reg[24 : 2] <= add_ln71_44_reg_3625[24 : 2];
        p_ZL19H_filter_FIR_kernel_104_load_reg_3371 <= p_ZL19H_filter_FIR_kernel_104;
        p_ZL19H_filter_FIR_kernel_106_load_reg_3366 <= p_ZL19H_filter_FIR_kernel_106;
        p_ZL19H_filter_FIR_kernel_106_load_reg_3366_pp0_iter1_reg <= p_ZL19H_filter_FIR_kernel_106_load_reg_3366;
        p_ZL19H_filter_FIR_kernel_109_load_reg_3361 <= p_ZL19H_filter_FIR_kernel_109;
        p_ZL19H_filter_FIR_kernel_14_load_reg_3556 <= p_ZL19H_filter_FIR_kernel_14;
        p_ZL19H_filter_FIR_kernel_17_load_reg_3551 <= p_ZL19H_filter_FIR_kernel_17;
        p_ZL19H_filter_FIR_kernel_17_load_reg_3551_pp0_iter1_reg <= p_ZL19H_filter_FIR_kernel_17_load_reg_3551;
        p_ZL19H_filter_FIR_kernel_19_load_reg_3546 <= p_ZL19H_filter_FIR_kernel_19;
        p_ZL19H_filter_FIR_kernel_24_load_reg_3541 <= p_ZL19H_filter_FIR_kernel_24;
        p_ZL19H_filter_FIR_kernel_25_load_reg_3536 <= p_ZL19H_filter_FIR_kernel_25;
        p_ZL19H_filter_FIR_kernel_29_load_reg_3531 <= p_ZL19H_filter_FIR_kernel_29;
        p_ZL19H_filter_FIR_kernel_31_load_reg_3526 <= p_ZL19H_filter_FIR_kernel_31;
        p_ZL19H_filter_FIR_kernel_31_load_reg_3526_pp0_iter1_reg <= p_ZL19H_filter_FIR_kernel_31_load_reg_3526;
        p_ZL19H_filter_FIR_kernel_32_load_reg_3521 <= p_ZL19H_filter_FIR_kernel_32;
        p_ZL19H_filter_FIR_kernel_34_load_reg_3516 <= p_ZL19H_filter_FIR_kernel_34;
        p_ZL19H_filter_FIR_kernel_36_load_reg_3511 <= p_ZL19H_filter_FIR_kernel_36;
        p_ZL19H_filter_FIR_kernel_39_load_reg_3506 <= p_ZL19H_filter_FIR_kernel_39;
        p_ZL19H_filter_FIR_kernel_42_load_reg_3501 <= p_ZL19H_filter_FIR_kernel_42;
        p_ZL19H_filter_FIR_kernel_44_load_reg_3496 <= p_ZL19H_filter_FIR_kernel_44;
        p_ZL19H_filter_FIR_kernel_46_load_reg_3491 <= p_ZL19H_filter_FIR_kernel_46;
        p_ZL19H_filter_FIR_kernel_47_load_reg_3486 <= p_ZL19H_filter_FIR_kernel_47;
        p_ZL19H_filter_FIR_kernel_47_load_reg_3486_pp0_iter1_reg <= p_ZL19H_filter_FIR_kernel_47_load_reg_3486;
        p_ZL19H_filter_FIR_kernel_50_load_reg_3481 <= p_ZL19H_filter_FIR_kernel_50;
        p_ZL19H_filter_FIR_kernel_54_load_reg_3476 <= p_ZL19H_filter_FIR_kernel_54;
        p_ZL19H_filter_FIR_kernel_56_load_reg_3471 <= p_ZL19H_filter_FIR_kernel_56;
        p_ZL19H_filter_FIR_kernel_59_load_reg_3466 <= p_ZL19H_filter_FIR_kernel_59;
        p_ZL19H_filter_FIR_kernel_60_load_reg_3461 <= p_ZL19H_filter_FIR_kernel_60;
        p_ZL19H_filter_FIR_kernel_60_load_reg_3461_pp0_iter1_reg <= p_ZL19H_filter_FIR_kernel_60_load_reg_3461;
        p_ZL19H_filter_FIR_kernel_63_load_reg_3456 <= p_ZL19H_filter_FIR_kernel_63;
        p_ZL19H_filter_FIR_kernel_63_load_reg_3456_pp0_iter1_reg <= p_ZL19H_filter_FIR_kernel_63_load_reg_3456;
        p_ZL19H_filter_FIR_kernel_64_load_reg_3451 <= p_ZL19H_filter_FIR_kernel_64;
        p_ZL19H_filter_FIR_kernel_67_load_reg_3446 <= p_ZL19H_filter_FIR_kernel_67;
        p_ZL19H_filter_FIR_kernel_69_load_reg_3441 <= p_ZL19H_filter_FIR_kernel_69;
        p_ZL19H_filter_FIR_kernel_73_load_reg_3436 <= p_ZL19H_filter_FIR_kernel_73;
        p_ZL19H_filter_FIR_kernel_76_load_reg_3431 <= p_ZL19H_filter_FIR_kernel_76;
        p_ZL19H_filter_FIR_kernel_76_load_reg_3431_pp0_iter1_reg <= p_ZL19H_filter_FIR_kernel_76_load_reg_3431;
        p_ZL19H_filter_FIR_kernel_77_load_reg_3426 <= p_ZL19H_filter_FIR_kernel_77;
        p_ZL19H_filter_FIR_kernel_79_load_reg_3421 <= p_ZL19H_filter_FIR_kernel_79;
        p_ZL19H_filter_FIR_kernel_81_load_reg_3416 <= p_ZL19H_filter_FIR_kernel_81;
        p_ZL19H_filter_FIR_kernel_84_load_reg_3411 <= p_ZL19H_filter_FIR_kernel_84;
        p_ZL19H_filter_FIR_kernel_87_load_reg_3406 <= p_ZL19H_filter_FIR_kernel_87;
        p_ZL19H_filter_FIR_kernel_89_load_reg_3401 <= p_ZL19H_filter_FIR_kernel_89;
        p_ZL19H_filter_FIR_kernel_91_load_reg_3396 <= p_ZL19H_filter_FIR_kernel_91;
        p_ZL19H_filter_FIR_kernel_92_load_reg_3391 <= p_ZL19H_filter_FIR_kernel_92;
        p_ZL19H_filter_FIR_kernel_92_load_reg_3391_pp0_iter1_reg <= p_ZL19H_filter_FIR_kernel_92_load_reg_3391;
        p_ZL19H_filter_FIR_kernel_94_load_reg_3386 <= p_ZL19H_filter_FIR_kernel_94;
        p_ZL19H_filter_FIR_kernel_98_load_reg_3381 <= p_ZL19H_filter_FIR_kernel_98;
        p_ZL19H_filter_FIR_kernel_99_load_reg_3376 <= p_ZL19H_filter_FIR_kernel_99;
        tmp113_reg_3601 <= tmp113_fu_1424_p2;
        tmp113_reg_3601_pp0_iter1_reg <= tmp113_reg_3601;
        tmp115_reg_3607 <= tmp115_fu_1430_p2;
        tmp115_reg_3607_pp0_iter1_reg <= tmp115_reg_3607;
        tmp117_reg_3613 <= tmp117_fu_1436_p2;
        tmp117_reg_3613_pp0_iter1_reg <= tmp117_reg_3613;
        tmp121_reg_3619 <= tmp121_fu_1442_p2;
        tmp121_reg_3619_pp0_iter1_reg <= tmp121_reg_3619;
        tmp25_reg_3566 <= tmp25_fu_1308_p2;
        tmp25_reg_3566_pp0_iter1_reg <= tmp25_reg_3566;
        tmp35_reg_3572 <= tmp35_fu_1314_p2;
        tmp35_reg_3572_pp0_iter1_reg <= tmp35_reg_3572;
        tmp43_reg_3578 <= tmp43_fu_1320_p2;
        tmp43_reg_3578_pp0_iter1_reg <= tmp43_reg_3578;
        tmp7_reg_3561 <= tmp7_fu_1262_p2;
        tmp7_reg_3561_pp0_iter1_reg <= tmp7_reg_3561;
        tmp81_reg_3584 <= tmp81_fu_1326_p2;
        tmp81_reg_3584_pp0_iter1_reg <= tmp81_reg_3584;
        tmp91_reg_3590 <= tmp91_fu_1332_p2;
        tmp91_reg_3590_pp0_iter1_reg <= tmp91_reg_3590;
        tmp931_reg_3596 <= tmp931_fu_1346_p2;
        tmp931_reg_3596_pp0_iter1_reg <= tmp931_reg_3596;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL19H_filter_FIR_kernel_0 <= p_ZL19H_filter_FIR_kernel_1;
        p_ZL19H_filter_FIR_kernel_1 <= p_ZL19H_filter_FIR_kernel_2;
        p_ZL19H_filter_FIR_kernel_10 <= p_ZL19H_filter_FIR_kernel_11;
        p_ZL19H_filter_FIR_kernel_100 <= p_ZL19H_filter_FIR_kernel_101;
        p_ZL19H_filter_FIR_kernel_101 <= p_ZL19H_filter_FIR_kernel_102;
        p_ZL19H_filter_FIR_kernel_102 <= p_ZL19H_filter_FIR_kernel_103;
        p_ZL19H_filter_FIR_kernel_103 <= p_ZL19H_filter_FIR_kernel_104;
        p_ZL19H_filter_FIR_kernel_104 <= p_ZL19H_filter_FIR_kernel_105;
        p_ZL19H_filter_FIR_kernel_105 <= p_ZL19H_filter_FIR_kernel_106;
        p_ZL19H_filter_FIR_kernel_106 <= p_ZL19H_filter_FIR_kernel_107;
        p_ZL19H_filter_FIR_kernel_107 <= p_ZL19H_filter_FIR_kernel_108;
        p_ZL19H_filter_FIR_kernel_108 <= p_ZL19H_filter_FIR_kernel_109;
        p_ZL19H_filter_FIR_kernel_109 <= p_ZL19H_filter_FIR_kernel_110;
        p_ZL19H_filter_FIR_kernel_11 <= p_ZL19H_filter_FIR_kernel_12;
        p_ZL19H_filter_FIR_kernel_110 <= p_ZL19H_filter_FIR_kernel_111;
        p_ZL19H_filter_FIR_kernel_111 <= p_ZL19H_filter_FIR_kernel_112;
        p_ZL19H_filter_FIR_kernel_112 <= p_ZL19H_filter_FIR_kernel_113;
        p_ZL19H_filter_FIR_kernel_113 <= p_ZL19H_filter_FIR_kernel_114;
        p_ZL19H_filter_FIR_kernel_114 <= p_ZL19H_filter_FIR_kernel_115;
        p_ZL19H_filter_FIR_kernel_115 <= p_ZL19H_filter_FIR_kernel_116;
        p_ZL19H_filter_FIR_kernel_116 <= p_ZL19H_filter_FIR_kernel_117;
        p_ZL19H_filter_FIR_kernel_117 <= p_ZL19H_filter_FIR_kernel_118;
        p_ZL19H_filter_FIR_kernel_118 <= p_ZL19H_filter_FIR_kernel_119;
        p_ZL19H_filter_FIR_kernel_119 <= p_ZL19H_filter_FIR_kernel_120;
        p_ZL19H_filter_FIR_kernel_12 <= p_ZL19H_filter_FIR_kernel_13;
        p_ZL19H_filter_FIR_kernel_120 <= p_ZL19H_filter_FIR_kernel_121;
        p_ZL19H_filter_FIR_kernel_121 <= p_ZL19H_filter_FIR_kernel_122;
        p_ZL19H_filter_FIR_kernel_122 <= x_n;
        p_ZL19H_filter_FIR_kernel_13 <= p_ZL19H_filter_FIR_kernel_14;
        p_ZL19H_filter_FIR_kernel_14 <= p_ZL19H_filter_FIR_kernel_15;
        p_ZL19H_filter_FIR_kernel_15 <= p_ZL19H_filter_FIR_kernel_16;
        p_ZL19H_filter_FIR_kernel_16 <= p_ZL19H_filter_FIR_kernel_17;
        p_ZL19H_filter_FIR_kernel_17 <= p_ZL19H_filter_FIR_kernel_18;
        p_ZL19H_filter_FIR_kernel_18 <= p_ZL19H_filter_FIR_kernel_19;
        p_ZL19H_filter_FIR_kernel_19 <= p_ZL19H_filter_FIR_kernel_20;
        p_ZL19H_filter_FIR_kernel_2 <= p_ZL19H_filter_FIR_kernel_3;
        p_ZL19H_filter_FIR_kernel_20 <= p_ZL19H_filter_FIR_kernel_21;
        p_ZL19H_filter_FIR_kernel_21 <= p_ZL19H_filter_FIR_kernel_22;
        p_ZL19H_filter_FIR_kernel_22 <= p_ZL19H_filter_FIR_kernel_23;
        p_ZL19H_filter_FIR_kernel_23 <= p_ZL19H_filter_FIR_kernel_24;
        p_ZL19H_filter_FIR_kernel_24 <= p_ZL19H_filter_FIR_kernel_25;
        p_ZL19H_filter_FIR_kernel_25 <= p_ZL19H_filter_FIR_kernel_26;
        p_ZL19H_filter_FIR_kernel_26 <= p_ZL19H_filter_FIR_kernel_27;
        p_ZL19H_filter_FIR_kernel_27 <= p_ZL19H_filter_FIR_kernel_28;
        p_ZL19H_filter_FIR_kernel_28 <= p_ZL19H_filter_FIR_kernel_29;
        p_ZL19H_filter_FIR_kernel_29 <= p_ZL19H_filter_FIR_kernel_30;
        p_ZL19H_filter_FIR_kernel_3 <= p_ZL19H_filter_FIR_kernel_4;
        p_ZL19H_filter_FIR_kernel_30 <= p_ZL19H_filter_FIR_kernel_31;
        p_ZL19H_filter_FIR_kernel_31 <= p_ZL19H_filter_FIR_kernel_32;
        p_ZL19H_filter_FIR_kernel_32 <= p_ZL19H_filter_FIR_kernel_33;
        p_ZL19H_filter_FIR_kernel_33 <= p_ZL19H_filter_FIR_kernel_34;
        p_ZL19H_filter_FIR_kernel_34 <= p_ZL19H_filter_FIR_kernel_35;
        p_ZL19H_filter_FIR_kernel_35 <= p_ZL19H_filter_FIR_kernel_36;
        p_ZL19H_filter_FIR_kernel_36 <= p_ZL19H_filter_FIR_kernel_37;
        p_ZL19H_filter_FIR_kernel_37 <= p_ZL19H_filter_FIR_kernel_38;
        p_ZL19H_filter_FIR_kernel_38 <= p_ZL19H_filter_FIR_kernel_39;
        p_ZL19H_filter_FIR_kernel_39 <= p_ZL19H_filter_FIR_kernel_40;
        p_ZL19H_filter_FIR_kernel_4 <= p_ZL19H_filter_FIR_kernel_5;
        p_ZL19H_filter_FIR_kernel_40 <= p_ZL19H_filter_FIR_kernel_41;
        p_ZL19H_filter_FIR_kernel_41 <= p_ZL19H_filter_FIR_kernel_42;
        p_ZL19H_filter_FIR_kernel_42 <= p_ZL19H_filter_FIR_kernel_43;
        p_ZL19H_filter_FIR_kernel_43 <= p_ZL19H_filter_FIR_kernel_44;
        p_ZL19H_filter_FIR_kernel_44 <= p_ZL19H_filter_FIR_kernel_45;
        p_ZL19H_filter_FIR_kernel_45 <= p_ZL19H_filter_FIR_kernel_46;
        p_ZL19H_filter_FIR_kernel_46 <= p_ZL19H_filter_FIR_kernel_47;
        p_ZL19H_filter_FIR_kernel_47 <= p_ZL19H_filter_FIR_kernel_48;
        p_ZL19H_filter_FIR_kernel_48 <= p_ZL19H_filter_FIR_kernel_49;
        p_ZL19H_filter_FIR_kernel_49 <= p_ZL19H_filter_FIR_kernel_50;
        p_ZL19H_filter_FIR_kernel_5 <= p_ZL19H_filter_FIR_kernel_6;
        p_ZL19H_filter_FIR_kernel_50 <= p_ZL19H_filter_FIR_kernel_51;
        p_ZL19H_filter_FIR_kernel_51 <= p_ZL19H_filter_FIR_kernel_52;
        p_ZL19H_filter_FIR_kernel_52 <= p_ZL19H_filter_FIR_kernel_53;
        p_ZL19H_filter_FIR_kernel_53 <= p_ZL19H_filter_FIR_kernel_54;
        p_ZL19H_filter_FIR_kernel_54 <= p_ZL19H_filter_FIR_kernel_55;
        p_ZL19H_filter_FIR_kernel_55 <= p_ZL19H_filter_FIR_kernel_56;
        p_ZL19H_filter_FIR_kernel_56 <= p_ZL19H_filter_FIR_kernel_57;
        p_ZL19H_filter_FIR_kernel_57 <= p_ZL19H_filter_FIR_kernel_58;
        p_ZL19H_filter_FIR_kernel_58 <= p_ZL19H_filter_FIR_kernel_59;
        p_ZL19H_filter_FIR_kernel_59 <= p_ZL19H_filter_FIR_kernel_60;
        p_ZL19H_filter_FIR_kernel_6 <= p_ZL19H_filter_FIR_kernel_7;
        p_ZL19H_filter_FIR_kernel_60 <= p_ZL19H_filter_FIR_kernel_61;
        p_ZL19H_filter_FIR_kernel_61 <= p_ZL19H_filter_FIR_kernel_62;
        p_ZL19H_filter_FIR_kernel_62 <= p_ZL19H_filter_FIR_kernel_63;
        p_ZL19H_filter_FIR_kernel_63 <= p_ZL19H_filter_FIR_kernel_64;
        p_ZL19H_filter_FIR_kernel_64 <= p_ZL19H_filter_FIR_kernel_65;
        p_ZL19H_filter_FIR_kernel_65 <= p_ZL19H_filter_FIR_kernel_66;
        p_ZL19H_filter_FIR_kernel_66 <= p_ZL19H_filter_FIR_kernel_67;
        p_ZL19H_filter_FIR_kernel_67 <= p_ZL19H_filter_FIR_kernel_68;
        p_ZL19H_filter_FIR_kernel_68 <= p_ZL19H_filter_FIR_kernel_69;
        p_ZL19H_filter_FIR_kernel_69 <= p_ZL19H_filter_FIR_kernel_70;
        p_ZL19H_filter_FIR_kernel_7 <= p_ZL19H_filter_FIR_kernel_8;
        p_ZL19H_filter_FIR_kernel_70 <= p_ZL19H_filter_FIR_kernel_71;
        p_ZL19H_filter_FIR_kernel_71 <= p_ZL19H_filter_FIR_kernel_72;
        p_ZL19H_filter_FIR_kernel_72 <= p_ZL19H_filter_FIR_kernel_73;
        p_ZL19H_filter_FIR_kernel_73 <= p_ZL19H_filter_FIR_kernel_74;
        p_ZL19H_filter_FIR_kernel_74 <= p_ZL19H_filter_FIR_kernel_75;
        p_ZL19H_filter_FIR_kernel_75 <= p_ZL19H_filter_FIR_kernel_76;
        p_ZL19H_filter_FIR_kernel_76 <= p_ZL19H_filter_FIR_kernel_77;
        p_ZL19H_filter_FIR_kernel_77 <= p_ZL19H_filter_FIR_kernel_78;
        p_ZL19H_filter_FIR_kernel_78 <= p_ZL19H_filter_FIR_kernel_79;
        p_ZL19H_filter_FIR_kernel_79 <= p_ZL19H_filter_FIR_kernel_80;
        p_ZL19H_filter_FIR_kernel_8 <= p_ZL19H_filter_FIR_kernel_9;
        p_ZL19H_filter_FIR_kernel_80 <= p_ZL19H_filter_FIR_kernel_81;
        p_ZL19H_filter_FIR_kernel_81 <= p_ZL19H_filter_FIR_kernel_82;
        p_ZL19H_filter_FIR_kernel_82 <= p_ZL19H_filter_FIR_kernel_83;
        p_ZL19H_filter_FIR_kernel_83 <= p_ZL19H_filter_FIR_kernel_84;
        p_ZL19H_filter_FIR_kernel_84 <= p_ZL19H_filter_FIR_kernel_85;
        p_ZL19H_filter_FIR_kernel_85 <= p_ZL19H_filter_FIR_kernel_86;
        p_ZL19H_filter_FIR_kernel_86 <= p_ZL19H_filter_FIR_kernel_87;
        p_ZL19H_filter_FIR_kernel_87 <= p_ZL19H_filter_FIR_kernel_88;
        p_ZL19H_filter_FIR_kernel_88 <= p_ZL19H_filter_FIR_kernel_89;
        p_ZL19H_filter_FIR_kernel_89 <= p_ZL19H_filter_FIR_kernel_90;
        p_ZL19H_filter_FIR_kernel_9 <= p_ZL19H_filter_FIR_kernel_10;
        p_ZL19H_filter_FIR_kernel_90 <= p_ZL19H_filter_FIR_kernel_91;
        p_ZL19H_filter_FIR_kernel_91 <= p_ZL19H_filter_FIR_kernel_92;
        p_ZL19H_filter_FIR_kernel_92 <= p_ZL19H_filter_FIR_kernel_93;
        p_ZL19H_filter_FIR_kernel_93 <= p_ZL19H_filter_FIR_kernel_94;
        p_ZL19H_filter_FIR_kernel_94 <= p_ZL19H_filter_FIR_kernel_95;
        p_ZL19H_filter_FIR_kernel_95 <= p_ZL19H_filter_FIR_kernel_96;
        p_ZL19H_filter_FIR_kernel_96 <= p_ZL19H_filter_FIR_kernel_97;
        p_ZL19H_filter_FIR_kernel_97 <= p_ZL19H_filter_FIR_kernel_98;
        p_ZL19H_filter_FIR_kernel_98 <= p_ZL19H_filter_FIR_kernel_99;
        p_ZL19H_filter_FIR_kernel_99 <= p_ZL19H_filter_FIR_kernel_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign FIR_accu32_fu_2899_p2 = ($signed(sext_ln71_172_fu_2895_p1) + $signed(add_ln71_28_fu_2829_p2));

assign add_ln71_11_fu_2675_p2 = ($signed(sext_ln71_131_fu_2672_p1) + $signed(grp_fu_3175_p4));

assign add_ln71_12_fu_2684_p2 = ($signed(sext_ln71_132_fu_2680_p1) + $signed(sext_ln71_130_fu_2669_p1));

assign add_ln71_13_fu_2794_p2 = ($signed(sext_ln71_133_fu_2791_p1) + $signed(add_ln71_6_fu_2786_p2));

assign add_ln71_18_fu_2699_p2 = ($signed(sext_ln71_137_fu_2696_p1) + $signed(sext_ln71_136_fu_2693_p1));

assign add_ln71_19_fu_2806_p2 = ($signed(sext_ln71_138_fu_2803_p1) + $signed(sext_ln71_135_fu_2800_p1));

assign add_ln71_22_fu_2711_p2 = ($signed(sext_ln71_141_fu_2708_p1) + $signed(sext_ln71_140_fu_2705_p1));

assign add_ln71_25_fu_2727_p2 = ($signed(sext_ln71_144_fu_2724_p1) + $signed(sext_ln71_143_fu_2721_p1));

assign add_ln71_26_fu_2737_p2 = ($signed(sext_ln71_145_fu_2733_p1) + $signed(sext_ln71_142_fu_2717_p1));

assign add_ln71_27_fu_2819_p2 = ($signed(sext_ln71_146_fu_2816_p1) + $signed(sext_ln71_139_fu_2812_p1));

assign add_ln71_28_fu_2829_p2 = ($signed(sext_ln71_147_fu_2825_p1) + $signed(add_ln71_13_fu_2794_p2));

assign add_ln71_33_fu_2752_p2 = ($signed(sext_ln71_151_fu_2749_p1) + $signed(sext_ln71_150_fu_2746_p1));

assign add_ln71_34_fu_2841_p2 = ($signed(sext_ln71_152_fu_2838_p1) + $signed(sext_ln71_149_fu_2835_p1));

assign add_ln71_39_fu_2767_p2 = ($signed(sext_ln71_156_fu_2764_p1) + $signed(sext_ln71_155_fu_2761_p1));

assign add_ln71_40_fu_2777_p2 = ($signed(sext_ln71_168_fu_2773_p1) + $signed(sext_ln71_154_fu_2758_p1));

assign add_ln71_41_fu_2850_p2 = ($signed(sext_ln71_169_fu_2847_p1) + $signed(add_ln71_34_fu_2841_p2));

assign add_ln71_44_fu_1448_p2 = (tmp108_fu_1382_p2 + tmp110_fu_1418_p2);

assign add_ln71_46_fu_2617_p2 = ($signed(sext_ln71_159_fu_2614_p1) + $signed(sext_ln71_158_fu_2611_p1));

assign add_ln71_47_fu_2866_p2 = ($signed(sext_ln71_160_fu_2863_p1) + $signed(sext_ln71_157_fu_2860_p1));

assign add_ln71_50_fu_2629_p2 = ($signed(sext_ln71_163_fu_2626_p1) + $signed(sext_ln71_162_fu_2623_p1));

assign add_ln71_53_fu_2642_p2 = ($signed(grp_fu_3132_p4) + $signed(sext_ln71_165_fu_2639_p1));

assign add_ln71_54_fu_2651_p2 = ($signed(sext_ln71_166_fu_2647_p1) + $signed(sext_ln71_164_fu_2635_p1));

assign add_ln71_55_fu_2879_p2 = ($signed(sext_ln71_167_fu_2876_p1) + $signed(sext_ln71_161_fu_2872_p1));

assign add_ln71_56_fu_2889_p2 = ($signed(sext_ln71_171_fu_2885_p1) + $signed(sext_ln71_170_fu_2856_p1));

assign add_ln71_5_fu_2663_p2 = ($signed(sext_ln71_128_fu_2660_p1) + $signed(sext_ln71_127_fu_2657_p1));

assign add_ln71_6_fu_2786_p2 = ($signed(sext_ln71_129_fu_2783_p1) + $signed(grp_fu_3317_p4));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = {{FIR_accu32_fu_2899_p2[31:16]}};

assign grp_fu_2915_p2 = 27'd374;

assign grp_fu_2923_p2 = 25'd58;

assign grp_fu_2934_p2 = 25'd33554356;

assign grp_fu_2945_p2 = 32'd30324;

assign grp_fu_2953_p2 = 30'd1073738540;

assign grp_fu_2953_p3 = ($signed(p_shl201_fu_2328_p1) - $signed(p_shl202_fu_2339_p1));

assign grp_fu_2963_p2 = 30'd1073738936;

assign grp_fu_2971_p2 = 29'd2276;

assign grp_fu_2971_p3 = tmp36_fu_2371_p2;

assign grp_fu_2981_p2 = 29'd536869042;

assign grp_fu_2989_p2 = 28'd1564;

assign grp_fu_2999_p2 = 28'd1120;

assign grp_fu_3007_p2 = 28'd268434506;

assign grp_fu_3015_p2 = 28'd798;

assign grp_fu_3023_p2 = 27'd134217384;

assign grp_fu_3031_p2 = 27'd546;

assign grp_fu_3039_p2 = 27'd134217284;

assign grp_fu_3047_p2 = 27'd348;

assign grp_fu_3055_p2 = 26'd67108508;

assign grp_fu_3055_p3 = ($signed(p_neg195_fu_2424_p2) - $signed(p_shl196_fu_2437_p1));

assign grp_fu_3065_p2 = 26'd330;

assign grp_fu_3073_p2 = 24'd16777174;

assign grp_fu_3073_p3 = ($signed(p_shl192_fu_2454_p1) + $signed(p_shl193_fu_2465_p1));

assign grp_fu_3084_p2 = 25'd33554190;

assign grp_fu_3094_p2 = 25'd210;

assign grp_fu_3102_p2 = 26'd67108684;

assign grp_fu_3110_p2 = 25'd98;

assign grp_fu_3110_p3 = ($signed(p_neg185_fu_2497_p2) - $signed(p_shl186_fu_2510_p1));

assign grp_fu_3121_p2 = 24'd52;

assign grp_fu_3121_p3 = ($signed(p_shl179_fu_2559_p1) - $signed(p_shl180_fu_2570_p1));

assign grp_fu_3132_p2 = 25'd100;

assign grp_fu_3132_p3 = ($signed(p_shl178_fu_2598_p1) - $signed(p_shl_fu_2587_p1));

assign grp_fu_3143_p2 = 31'd2147476988;

assign grp_fu_3153_p2 = 29'd1706;

assign grp_fu_3164_p2 = 28'd268434498;

assign grp_fu_3175_p2 = 26'd67108638;

assign grp_fu_3186_p2 = 25'd118;

assign grp_fu_3197_p2 = 26'd67108642;

assign grp_fu_3208_p2 = 27'd294;

assign grp_fu_3219_p2 = 27'd134217062;

assign grp_fu_3230_p2 = 27'd134217336;

assign grp_fu_3241_p2 = 27'd394;

assign grp_fu_3252_p2 = 27'd134217338;

assign grp_fu_3263_p2 = 26'd196;

assign grp_fu_3274_p2 = 25'd82;

assign grp_fu_3285_p2 = 27'd134217424;

assign grp_fu_3296_p2 = 23'd22;

assign grp_fu_3307_p2 = 26'd150;

assign grp_fu_3317_p2 = 32'd8952;

assign grp_fu_3328_p2 = 29'd536869588;

assign grp_fu_3339_p2 = 27'd134217460;

assign grp_fu_3350_p2 = 24'd16777170;

assign p_ZL19H_filter_FIR_kernel_0_load_cast_fu_1222_p0 = p_ZL19H_filter_FIR_kernel_0;

assign p_ZL19H_filter_FIR_kernel_102_load_cast_fu_1338_p0 = p_ZL19H_filter_FIR_kernel_102;

assign p_ZL19H_filter_FIR_kernel_102_load_cast_fu_1338_p1 = p_ZL19H_filter_FIR_kernel_102_load_cast_fu_1338_p0;

assign p_ZL19H_filter_FIR_kernel_21_load_cast_fu_1342_p0 = p_ZL19H_filter_FIR_kernel_21;

assign p_ZL19H_filter_FIR_kernel_21_load_cast_fu_1342_p1 = p_ZL19H_filter_FIR_kernel_21_load_cast_fu_1342_p0;

assign p_neg185_fu_2497_p2 = ($signed(25'd0) - $signed(p_shl184_fu_2493_p1));

assign p_neg195_fu_2424_p2 = ($signed(26'd0) - $signed(p_shl194_fu_2420_p1));

assign p_shl178_fu_2598_p1 = $signed(tmp_22_fu_2591_p3);

assign p_shl179_fu_2559_p1 = $signed(tmp_19_fu_2552_p3);

assign p_shl180_fu_2570_p1 = $signed(tmp_20_fu_2563_p3);

assign p_shl181_fu_2527_p1 = $signed(tmp_17_fu_2520_p3);

assign p_shl183_fu_2538_p1 = $signed(tmp_18_fu_2531_p3);

assign p_shl184_fu_2493_p1 = $signed(tmp_15_fu_2486_p3);

assign p_shl186_fu_2510_p1 = $signed(tmp_16_fu_2503_p3);

assign p_shl187_fu_1402_p1 = $signed(tmp_13_fu_1394_p3);

assign p_shl188_fu_1414_p1 = $signed(tmp_14_fu_1406_p3);

assign p_shl189_fu_1366_p1 = $signed(tmp_11_fu_1358_p3);

assign p_shl191_fu_1378_p1 = $signed(tmp_12_fu_1370_p3);

assign p_shl192_fu_2454_p1 = $signed(tmp_9_fu_2447_p3);

assign p_shl193_fu_2465_p1 = $signed(tmp_10_fu_2458_p3);

assign p_shl194_fu_2420_p1 = $signed(tmp_7_fu_2413_p3);

assign p_shl196_fu_2437_p1 = $signed(tmp_8_fu_2430_p3);

assign p_shl197_fu_2388_p1 = $signed(tmp_5_fu_2381_p3);

assign p_shl198_fu_2399_p1 = $signed(tmp_6_fu_2392_p3);

assign p_shl199_fu_2356_p1 = $signed(tmp_3_fu_2349_p3);

assign p_shl200_fu_2367_p1 = $signed(tmp_4_fu_2360_p3);

assign p_shl201_fu_2328_p1 = $signed(tmp_1_fu_2321_p3);

assign p_shl202_fu_2339_p1 = $signed(tmp_2_fu_2332_p3);

assign p_shl_fu_2587_p1 = $signed(tmp_21_fu_2580_p3);

assign sext_ln66_fu_406_p0 = x_n;

assign sext_ln71_100_fu_1030_p0 = p_ZL19H_filter_FIR_kernel_27;

assign sext_ln71_100_fu_1030_p1 = sext_ln71_100_fu_1030_p0;

assign sext_ln71_101_fu_1038_p0 = p_ZL19H_filter_FIR_kernel_26;

assign sext_ln71_104_fu_1054_p0 = p_ZL19H_filter_FIR_kernel_23;

assign sext_ln71_105_fu_1062_p0 = p_ZL19H_filter_FIR_kernel_22;

assign sext_ln71_105_fu_1062_p1 = sext_ln71_105_fu_1062_p0;

assign sext_ln71_106_fu_1074_p0 = p_ZL19H_filter_FIR_kernel_20;

assign sext_ln71_108_fu_1086_p0 = p_ZL19H_filter_FIR_kernel_18;

assign sext_ln71_10_fu_446_p0 = p_ZL19H_filter_FIR_kernel_118;

assign sext_ln71_10_fu_446_p1 = sext_ln71_10_fu_446_p0;

assign sext_ln71_110_fu_1098_p0 = p_ZL19H_filter_FIR_kernel_16;

assign sext_ln71_111_fu_1106_p0 = p_ZL19H_filter_FIR_kernel_15;

assign sext_ln71_111_fu_1106_p1 = sext_ln71_111_fu_1106_p0;

assign sext_ln71_113_fu_1118_p0 = p_ZL19H_filter_FIR_kernel_13;

assign sext_ln71_113_fu_1118_p1 = sext_ln71_113_fu_1118_p0;

assign sext_ln71_114_fu_1126_p0 = p_ZL19H_filter_FIR_kernel_12;

assign sext_ln71_114_fu_1126_p1 = sext_ln71_114_fu_1126_p0;

assign sext_ln71_115_fu_1134_p0 = p_ZL19H_filter_FIR_kernel_11;

assign sext_ln71_115_fu_1134_p1 = sext_ln71_115_fu_1134_p0;

assign sext_ln71_116_fu_1142_p0 = p_ZL19H_filter_FIR_kernel_10;

assign sext_ln71_117_fu_1150_p0 = p_ZL19H_filter_FIR_kernel_9;

assign sext_ln71_117_fu_1150_p1 = sext_ln71_117_fu_1150_p0;

assign sext_ln71_118_fu_1158_p0 = p_ZL19H_filter_FIR_kernel_8;

assign sext_ln71_118_fu_1158_p1 = sext_ln71_118_fu_1158_p0;

assign sext_ln71_119_fu_1166_p0 = p_ZL19H_filter_FIR_kernel_7;

assign sext_ln71_119_fu_1166_p1 = sext_ln71_119_fu_1166_p0;

assign sext_ln71_11_fu_454_p0 = p_ZL19H_filter_FIR_kernel_117;

assign sext_ln71_11_fu_454_p1 = sext_ln71_11_fu_454_p0;

assign sext_ln71_120_fu_1174_p0 = p_ZL19H_filter_FIR_kernel_6;

assign sext_ln71_120_fu_1174_p1 = sext_ln71_120_fu_1174_p0;

assign sext_ln71_121_fu_1182_p0 = p_ZL19H_filter_FIR_kernel_5;

assign sext_ln71_121_fu_1182_p1 = sext_ln71_121_fu_1182_p0;

assign sext_ln71_122_fu_1190_p0 = p_ZL19H_filter_FIR_kernel_4;

assign sext_ln71_122_fu_1190_p1 = sext_ln71_122_fu_1190_p0;

assign sext_ln71_123_fu_1198_p0 = p_ZL19H_filter_FIR_kernel_3;

assign sext_ln71_123_fu_1198_p1 = sext_ln71_123_fu_1198_p0;

assign sext_ln71_124_fu_1206_p0 = p_ZL19H_filter_FIR_kernel_2;

assign sext_ln71_125_fu_1214_p0 = p_ZL19H_filter_FIR_kernel_1;

assign sext_ln71_125_fu_1214_p1 = sext_ln71_125_fu_1214_p0;

assign sext_ln71_127_fu_2657_p1 = add_ln71_3_reg_3755;

assign sext_ln71_128_fu_2660_p1 = grp_fu_3153_p4;

assign sext_ln71_129_fu_2783_p1 = $signed(add_ln71_5_reg_3800);

assign sext_ln71_12_fu_462_p0 = p_ZL19H_filter_FIR_kernel_116;

assign sext_ln71_12_fu_462_p1 = sext_ln71_12_fu_462_p0;

assign sext_ln71_130_fu_2669_p1 = grp_fu_3164_p4;

assign sext_ln71_131_fu_2672_p1 = add_ln71_10_reg_3765;

assign sext_ln71_132_fu_2680_p1 = $signed(add_ln71_11_fu_2675_p2);

assign sext_ln71_133_fu_2791_p1 = $signed(add_ln71_12_reg_3805);

assign sext_ln71_135_fu_2800_p1 = grp_fu_3328_p4;

assign sext_ln71_136_fu_2693_p1 = grp_fu_3197_p4;

assign sext_ln71_137_fu_2696_p1 = grp_fu_3208_p4;

assign sext_ln71_138_fu_2803_p1 = $signed(add_ln71_18_reg_3815);

assign sext_ln71_139_fu_2812_p1 = $signed(add_ln71_19_fu_2806_p2);

assign sext_ln71_13_fu_470_p0 = p_ZL19H_filter_FIR_kernel_115;

assign sext_ln71_13_fu_470_p1 = sext_ln71_13_fu_470_p0;

assign sext_ln71_140_fu_2705_p1 = grp_fu_3219_p4;

assign sext_ln71_141_fu_2708_p1 = grp_fu_3230_p4;

assign sext_ln71_142_fu_2717_p1 = $signed(add_ln71_22_fu_2711_p2);

assign sext_ln71_143_fu_2721_p1 = grp_fu_3241_p4;

assign sext_ln71_144_fu_2724_p1 = grp_fu_3252_p4;

assign sext_ln71_145_fu_2733_p1 = $signed(add_ln71_25_fu_2727_p2);

assign sext_ln71_146_fu_2816_p1 = $signed(add_ln71_26_reg_3820);

assign sext_ln71_147_fu_2825_p1 = $signed(add_ln71_27_fu_2819_p2);

assign sext_ln71_149_fu_2835_p1 = grp_fu_3339_p4;

assign sext_ln71_14_fu_478_p0 = p_ZL19H_filter_FIR_kernel_114;

assign sext_ln71_14_fu_478_p1 = sext_ln71_14_fu_478_p0;

assign sext_ln71_150_fu_2746_p1 = add_ln71_31_reg_3770;

assign sext_ln71_151_fu_2749_p1 = grp_fu_3274_p4;

assign sext_ln71_152_fu_2838_p1 = $signed(add_ln71_33_reg_3830);

assign sext_ln71_154_fu_2758_p1 = grp_fu_3285_p4;

assign sext_ln71_155_fu_2761_p1 = add_ln71_37_reg_3780;

assign sext_ln71_156_fu_2764_p1 = grp_fu_3296_p4;

assign sext_ln71_157_fu_2860_p1 = grp_fu_3350_p4;

assign sext_ln71_158_fu_2611_p1 = $signed(add_ln71_44_reg_3625_pp0_iter2_reg);

assign sext_ln71_159_fu_2614_p1 = grp_fu_3110_p4;

assign sext_ln71_15_fu_486_p0 = p_ZL19H_filter_FIR_kernel_113;

assign sext_ln71_160_fu_2863_p1 = $signed(add_ln71_46_reg_3785_pp0_iter4_reg);

assign sext_ln71_161_fu_2872_p1 = $signed(add_ln71_47_fu_2866_p2);

assign sext_ln71_162_fu_2623_p1 = grp_fu_2923_p4;

assign sext_ln71_163_fu_2626_p1 = grp_fu_2934_p4;

assign sext_ln71_164_fu_2635_p1 = $signed(add_ln71_50_fu_2629_p2);

assign sext_ln71_165_fu_2639_p1 = grp_fu_3121_p4;

assign sext_ln71_166_fu_2647_p1 = $signed(add_ln71_53_fu_2642_p2);

assign sext_ln71_167_fu_2876_p1 = $signed(add_ln71_54_reg_3790_pp0_iter4_reg);

assign sext_ln71_168_fu_2773_p1 = $signed(add_ln71_39_fu_2767_p2);

assign sext_ln71_169_fu_2847_p1 = $signed(add_ln71_40_reg_3835);

assign sext_ln71_16_fu_494_p0 = p_ZL19H_filter_FIR_kernel_112;

assign sext_ln71_16_fu_494_p1 = sext_ln71_16_fu_494_p0;

assign sext_ln71_170_fu_2856_p1 = $signed(add_ln71_41_fu_2850_p2);

assign sext_ln71_171_fu_2885_p1 = $signed(add_ln71_55_fu_2879_p2);

assign sext_ln71_172_fu_2895_p1 = $signed(add_ln71_56_fu_2889_p2);

assign sext_ln71_17_fu_502_p0 = p_ZL19H_filter_FIR_kernel_111;

assign sext_ln71_17_fu_502_p1 = sext_ln71_17_fu_502_p0;

assign sext_ln71_18_fu_510_p0 = p_ZL19H_filter_FIR_kernel_110;

assign sext_ln71_18_fu_510_p1 = sext_ln71_18_fu_510_p0;

assign sext_ln71_20_fu_522_p0 = p_ZL19H_filter_FIR_kernel_108;

assign sext_ln71_20_fu_522_p1 = sext_ln71_20_fu_522_p0;

assign sext_ln71_21_fu_530_p0 = p_ZL19H_filter_FIR_kernel_107;

assign sext_ln71_23_fu_542_p0 = p_ZL19H_filter_FIR_kernel_105;

assign sext_ln71_25_fu_554_p0 = p_ZL19H_filter_FIR_kernel_103;

assign sext_ln71_26_fu_566_p0 = p_ZL19H_filter_FIR_kernel_101;

assign sext_ln71_26_fu_566_p1 = sext_ln71_26_fu_566_p0;

assign sext_ln71_27_fu_574_p0 = p_ZL19H_filter_FIR_kernel_100;

assign sext_ln71_30_fu_590_p0 = p_ZL19H_filter_FIR_kernel_97;

assign sext_ln71_31_fu_598_p0 = p_ZL19H_filter_FIR_kernel_96;

assign sext_ln71_31_fu_598_p1 = sext_ln71_31_fu_598_p0;

assign sext_ln71_32_fu_606_p0 = p_ZL19H_filter_FIR_kernel_95;

assign sext_ln71_34_fu_618_p0 = p_ZL19H_filter_FIR_kernel_93;

assign sext_ln71_34_fu_618_p1 = sext_ln71_34_fu_618_p0;

assign sext_ln71_37_fu_634_p0 = p_ZL19H_filter_FIR_kernel_90;

assign sext_ln71_39_fu_646_p0 = p_ZL19H_filter_FIR_kernel_88;

assign sext_ln71_41_fu_658_p0 = p_ZL19H_filter_FIR_kernel_86;

assign sext_ln71_42_fu_666_p0 = p_ZL19H_filter_FIR_kernel_85;

assign sext_ln71_42_fu_666_p1 = sext_ln71_42_fu_666_p0;

assign sext_ln71_44_fu_678_p0 = p_ZL19H_filter_FIR_kernel_83;

assign sext_ln71_45_fu_686_p0 = p_ZL19H_filter_FIR_kernel_82;

assign sext_ln71_47_fu_698_p0 = p_ZL19H_filter_FIR_kernel_80;

assign sext_ln71_49_fu_710_p0 = p_ZL19H_filter_FIR_kernel_78;

assign sext_ln71_52_fu_726_p0 = p_ZL19H_filter_FIR_kernel_75;

assign sext_ln71_52_fu_726_p1 = sext_ln71_52_fu_726_p0;

assign sext_ln71_53_fu_734_p0 = p_ZL19H_filter_FIR_kernel_74;

assign sext_ln71_55_fu_746_p0 = p_ZL19H_filter_FIR_kernel_72;

assign sext_ln71_56_fu_754_p0 = p_ZL19H_filter_FIR_kernel_71;

assign sext_ln71_56_fu_754_p1 = sext_ln71_56_fu_754_p0;

assign sext_ln71_57_fu_762_p0 = p_ZL19H_filter_FIR_kernel_70;

assign sext_ln71_59_fu_774_p0 = p_ZL19H_filter_FIR_kernel_68;

assign sext_ln71_61_fu_786_p0 = p_ZL19H_filter_FIR_kernel_66;

assign sext_ln71_61_fu_786_p1 = sext_ln71_61_fu_786_p0;

assign sext_ln71_62_fu_794_p0 = p_ZL19H_filter_FIR_kernel_65;

assign sext_ln71_65_fu_810_p0 = p_ZL19H_filter_FIR_kernel_62;

assign sext_ln71_66_fu_818_p0 = p_ZL19H_filter_FIR_kernel_61;

assign sext_ln71_69_fu_834_p0 = p_ZL19H_filter_FIR_kernel_58;

assign sext_ln71_70_fu_842_p0 = p_ZL19H_filter_FIR_kernel_57;

assign sext_ln71_70_fu_842_p1 = sext_ln71_70_fu_842_p0;

assign sext_ln71_72_fu_854_p0 = p_ZL19H_filter_FIR_kernel_55;

assign sext_ln71_74_fu_866_p0 = p_ZL19H_filter_FIR_kernel_53;

assign sext_ln71_75_fu_874_p0 = p_ZL19H_filter_FIR_kernel_52;

assign sext_ln71_75_fu_874_p1 = sext_ln71_75_fu_874_p0;

assign sext_ln71_76_fu_882_p0 = p_ZL19H_filter_FIR_kernel_51;

assign sext_ln71_78_fu_894_p0 = p_ZL19H_filter_FIR_kernel_49;

assign sext_ln71_79_fu_902_p0 = p_ZL19H_filter_FIR_kernel_48;

assign sext_ln71_79_fu_902_p1 = sext_ln71_79_fu_902_p0;

assign sext_ln71_7_fu_422_p0 = p_ZL19H_filter_FIR_kernel_121;

assign sext_ln71_82_fu_918_p0 = p_ZL19H_filter_FIR_kernel_45;

assign sext_ln71_84_fu_930_p0 = p_ZL19H_filter_FIR_kernel_43;

assign sext_ln71_86_fu_942_p0 = p_ZL19H_filter_FIR_kernel_41;

assign sext_ln71_87_fu_950_p0 = p_ZL19H_filter_FIR_kernel_40;

assign sext_ln71_89_fu_962_p0 = p_ZL19H_filter_FIR_kernel_38;

assign sext_ln71_89_fu_962_p1 = sext_ln71_89_fu_962_p0;

assign sext_ln71_8_fu_430_p0 = p_ZL19H_filter_FIR_kernel_120;

assign sext_ln71_8_fu_430_p1 = sext_ln71_8_fu_430_p0;

assign sext_ln71_90_fu_970_p0 = p_ZL19H_filter_FIR_kernel_37;

assign sext_ln71_92_fu_982_p0 = p_ZL19H_filter_FIR_kernel_35;

assign sext_ln71_94_fu_994_p0 = p_ZL19H_filter_FIR_kernel_33;

assign sext_ln71_97_fu_1010_p0 = p_ZL19H_filter_FIR_kernel_30;

assign sext_ln71_97_fu_1010_p1 = sext_ln71_97_fu_1010_p0;

assign sext_ln71_99_fu_1022_p0 = p_ZL19H_filter_FIR_kernel_28;

assign sext_ln71_9_fu_438_p0 = p_ZL19H_filter_FIR_kernel_119;

assign sext_ln71_9_fu_438_p1 = sext_ln71_9_fu_438_p0;

assign sext_ln71_fu_414_p0 = p_ZL19H_filter_FIR_kernel_122;

assign sext_ln71_fu_414_p1 = sext_ln71_fu_414_p0;

assign tmp107_fu_1352_p2 = ($signed(sext_ln71_114_fu_1126_p1) + $signed(sext_ln71_17_fu_502_p1));

assign tmp108_fu_1382_p2 = ($signed(p_shl191_fu_1378_p1) - $signed(p_shl189_fu_1366_p1));

assign tmp109_fu_1388_p2 = ($signed(sext_ln71_115_fu_1134_p1) + $signed(sext_ln71_16_fu_494_p1));

assign tmp110_fu_1418_p2 = ($signed(p_shl187_fu_1402_p1) + $signed(p_shl188_fu_1414_p1));

assign tmp113_fu_1424_p2 = ($signed(sext_ln71_118_fu_1158_p1) + $signed(sext_ln71_13_fu_470_p1));

assign tmp115_fu_1430_p2 = ($signed(sext_ln71_122_fu_1190_p1) + $signed(sext_ln71_9_fu_438_p1));

assign tmp116_fu_2542_p2 = ($signed(p_shl183_fu_2538_p1) - $signed(p_shl181_fu_2527_p1));

assign tmp117_fu_1436_p2 = ($signed(sext_ln71_123_fu_1198_p1) + $signed(sext_ln71_8_fu_430_p1));

assign tmp121_fu_1442_p2 = ($signed(sext_ln71_125_fu_1214_p1) + $signed(sext_ln71_fu_414_p1));

assign tmp125_fu_1268_p2 = ($signed(sext_ln71_20_fu_522_p1) + $signed(sext_ln71_11_fu_454_p1));

assign tmp126_fu_1278_p2 = ($signed(sext_ln71_111_fu_1106_p1) + $signed(sext_ln71_120_fu_1174_p1));

assign tmp127_fu_1288_p2 = ($signed(sext_ln71_14_fu_478_p1) + $signed(sext_ln71_10_fu_446_p1));

assign tmp128_fu_1298_p2 = ($signed(sext_ln71_117_fu_1150_p1) + $signed(sext_ln71_121_fu_1182_p1));

assign tmp25_fu_1308_p2 = ($signed(sext_ln71_70_fu_842_p1) + $signed(sext_ln71_61_fu_786_p1));

assign tmp35_fu_1314_p2 = ($signed(sext_ln71_75_fu_874_p1) + $signed(sext_ln71_56_fu_754_p1));

assign tmp36_fu_2371_p2 = ($signed(p_shl199_fu_2356_p1) + $signed(p_shl200_fu_2367_p1));

assign tmp43_fu_1320_p2 = ($signed(sext_ln71_79_fu_902_p1) + $signed(sext_ln71_52_fu_726_p1));

assign tmp44_fu_2403_p2 = ($signed(p_shl197_fu_2388_p1) - $signed(p_shl198_fu_2399_p1));

assign tmp4_fu_1226_p2 = ($signed(sext_ln71_42_fu_666_p1) + $signed(sext_ln71_34_fu_618_p1));

assign tmp5_cast_fu_1252_p1 = $signed(tmp5_fu_1246_p2);

assign tmp5_fu_1246_p2 = ($signed(sext_ln71_12_fu_462_p1) - $signed(sext_ln71_18_fu_510_p1));

assign tmp6_fu_1256_p2 = ($signed(tmp5_cast_fu_1252_p1) - $signed(sext_ln71_113_fu_1118_p1));

assign tmp7_fu_1262_p2 = ($signed(tmp6_fu_1256_p2) + $signed(sext_ln71_119_fu_1166_p1));

assign tmp81_fu_1326_p2 = ($signed(sext_ln71_100_fu_1030_p1) + $signed(sext_ln71_31_fu_598_p1));

assign tmp8_fu_2315_p1 = 25'd70;

assign tmp91_fu_1332_p2 = ($signed(sext_ln71_105_fu_1062_p1) + $signed(sext_ln71_26_fu_566_p1));

assign tmp931_fu_1346_p2 = ($signed(p_ZL19H_filter_FIR_kernel_21_load_cast_fu_1342_p1) + $signed(p_ZL19H_filter_FIR_kernel_102_load_cast_fu_1338_p1));

assign tmp93_fu_1236_p2 = ($signed(sext_ln71_89_fu_962_p1) + $signed(sext_ln71_97_fu_1010_p1));

assign tmp_10_fu_2458_p3 = {{tmp91_reg_3590_pp0_iter1_reg}, {4'd0}};

assign tmp_11_fu_1358_p3 = {{tmp107_fu_1352_p2}, {7'd0}};

assign tmp_12_fu_1370_p3 = {{tmp107_fu_1352_p2}, {2'd0}};

assign tmp_13_fu_1394_p3 = {{tmp109_fu_1388_p2}, {6'd0}};

assign tmp_14_fu_1406_p3 = {{tmp109_fu_1388_p2}, {3'd0}};

assign tmp_15_fu_2486_p3 = {{tmp113_reg_3601_pp0_iter1_reg}, {6'd0}};

assign tmp_16_fu_2503_p3 = {{tmp113_reg_3601_pp0_iter1_reg}, {4'd0}};

assign tmp_17_fu_2520_p3 = {{tmp115_reg_3607_pp0_iter1_reg}, {6'd0}};

assign tmp_18_fu_2531_p3 = {{tmp115_reg_3607_pp0_iter1_reg}, {1'd0}};

assign tmp_19_fu_2552_p3 = {{tmp117_reg_3613_pp0_iter1_reg}, {6'd0}};

assign tmp_1_fu_2321_p3 = {{tmp25_reg_3566_pp0_iter1_reg}, {12'd0}};

assign tmp_20_fu_2563_p3 = {{tmp117_reg_3613_pp0_iter1_reg}, {2'd0}};

assign tmp_21_fu_2580_p3 = {{tmp121_reg_3619_pp0_iter1_reg}, {8'd0}};

assign tmp_22_fu_2591_p3 = {{tmp121_reg_3619_pp0_iter1_reg}, {6'd0}};

assign tmp_2_fu_2332_p3 = {{tmp25_reg_3566_pp0_iter1_reg}, {7'd0}};

assign tmp_3_fu_2349_p3 = {{tmp35_reg_3572_pp0_iter1_reg}, {9'd0}};

assign tmp_4_fu_2360_p3 = {{tmp35_reg_3572_pp0_iter1_reg}, {1'd0}};

assign tmp_5_fu_2381_p3 = {{tmp43_reg_3578_pp0_iter1_reg}, {5'd0}};

assign tmp_6_fu_2392_p3 = {{tmp43_reg_3578_pp0_iter1_reg}, {3'd0}};

assign tmp_7_fu_2413_p3 = {{tmp81_reg_3584_pp0_iter1_reg}, {7'd0}};

assign tmp_8_fu_2430_p3 = {{tmp81_reg_3584_pp0_iter1_reg}, {3'd0}};

assign tmp_9_fu_2447_p3 = {{tmp91_reg_3590_pp0_iter1_reg}, {8'd0}};

assign tmp_fu_2475_p3 = {{tmp931_reg_3596_pp0_iter1_reg}, {2'd0}};

always @ (posedge ap_clk) begin
    add_ln71_44_reg_3625[1:0] <= 2'b00;
    add_ln71_44_reg_3625_pp0_iter1_reg[1:0] <= 2'b00;
    add_ln71_44_reg_3625_pp0_iter2_reg[1:0] <= 2'b00;
end

endmodule //FIR_Halfband_v1_FIR_filter
