-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Multirate_v2_FIR_filter is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    FIR_delays_read : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_read_22 : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_read_23 : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_delays_read_24 : IN STD_LOGIC_VECTOR (15 downto 0);
    FIR_coe_read : IN STD_LOGIC_VECTOR (9 downto 0);
    FIR_coe_read_9 : IN STD_LOGIC_VECTOR (12 downto 0);
    FIR_coe_read_10 : IN STD_LOGIC_VECTOR (13 downto 0);
    FIR_coe_read_11 : IN STD_LOGIC_VECTOR (12 downto 0);
    FIR_coe_read_12 : IN STD_LOGIC_VECTOR (9 downto 0);
    FIR_delays_write : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of Multirate_v2_FIR_filter is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";

attribute shreg_extract : string;
    signal FIR_delays_write_read_reg_226 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal FIR_delays_write_read_reg_226_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_write_read_reg_226_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_write_read_reg_226_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_coe_read_2_reg_232 : STD_LOGIC_VECTOR (12 downto 0);
    signal FIR_coe_read_2_reg_232_pp0_iter1_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal FIR_coe_read_3_reg_237 : STD_LOGIC_VECTOR (13 downto 0);
    signal FIR_coe_read_4_reg_242 : STD_LOGIC_VECTOR (12 downto 0);
    signal FIR_coe_read_4_reg_242_pp0_iter1_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal FIR_coe_read_4_reg_242_pp0_iter2_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal FIR_coe_read11_reg_247 : STD_LOGIC_VECTOR (9 downto 0);
    signal FIR_delays_read_15_reg_252 : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_15_reg_252_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_15_reg_252_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_15_reg_252_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_16_reg_258 : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_16_reg_258_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_16_reg_258_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_16_reg_258_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_17_reg_264 : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_17_reg_264_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_17_reg_264_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_17_reg_264_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln68_3_fu_130_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal mul_ln68_1_fu_142_p2 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal grp_fu_199_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_208_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal grp_fu_217_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp4_cast_fu_151_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp3_fu_154_p2 : STD_LOGIC_VECTOR (29 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of tmp3_fu_154_p2 : signal is "no";
    signal y_fu_159_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln70_fu_169_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_217_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_199_ce : STD_LOGIC;
    signal grp_fu_208_ce : STD_LOGIC;
    signal grp_fu_217_ce : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;
    signal FIR_delays_read_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_22_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_23_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_delays_read_24_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal FIR_coe_read_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal FIR_coe_read_9_int_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal FIR_coe_read_10_int_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal FIR_coe_read_11_int_reg : STD_LOGIC_VECTOR (12 downto 0);
    signal FIR_coe_read_12_int_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal FIR_delays_write_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_3_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_return_4_int_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_217_p10 : STD_LOGIC_VECTOR (29 downto 0);

    component Multirate_v2_mul_16s_13s_28_1_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component Multirate_v2_mac_muladd_16s_10s_28s_28_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        din2 : IN STD_LOGIC_VECTOR (27 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component Multirate_v2_mac_muladd_16s_14ns_28s_30_4_0 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (13 downto 0);
        din2 : IN STD_LOGIC_VECTOR (27 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (29 downto 0) );
    end component;



begin
    mul_16s_13s_28_1_0_U1 : component Multirate_v2_mul_16s_13s_28_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 28)
    port map (
        din0 => FIR_delays_read_17_reg_264_pp0_iter1_reg,
        din1 => FIR_coe_read_2_reg_232_pp0_iter1_reg,
        dout => mul_ln68_3_fu_130_p2);

    mul_16s_13s_28_1_0_U2 : component Multirate_v2_mul_16s_13s_28_1_0
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 13,
        dout_WIDTH => 28)
    port map (
        din0 => FIR_delays_read_15_reg_252_pp0_iter2_reg,
        din1 => FIR_coe_read_4_reg_242_pp0_iter2_reg,
        dout => mul_ln68_1_fu_142_p2);

    mac_muladd_16s_10s_28s_28_4_0_U3 : component Multirate_v2_mac_muladd_16s_10s_28s_28_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        din2_WIDTH => 28,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => FIR_delays_read_int_reg,
        din1 => FIR_coe_read_12_int_reg,
        din2 => mul_ln68_3_fu_130_p2,
        ce => grp_fu_199_ce,
        dout => grp_fu_199_p3);

    mac_muladd_16s_10s_28s_28_4_0_U4 : component Multirate_v2_mac_muladd_16s_10s_28s_28_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        din2_WIDTH => 28,
        dout_WIDTH => 28)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => FIR_delays_write_read_reg_226,
        din1 => FIR_coe_read11_reg_247,
        din2 => mul_ln68_1_fu_142_p2,
        ce => grp_fu_208_ce,
        dout => grp_fu_208_p3);

    mac_muladd_16s_14ns_28s_30_4_0_U5 : component Multirate_v2_mac_muladd_16s_14ns_28s_30_4_0
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 14,
        din2_WIDTH => 28,
        dout_WIDTH => 30)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => FIR_delays_read_16_reg_258,
        din1 => grp_fu_217_p1,
        din2 => grp_fu_199_p3,
        ce => grp_fu_217_ce,
        dout => grp_fu_217_p3);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                FIR_coe_read11_reg_247 <= FIR_coe_read_int_reg;
                FIR_coe_read_2_reg_232 <= FIR_coe_read_11_int_reg;
                FIR_coe_read_2_reg_232_pp0_iter1_reg <= FIR_coe_read_2_reg_232;
                FIR_coe_read_3_reg_237 <= FIR_coe_read_10_int_reg;
                FIR_coe_read_4_reg_242 <= FIR_coe_read_9_int_reg;
                FIR_coe_read_4_reg_242_pp0_iter1_reg <= FIR_coe_read_4_reg_242;
                FIR_coe_read_4_reg_242_pp0_iter2_reg <= FIR_coe_read_4_reg_242_pp0_iter1_reg;
                FIR_delays_read_15_reg_252 <= FIR_delays_read_24_int_reg;
                FIR_delays_read_15_reg_252_pp0_iter1_reg <= FIR_delays_read_15_reg_252;
                FIR_delays_read_15_reg_252_pp0_iter2_reg <= FIR_delays_read_15_reg_252_pp0_iter1_reg;
                FIR_delays_read_15_reg_252_pp0_iter3_reg <= FIR_delays_read_15_reg_252_pp0_iter2_reg;
                FIR_delays_read_16_reg_258 <= FIR_delays_read_23_int_reg;
                FIR_delays_read_16_reg_258_pp0_iter1_reg <= FIR_delays_read_16_reg_258;
                FIR_delays_read_16_reg_258_pp0_iter2_reg <= FIR_delays_read_16_reg_258_pp0_iter1_reg;
                FIR_delays_read_16_reg_258_pp0_iter3_reg <= FIR_delays_read_16_reg_258_pp0_iter2_reg;
                FIR_delays_read_17_reg_264 <= FIR_delays_read_22_int_reg;
                FIR_delays_read_17_reg_264_pp0_iter1_reg <= FIR_delays_read_17_reg_264;
                FIR_delays_read_17_reg_264_pp0_iter2_reg <= FIR_delays_read_17_reg_264_pp0_iter1_reg;
                FIR_delays_read_17_reg_264_pp0_iter3_reg <= FIR_delays_read_17_reg_264_pp0_iter2_reg;
                FIR_delays_write_read_reg_226 <= FIR_delays_write_int_reg;
                FIR_delays_write_read_reg_226_pp0_iter1_reg <= FIR_delays_write_read_reg_226;
                FIR_delays_write_read_reg_226_pp0_iter2_reg <= FIR_delays_write_read_reg_226_pp0_iter1_reg;
                FIR_delays_write_read_reg_226_pp0_iter3_reg <= FIR_delays_write_read_reg_226_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                FIR_coe_read_10_int_reg <= FIR_coe_read_10;
                FIR_coe_read_11_int_reg <= FIR_coe_read_11;
                FIR_coe_read_12_int_reg <= FIR_coe_read_12;
                FIR_coe_read_9_int_reg <= FIR_coe_read_9;
                FIR_coe_read_int_reg <= FIR_coe_read;
                FIR_delays_read_22_int_reg <= FIR_delays_read_22;
                FIR_delays_read_23_int_reg <= FIR_delays_read_23;
                FIR_delays_read_24_int_reg <= FIR_delays_read_24;
                FIR_delays_read_int_reg <= FIR_delays_read;
                FIR_delays_write_int_reg <= FIR_delays_write;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= sext_ln70_fu_169_p1;
                ap_return_1_int_reg <= FIR_delays_read_17_reg_264_pp0_iter3_reg;
                ap_return_2_int_reg <= FIR_delays_read_16_reg_258_pp0_iter3_reg;
                ap_return_3_int_reg <= FIR_delays_read_15_reg_252_pp0_iter3_reg;
                ap_return_4_int_reg <= FIR_delays_write_read_reg_226_pp0_iter3_reg;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(sext_ln70_fu_169_p1, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= sext_ln70_fu_169_p1;
        else 
            ap_return_0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_1_assign_proc : process(FIR_delays_read_17_reg_264_pp0_iter3_reg, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= FIR_delays_read_17_reg_264_pp0_iter3_reg;
        else 
            ap_return_1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_2_assign_proc : process(FIR_delays_read_16_reg_258_pp0_iter3_reg, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= FIR_delays_read_16_reg_258_pp0_iter3_reg;
        else 
            ap_return_2 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_3_assign_proc : process(FIR_delays_read_15_reg_252_pp0_iter3_reg, ap_ce_reg, ap_return_3_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_3 <= ap_return_3_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_3 <= FIR_delays_read_15_reg_252_pp0_iter3_reg;
        else 
            ap_return_3 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_return_4_assign_proc : process(FIR_delays_write_read_reg_226_pp0_iter3_reg, ap_ce_reg, ap_return_4_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_4 <= ap_return_4_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_4 <= FIR_delays_write_read_reg_226_pp0_iter3_reg;
        else 
            ap_return_4 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_199_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_199_ce <= ap_const_logic_1;
        else 
            grp_fu_199_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_208_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_208_ce <= ap_const_logic_1;
        else 
            grp_fu_208_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_217_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_fu_217_ce <= ap_const_logic_1;
        else 
            grp_fu_217_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_217_p1 <= grp_fu_217_p10(14 - 1 downto 0);
    grp_fu_217_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(FIR_coe_read_3_reg_237),30));
        sext_ln70_fu_169_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(y_fu_159_p4),16));

    tmp3_fu_154_p2 <= std_logic_vector(signed(grp_fu_217_p3) + signed(tmp4_cast_fu_151_p1));
        tmp4_cast_fu_151_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_208_p3),30));

    y_fu_159_p4 <= tmp3_fu_154_p2(29 downto 15);
end behav;
