// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module FIR_Cascade_v2_FIR_filter_2 (
        ap_clk,
        ap_rst,
        FIR_delays_read,
        FIR_delays_read_9,
        FIR_delays_read_10,
        FIR_delays_read_11,
        FIR_delays_read_12,
        FIR_delays_write,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] FIR_delays_read;
input  [15:0] FIR_delays_read_9;
input  [15:0] FIR_delays_read_10;
input  [15:0] FIR_delays_read_11;
input  [15:0] FIR_delays_read_12;
input  [15:0] FIR_delays_write;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;

reg  signed [15:0] FIR_delays_write_read_reg_161;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] FIR_delays_write_read_reg_161_pp0_iter1_reg;
reg  signed [15:0] FIR_delays_write_read_reg_161_pp0_iter2_reg;
reg  signed [15:0] FIR_delays_write_read_reg_161_pp0_iter3_reg;
reg  signed [15:0] FIR_delays_write_read_reg_161_pp0_iter4_reg;
reg  signed [15:0] FIR_delays_read_1_reg_167;
reg  signed [15:0] FIR_delays_read_1_reg_167_pp0_iter1_reg;
reg  signed [15:0] FIR_delays_read_1_reg_167_pp0_iter2_reg;
reg  signed [15:0] FIR_delays_read_1_reg_167_pp0_iter3_reg;
reg  signed [15:0] FIR_delays_read_1_reg_167_pp0_iter4_reg;
reg  signed [15:0] FIR_delays_read_2_reg_173;
reg  signed [15:0] FIR_delays_read_2_reg_173_pp0_iter1_reg;
reg  signed [15:0] FIR_delays_read_2_reg_173_pp0_iter2_reg;
reg  signed [15:0] FIR_delays_read_2_reg_173_pp0_iter3_reg;
reg  signed [15:0] FIR_delays_read_2_reg_173_pp0_iter4_reg;
reg  signed [15:0] FIR_delays_read_3_reg_178;
reg  signed [15:0] FIR_delays_read_3_reg_178_pp0_iter1_reg;
reg  signed [15:0] FIR_delays_read_3_reg_178_pp0_iter2_reg;
reg  signed [15:0] FIR_delays_read_3_reg_178_pp0_iter3_reg;
reg  signed [15:0] FIR_delays_read_3_reg_178_pp0_iter4_reg;
reg  signed [15:0] FIR_delays_read_4_reg_183;
reg  signed [15:0] FIR_delays_read_4_reg_183_pp0_iter1_reg;
reg  signed [15:0] FIR_delays_read_4_reg_183_pp0_iter2_reg;
reg  signed [15:0] FIR_delays_read_4_reg_183_pp0_iter3_reg;
reg  signed [15:0] FIR_delays_read_4_reg_183_pp0_iter4_reg;
reg  signed [15:0] FIR_delays_read11_reg_189;
wire  signed [31:0] grp_fu_132_p3;
wire  signed [31:0] grp_fu_140_p4;
wire  signed [15:0] sext_ln66_1_fu_72_p0;
wire    ap_block_pp0_stage0;
wire  signed [15:0] sext_ln66_2_fu_76_p0;
wire  signed [31:0] grp_fu_150_p4;
wire   [14:0] grp_fu_132_p2;
wire   [9:0] grp_fu_140_p2;
wire  signed [13:0] grp_fu_150_p2;
reg    grp_fu_132_ce;
reg    grp_fu_140_ce;
reg    grp_fu_150_ce;
reg    ap_ce_reg;
reg   [15:0] FIR_delays_read_int_reg;
reg   [15:0] FIR_delays_read_9_int_reg;
reg   [15:0] FIR_delays_read_10_int_reg;
reg   [15:0] FIR_delays_read_11_int_reg;
reg   [15:0] FIR_delays_read_12_int_reg;
reg   [15:0] FIR_delays_write_int_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
reg   [15:0] ap_return_4_int_reg;
reg   [15:0] ap_return_5_int_reg;

FIR_Cascade_v2_am_addmul_16s_16s_15ns_32_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 32 ))
am_addmul_16s_16s_15ns_32_4_0_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln66_2_fu_76_p0),
    .din1(sext_ln66_1_fu_72_p0),
    .din2(grp_fu_132_p2),
    .ce(grp_fu_132_ce),
    .dout(grp_fu_132_p3)
);

FIR_Cascade_v2_ama_addmuladd_16s_16s_10ns_32s_32_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
ama_addmuladd_16s_16s_10ns_32s_32_4_0_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FIR_delays_read11_reg_189),
    .din1(FIR_delays_write_read_reg_161),
    .din2(grp_fu_140_p2),
    .din3(grp_fu_132_p3),
    .ce(grp_fu_140_ce),
    .dout(grp_fu_140_p4)
);

FIR_Cascade_v2_ama_addmuladd_16s_16s_14s_32s_32_4_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 14 ),
    .din3_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
ama_addmuladd_16s_16s_14s_32s_32_4_0_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(FIR_delays_read_4_reg_183_pp0_iter1_reg),
    .din1(FIR_delays_read_1_reg_167_pp0_iter1_reg),
    .din2(grp_fu_150_p2),
    .din3(grp_fu_140_p4),
    .ce(grp_fu_150_ce),
    .dout(grp_fu_150_p4)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        FIR_delays_read11_reg_189 <= FIR_delays_read_int_reg;
        FIR_delays_read_1_reg_167 <= FIR_delays_read_12_int_reg;
        FIR_delays_read_1_reg_167_pp0_iter1_reg <= FIR_delays_read_1_reg_167;
        FIR_delays_read_1_reg_167_pp0_iter2_reg <= FIR_delays_read_1_reg_167_pp0_iter1_reg;
        FIR_delays_read_1_reg_167_pp0_iter3_reg <= FIR_delays_read_1_reg_167_pp0_iter2_reg;
        FIR_delays_read_1_reg_167_pp0_iter4_reg <= FIR_delays_read_1_reg_167_pp0_iter3_reg;
        FIR_delays_read_2_reg_173 <= FIR_delays_read_11_int_reg;
        FIR_delays_read_2_reg_173_pp0_iter1_reg <= FIR_delays_read_2_reg_173;
        FIR_delays_read_2_reg_173_pp0_iter2_reg <= FIR_delays_read_2_reg_173_pp0_iter1_reg;
        FIR_delays_read_2_reg_173_pp0_iter3_reg <= FIR_delays_read_2_reg_173_pp0_iter2_reg;
        FIR_delays_read_2_reg_173_pp0_iter4_reg <= FIR_delays_read_2_reg_173_pp0_iter3_reg;
        FIR_delays_read_3_reg_178 <= FIR_delays_read_10_int_reg;
        FIR_delays_read_3_reg_178_pp0_iter1_reg <= FIR_delays_read_3_reg_178;
        FIR_delays_read_3_reg_178_pp0_iter2_reg <= FIR_delays_read_3_reg_178_pp0_iter1_reg;
        FIR_delays_read_3_reg_178_pp0_iter3_reg <= FIR_delays_read_3_reg_178_pp0_iter2_reg;
        FIR_delays_read_3_reg_178_pp0_iter4_reg <= FIR_delays_read_3_reg_178_pp0_iter3_reg;
        FIR_delays_read_4_reg_183 <= FIR_delays_read_9_int_reg;
        FIR_delays_read_4_reg_183_pp0_iter1_reg <= FIR_delays_read_4_reg_183;
        FIR_delays_read_4_reg_183_pp0_iter2_reg <= FIR_delays_read_4_reg_183_pp0_iter1_reg;
        FIR_delays_read_4_reg_183_pp0_iter3_reg <= FIR_delays_read_4_reg_183_pp0_iter2_reg;
        FIR_delays_read_4_reg_183_pp0_iter4_reg <= FIR_delays_read_4_reg_183_pp0_iter3_reg;
        FIR_delays_write_read_reg_161 <= FIR_delays_write_int_reg;
        FIR_delays_write_read_reg_161_pp0_iter1_reg <= FIR_delays_write_read_reg_161;
        FIR_delays_write_read_reg_161_pp0_iter2_reg <= FIR_delays_write_read_reg_161_pp0_iter1_reg;
        FIR_delays_write_read_reg_161_pp0_iter3_reg <= FIR_delays_write_read_reg_161_pp0_iter2_reg;
        FIR_delays_write_read_reg_161_pp0_iter4_reg <= FIR_delays_write_read_reg_161_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        FIR_delays_read_10_int_reg <= FIR_delays_read_10;
        FIR_delays_read_11_int_reg <= FIR_delays_read_11;
        FIR_delays_read_12_int_reg <= FIR_delays_read_12;
        FIR_delays_read_9_int_reg <= FIR_delays_read_9;
        FIR_delays_read_int_reg <= FIR_delays_read;
        FIR_delays_write_int_reg <= FIR_delays_write;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= {{grp_fu_150_p4[31:16]}};
        ap_return_1_int_reg <= FIR_delays_read_4_reg_183_pp0_iter4_reg;
        ap_return_2_int_reg <= FIR_delays_read_3_reg_178_pp0_iter4_reg;
        ap_return_3_int_reg <= FIR_delays_read_2_reg_173_pp0_iter4_reg;
        ap_return_4_int_reg <= FIR_delays_read_1_reg_167_pp0_iter4_reg;
        ap_return_5_int_reg <= FIR_delays_write_read_reg_161_pp0_iter4_reg;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = {{grp_fu_150_p4[31:16]}};
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = FIR_delays_read_4_reg_183_pp0_iter4_reg;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = FIR_delays_read_3_reg_178_pp0_iter4_reg;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = FIR_delays_read_2_reg_173_pp0_iter4_reg;
    end else begin
        ap_return_3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = FIR_delays_read_1_reg_167_pp0_iter4_reg;
    end else begin
        ap_return_4 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_5 = ap_return_5_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_5 = FIR_delays_write_read_reg_161_pp0_iter4_reg;
    end else begin
        ap_return_5 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_132_ce = 1'b1;
    end else begin
        grp_fu_132_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_140_ce = 1'b1;
    end else begin
        grp_fu_140_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_150_ce = 1'b1;
    end else begin
        grp_fu_150_ce = 1'b0;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign grp_fu_132_p2 = 32'd19716;

assign grp_fu_140_p2 = 28'd714;

assign grp_fu_150_p2 = 31'd2147479508;

assign sext_ln66_1_fu_72_p0 = FIR_delays_read_11_int_reg;

assign sext_ln66_2_fu_76_p0 = FIR_delays_read_10_int_reg;

endmodule //FIR_Cascade_v2_FIR_filter_2
