set SynModuleInfo {
  {SRCNAME FIR_HLS_Pipeline_VITIS_LOOP_28_2 MODELNAME FIR_HLS_Pipeline_VITIS_LOOP_28_2 RTLNAME FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_28_2
    SUBMODULES {
      {MODELNAME FIR_HLS_mul_16s_14s_30_1_1 RTLNAME FIR_HLS_mul_16s_14s_30_1_1 BINDTYPE op TYPE mul IMPL auto LATENCY 0 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_28_2_b_FIR_ROM_AUTO_1R RTLNAME FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_28_2_b_FIR_ROM_AUTO_1R BINDTYPE storage TYPE rom IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_28_2_H_accu_FIR1_RAM_AUTO_1R1W RTLNAME FIR_HLS_FIR_HLS_Pipeline_VITIS_LOOP_28_2_H_accu_FIR1_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
    }
  }
  {SRCNAME FIR_HLS MODELNAME FIR_HLS RTLNAME FIR_HLS IS_TOP 1
    SUBMODULES {
      {MODELNAME FIR_HLS_regslice_both RTLNAME FIR_HLS_regslice_both BINDTYPE interface TYPE adapter IMPL reg_slice}
    }
  }
}
