-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Fast_Running_FIR_HLS is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    input_r_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    input_r_TVALID : IN STD_LOGIC;
    input_r_TREADY : OUT STD_LOGIC;
    output_r_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_r_TVALID : OUT STD_LOGIC;
    output_r_TREADY : IN STD_LOGIC );
end;


architecture behav of Fast_Running_FIR_HLS is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Fast_Running_FIR_HLS_Fast_Running_FIR_HLS,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.870000,HLS_SYN_LAT=200,HLS_SYN_TPT=none,HLS_SYN_MEM=9,HLS_SYN_DSP=0,HLS_SYN_FF=302,HLS_SYN_LUT=702,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv24_FFFF48 : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111101001000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv25_1FFFEEA : STD_LOGIC_VECTOR (24 downto 0) := "1111111111111111011101010";
    constant ap_const_lv23_5C : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000001011100";

    signal ap_rst_n_inv : STD_LOGIC;
    signal mod_value : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal input1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal H_filter_FIR_22_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal H_filter_FIR_22_ce0 : STD_LOGIC;
    signal H_filter_FIR_22_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_22_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal y2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal y11 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal input2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal H_filter_FIR_21_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal H_filter_FIR_21_ce0 : STD_LOGIC;
    signal H_filter_FIR_21_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_21_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_20_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal H_filter_FIR_20_ce0 : STD_LOGIC;
    signal H_filter_FIR_20_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal H_filter_FIR_20_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal output_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal mod_value_load_load_fu_149_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal mod_value_load_reg_305 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal x_n_fu_161_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_n_reg_314 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_n_2_reg_324 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln14_fu_217_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal H_filter_FIR_21_load_reg_334 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_n_1_fu_251_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_n_1_reg_339 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln22_fu_290_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_start : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_done : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_idle : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_ready : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_ce0 : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_we0 : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_ce1 : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_start : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_done : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_idle : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_ready : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_ce0 : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_we0 : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_ce1 : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_start : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_done : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_idle : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_ready : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_ce0 : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_we0 : STD_LOGIC;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_ce1 : STD_LOGIC;
    signal ap_phi_mux_storemerge_phi_fu_114_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal regslice_both_output_r_U_apdone_blk : STD_LOGIC;
    signal ap_block_state4_on_subcall_done : BOOLEAN;
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_start_reg : STD_LOGIC := '0';
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_start_reg : STD_LOGIC := '0';
    signal grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state2 : BOOLEAN;
    signal y_fu_197_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state5 : BOOLEAN;
    signal H_filter_FIR_22_ce0_local : STD_LOGIC;
    signal H_filter_FIR_21_ce0_local : STD_LOGIC;
    signal H_filter_FIR_20_ce0_local : STD_LOGIC;
    signal sext_ln35_1_fu_177_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln35_1_fu_181_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln35_1_fu_181_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln35_4_fu_187_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln35_1_fu_191_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_297_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln35_2_fu_260_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln35_2_fu_260_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal sext_ln35_5_fu_266_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln35_2_fu_270_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal y_2_fu_276_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_297_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_297_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal regslice_both_input_r_U_apdone_blk : STD_LOGIC;
    signal input_r_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal input_r_TVALID_int_regslice : STD_LOGIC;
    signal input_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_input_r_U_ack_in : STD_LOGIC;
    signal output_r_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal output_r_TVALID_int_regslice : STD_LOGIC;
    signal output_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_output_r_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Fast_Running_FIR_HLS_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln37_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        H_filter_FIR_22_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        H_filter_FIR_22_ce0 : OUT STD_LOGIC;
        H_filter_FIR_22_we0 : OUT STD_LOGIC;
        H_filter_FIR_22_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        H_filter_FIR_22_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        H_filter_FIR_22_ce1 : OUT STD_LOGIC;
        H_filter_FIR_22_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Fast_Running_FIR_HLS_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln37 : IN STD_LOGIC_VECTOR (15 downto 0);
        H_filter_FIR_21_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        H_filter_FIR_21_ce0 : OUT STD_LOGIC;
        H_filter_FIR_21_we0 : OUT STD_LOGIC;
        H_filter_FIR_21_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        H_filter_FIR_21_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        H_filter_FIR_21_ce1 : OUT STD_LOGIC;
        H_filter_FIR_21_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Fast_Running_FIR_HLS_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln37_2 : IN STD_LOGIC_VECTOR (15 downto 0);
        H_filter_FIR_20_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        H_filter_FIR_20_ce0 : OUT STD_LOGIC;
        H_filter_FIR_20_we0 : OUT STD_LOGIC;
        H_filter_FIR_20_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        H_filter_FIR_20_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        H_filter_FIR_20_ce1 : OUT STD_LOGIC;
        H_filter_FIR_20_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Fast_Running_FIR_HLS_mul_16s_9s_24_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component Fast_Running_FIR_HLS_mul_16s_10s_25_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component Fast_Running_FIR_HLS_mac_muladd_16s_7ns_32s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Fast_Running_FIR_HLS_H_filter_FIR_22_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component Fast_Running_FIR_HLS_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    H_filter_FIR_22_U : component Fast_Running_FIR_HLS_H_filter_FIR_22_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 196,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => H_filter_FIR_22_address0,
        ce0 => H_filter_FIR_22_ce0,
        we0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_we0,
        d0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_d0,
        q0 => H_filter_FIR_22_q0,
        address1 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_address1,
        ce1 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_ce1,
        q1 => H_filter_FIR_22_q1);

    H_filter_FIR_21_U : component Fast_Running_FIR_HLS_H_filter_FIR_22_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 196,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => H_filter_FIR_21_address0,
        ce0 => H_filter_FIR_21_ce0,
        we0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_we0,
        d0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_d0,
        q0 => H_filter_FIR_21_q0,
        address1 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_address1,
        ce1 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_ce1,
        q1 => H_filter_FIR_21_q1);

    H_filter_FIR_20_U : component Fast_Running_FIR_HLS_H_filter_FIR_22_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 196,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => H_filter_FIR_20_address0,
        ce0 => H_filter_FIR_20_ce0,
        we0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_we0,
        d0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_d0,
        q0 => H_filter_FIR_20_q0,
        address1 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_address1,
        ce1 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_ce1,
        q1 => H_filter_FIR_20_q1);

    grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122 : component Fast_Running_FIR_HLS_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_start,
        ap_done => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_done,
        ap_idle => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_idle,
        ap_ready => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_ready,
        sext_ln37_1 => x_n_2_reg_324,
        H_filter_FIR_22_address0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_address0,
        H_filter_FIR_22_ce0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_ce0,
        H_filter_FIR_22_we0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_we0,
        H_filter_FIR_22_d0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_d0,
        H_filter_FIR_22_address1 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_address1,
        H_filter_FIR_22_ce1 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_ce1,
        H_filter_FIR_22_q1 => H_filter_FIR_22_q1);

    grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131 : component Fast_Running_FIR_HLS_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_start,
        ap_done => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_done,
        ap_idle => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_idle,
        ap_ready => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_ready,
        sext_ln37 => x_n_reg_314,
        H_filter_FIR_21_address0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_address0,
        H_filter_FIR_21_ce0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_ce0,
        H_filter_FIR_21_we0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_we0,
        H_filter_FIR_21_d0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_d0,
        H_filter_FIR_21_address1 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_address1,
        H_filter_FIR_21_ce1 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_ce1,
        H_filter_FIR_21_q1 => H_filter_FIR_21_q1);

    grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140 : component Fast_Running_FIR_HLS_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_start,
        ap_done => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_done,
        ap_idle => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_idle,
        ap_ready => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_ready,
        sext_ln37_2 => x_n_1_reg_339,
        H_filter_FIR_20_address0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_address0,
        H_filter_FIR_20_ce0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_ce0,
        H_filter_FIR_20_we0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_we0,
        H_filter_FIR_20_d0 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_d0,
        H_filter_FIR_20_address1 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_address1,
        H_filter_FIR_20_ce1 => grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_ce1,
        H_filter_FIR_20_q1 => H_filter_FIR_20_q1);

    mul_16s_9s_24_1_1_U14 : component Fast_Running_FIR_HLS_mul_16s_9s_24_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 9,
        dout_WIDTH => 24)
    port map (
        din0 => sext_ln35_1_fu_177_p0,
        din1 => mul_ln35_1_fu_181_p1,
        dout => mul_ln35_1_fu_181_p2);

    mul_16s_10s_25_1_1_U15 : component Fast_Running_FIR_HLS_mul_16s_10s_25_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 25)
    port map (
        din0 => x_n_1_fu_251_p2,
        din1 => mul_ln35_2_fu_260_p1,
        dout => mul_ln35_2_fu_260_p2);

    mac_muladd_16s_7ns_32s_32_4_1_U16 : component Fast_Running_FIR_HLS_mac_muladd_16s_7ns_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 7,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => x_n_fu_161_p2,
        din1 => grp_fu_297_p1,
        din2 => H_filter_FIR_21_load_reg_334,
        ce => grp_fu_297_ce,
        dout => grp_fu_297_p3);

    regslice_both_input_r_U : component Fast_Running_FIR_HLS_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TDATA,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_U_ack_in,
        data_out => input_r_TDATA_int_regslice,
        vld_out => input_r_TVALID_int_regslice,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_U_apdone_blk);

    regslice_both_output_r_U : component Fast_Running_FIR_HLS_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => output_r_TDATA_int_regslice,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => output_r_TREADY_int_regslice,
        data_out => output_r_TDATA,
        vld_out => regslice_both_output_r_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_start_reg <= ap_const_logic_0;
            else
                if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                    grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_ready = ap_const_logic_1)) then 
                    grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_start_reg <= ap_const_logic_0;
            else
                if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                    grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_ready = ap_const_logic_1)) then 
                    grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_start_reg <= ap_const_logic_0;
            else
                if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_ready = ap_const_logic_1)) then 
                    grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                H_filter_FIR_21_load_reg_334 <= H_filter_FIR_21_q0;
                x_n_1_reg_339 <= x_n_1_fu_251_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                input1 <= input_r_TDATA_int_regslice;
                y2 <= add_ln35_1_fu_191_p2(31 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                input2 <= input_r_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state4_on_subcall_done) or (regslice_both_output_r_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                mod_value <= ap_phi_mux_storemerge_phi_fu_114_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                mod_value_load_reg_305 <= mod_value;
                x_n_reg_314 <= x_n_fu_161_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                x_n_2_reg_324 <= input_r_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state4_on_subcall_done) or (regslice_both_output_r_U_apdone_blk = ap_const_logic_1))) and (mod_value_load_reg_305 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                y11 <= grp_fu_297_p3(31 downto 16);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state3, ap_CS_fsm_state6, mod_value_load_load_fu_149_p1, ap_CS_fsm_state1, ap_CS_fsm_state4, regslice_both_output_r_U_apdone_blk, ap_block_state4_on_subcall_done, ap_block_state2, ap_block_state5, output_r_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((mod_value_load_load_fu_149_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if ((not(((ap_const_boolean_1 = ap_block_state4_on_subcall_done) or (regslice_both_output_r_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;

    H_filter_FIR_20_address0_assign_proc : process(mod_value_load_reg_305, grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_address0, ap_CS_fsm_state4)
    begin
        if (((mod_value_load_reg_305 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            H_filter_FIR_20_address0 <= grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_address0;
        else 
            H_filter_FIR_20_address0 <= ap_const_lv8_0;
        end if; 
    end process;


    H_filter_FIR_20_ce0_assign_proc : process(mod_value_load_reg_305, grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_ce0, ap_CS_fsm_state4, H_filter_FIR_20_ce0_local)
    begin
        if (((mod_value_load_reg_305 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            H_filter_FIR_20_ce0 <= grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_H_filter_FIR_20_ce0;
        else 
            H_filter_FIR_20_ce0 <= H_filter_FIR_20_ce0_local;
        end if; 
    end process;


    H_filter_FIR_20_ce0_local_assign_proc : process(ap_CS_fsm_state1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            H_filter_FIR_20_ce0_local <= ap_const_logic_1;
        else 
            H_filter_FIR_20_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_21_address0_assign_proc : process(mod_value_load_reg_305, grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_address0, ap_CS_fsm_state4)
    begin
        if (((mod_value_load_reg_305 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            H_filter_FIR_21_address0 <= grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_address0;
        else 
            H_filter_FIR_21_address0 <= ap_const_lv8_0;
        end if; 
    end process;


    H_filter_FIR_21_ce0_assign_proc : process(mod_value_load_reg_305, grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_ce0, ap_CS_fsm_state4, H_filter_FIR_21_ce0_local)
    begin
        if (((mod_value_load_reg_305 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            H_filter_FIR_21_ce0 <= grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_H_filter_FIR_21_ce0;
        else 
            H_filter_FIR_21_ce0 <= H_filter_FIR_21_ce0_local;
        end if; 
    end process;


    H_filter_FIR_21_ce0_local_assign_proc : process(ap_CS_fsm_state1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            H_filter_FIR_21_ce0_local <= ap_const_logic_1;
        else 
            H_filter_FIR_21_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    H_filter_FIR_22_address0_assign_proc : process(mod_value_load_reg_305, grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_address0, ap_CS_fsm_state4)
    begin
        if (((mod_value_load_reg_305 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            H_filter_FIR_22_address0 <= grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_address0;
        else 
            H_filter_FIR_22_address0 <= ap_const_lv8_0;
        end if; 
    end process;


    H_filter_FIR_22_ce0_assign_proc : process(mod_value_load_reg_305, grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_ce0, ap_CS_fsm_state4, H_filter_FIR_22_ce0_local)
    begin
        if (((mod_value_load_reg_305 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            H_filter_FIR_22_ce0 <= grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_H_filter_FIR_22_ce0;
        else 
            H_filter_FIR_22_ce0 <= H_filter_FIR_22_ce0_local;
        end if; 
    end process;


    H_filter_FIR_22_ce0_local_assign_proc : process(ap_CS_fsm_state1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            H_filter_FIR_22_ce0_local <= ap_const_logic_1;
        else 
            H_filter_FIR_22_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln35_1_fu_191_p2 <= std_logic_vector(signed(sext_ln35_4_fu_187_p1) + signed(H_filter_FIR_22_q0));
    add_ln35_2_fu_270_p2 <= std_logic_vector(signed(sext_ln35_5_fu_266_p1) + signed(H_filter_FIR_20_q0));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;

    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2)
    begin
        if ((ap_const_boolean_1 = ap_block_state2)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(output_r_TREADY_int_regslice)
    begin
        if ((output_r_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(regslice_both_output_r_U_apdone_blk, ap_block_state4_on_subcall_done)
    begin
        if (((ap_const_boolean_1 = ap_block_state4_on_subcall_done) or (regslice_both_output_r_U_apdone_blk = ap_const_logic_1))) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(ap_block_state5)
    begin
        if ((ap_const_boolean_1 = ap_block_state5)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(output_r_TREADY_int_regslice)
    begin
        if ((output_r_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state2_assign_proc : process(input_r_TVALID_int_regslice, output_r_TREADY_int_regslice)
    begin
                ap_block_state2 <= ((output_r_TREADY_int_regslice = ap_const_logic_0) or (input_r_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state4_on_subcall_done_assign_proc : process(mod_value_load_reg_305, grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_done, grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_done, grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_done)
    begin
                ap_block_state4_on_subcall_done <= (((mod_value_load_reg_305 = ap_const_lv1_1) and (grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_done = ap_const_logic_0)) or ((mod_value_load_reg_305 = ap_const_lv1_1) and (grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_done = ap_const_logic_0)) or ((mod_value_load_reg_305 = ap_const_lv1_0) and (grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_done = ap_const_logic_0)));
    end process;


    ap_block_state5_assign_proc : process(input_r_TVALID_int_regslice, output_r_TREADY_int_regslice)
    begin
                ap_block_state5 <= ((output_r_TREADY_int_regslice = ap_const_logic_0) or (input_r_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_phi_mux_storemerge_phi_fu_114_p4_assign_proc : process(mod_value_load_reg_305, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
            if ((mod_value_load_reg_305 = ap_const_lv1_0)) then 
                ap_phi_mux_storemerge_phi_fu_114_p4 <= ap_const_lv1_1;
            elsif ((mod_value_load_reg_305 = ap_const_lv1_1)) then 
                ap_phi_mux_storemerge_phi_fu_114_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_storemerge_phi_fu_114_p4 <= "X";
            end if;
        else 
            ap_phi_mux_storemerge_phi_fu_114_p4 <= "X";
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_start <= grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_11_fu_131_ap_start_reg;
    grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_start <= grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_12_fu_140_ap_start_reg;
    grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_start <= grp_Fast_Running_FIR_HLS_Pipeline_VITIS_LOOP_37_1_fu_122_ap_start_reg;

    grp_fu_297_ce_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state1, ap_CS_fsm_state4, regslice_both_output_r_U_apdone_blk, ap_block_state4_on_subcall_done, ap_block_state5, output_r_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) or ((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((ap_const_boolean_1 = ap_block_state4_on_subcall_done) or (regslice_both_output_r_U_apdone_blk = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            grp_fu_297_ce <= ap_const_logic_1;
        else 
            grp_fu_297_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_297_p1 <= ap_const_lv23_5C(7 - 1 downto 0);

    input_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5, input_r_TVALID_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            input_r_TDATA_blk_n <= input_r_TVALID_int_regslice;
        else 
            input_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    input_r_TREADY <= regslice_both_input_r_U_ack_in;

    input_r_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5, ap_block_state2, ap_block_state5)
    begin
        if ((((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            input_r_TREADY_int_regslice <= ap_const_logic_1;
        else 
            input_r_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    mod_value_load_load_fu_149_p1 <= mod_value;
    mul_ln35_1_fu_181_p1 <= ap_const_lv24_FFFF48(9 - 1 downto 0);
    mul_ln35_2_fu_260_p1 <= ap_const_lv25_1FFFEEA(10 - 1 downto 0);

    output_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state3, ap_CS_fsm_state6, output_r_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            output_r_TDATA_blk_n <= output_r_TREADY_int_regslice;
        else 
            output_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    output_r_TDATA_int_regslice_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5, sub_ln14_fu_217_p2, sub_ln22_fu_290_p2, ap_block_state2, ap_block_state5)
    begin
        if (((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            output_r_TDATA_int_regslice <= sub_ln22_fu_290_p2;
        elsif (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            output_r_TDATA_int_regslice <= sub_ln14_fu_217_p2;
        else 
            output_r_TDATA_int_regslice <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    output_r_TVALID <= regslice_both_output_r_U_vld_out;

    output_r_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state5, ap_block_state2, ap_block_state5)
    begin
        if ((((ap_const_boolean_0 = ap_block_state5) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            output_r_TVALID_int_regslice <= ap_const_logic_1;
        else 
            output_r_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    sext_ln35_1_fu_177_p0 <= input_r_TDATA_int_regslice;
        sext_ln35_4_fu_187_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln35_1_fu_181_p2),32));

        sext_ln35_5_fu_266_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln35_2_fu_260_p2),32));

    sub_ln14_fu_217_p2 <= std_logic_vector(unsigned(y_fu_197_p4) - unsigned(y11));
    sub_ln22_fu_290_p2 <= std_logic_vector(unsigned(y2) - unsigned(y_2_fu_276_p4));
    x_n_1_fu_251_p2 <= std_logic_vector(unsigned(input1) - unsigned(input_r_TDATA_int_regslice));
    x_n_fu_161_p2 <= std_logic_vector(unsigned(input1) - unsigned(input2));
    y_2_fu_276_p4 <= add_ln35_2_fu_270_p2(31 downto 16);
    y_fu_197_p4 <= add_ln35_1_fu_191_p2(31 downto 16);
end behav;
