-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FIR_Halfband_v2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    input_r_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    input_r_TVALID : IN STD_LOGIC;
    input_r_TREADY : OUT STD_LOGIC;
    output_r_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_r_TVALID : OUT STD_LOGIC;
    output_r_TREADY : IN STD_LOGIC );
end;


architecture behav of FIR_Halfband_v2 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "FIR_Halfband_v2_FIR_Halfband_v2,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.736000,HLS_SYN_LAT=6,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=6175,HLS_SYN_LUT=6304,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (14 downto 0) := "000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (14 downto 0) := "000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (14 downto 0) := "000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (14 downto 0) := "000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (14 downto 0) := "000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (14 downto 0) := "000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (14 downto 0) := "000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (14 downto 0) := "000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (14 downto 0) := "000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (14 downto 0) := "001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (14 downto 0) := "010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (14 downto 0) := "100000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal mod_value1 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal y1_phase1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal mod_value2 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal y2_phase1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal y3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_dec_2_21_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_dec_2_21_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_dec_2_21_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_dec_2_21_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_dec_2_21_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_int_2_21_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_int_2_21_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_int_2_21_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_int_2_21_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_int_2_21_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal y4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_dec_1_21_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_dec_1_21_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_dec_1_21_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_int_1_21_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_int_1_21_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_ZL21H_filter_FIR_int_1_21_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal H_dec_1_20_V_ce0 : STD_LOGIC;
    signal H_dec_1_20_V_we0 : STD_LOGIC;
    signal H_dec_1_20_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal H_dec_2_20_V_ce0 : STD_LOGIC;
    signal H_dec_2_20_V_we0 : STD_LOGIC;
    signal H_dec_2_20_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal H_int_2_20_V_ce0 : STD_LOGIC;
    signal H_int_2_20_V_we0 : STD_LOGIC;
    signal H_int_2_20_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal H_int_1_20_V_ce0 : STD_LOGIC;
    signal H_int_1_20_V_we0 : STD_LOGIC;
    signal H_int_1_20_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal input_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal output_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal mod_value1_load_reg_1197 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal mod_value1_load_load_fu_699_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln29_fu_773_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mod_value2_load_load_fu_780_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal mod_value2_load_reg_1211 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln35_fu_854_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln35_reg_1215 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal shl_ln52_fu_1190_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_fu_411_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_fu_411_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_fu_411_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_fu_411_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_fu_411_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_fu_411_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_fu_421_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_fu_421_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_fu_421_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_fu_421_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_fu_421_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_fu_421_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_1_fu_431_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_1_fu_431_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_1_fu_431_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_1_fu_431_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_1_fu_440_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_1_fu_440_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_1_fu_440_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_FIR_filter_1_fu_440_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_2_FIR_filter_transposed_fu_448_ap_start : STD_LOGIC;
    signal p_2_FIR_filter_transposed_fu_448_ap_done : STD_LOGIC;
    signal p_2_FIR_filter_transposed_fu_448_ap_idle : STD_LOGIC;
    signal p_2_FIR_filter_transposed_fu_448_ap_ready : STD_LOGIC;
    signal p_2_FIR_filter_transposed_fu_448_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln43_fu_1080_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_p_013_0_0_0_phi_fu_380_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_013_0_0_0_reg_377 : STD_LOGIC_VECTOR (15 downto 0);
    signal storemerge1_reg_386 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_storemerge_phi_fu_403_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal storemerge_reg_399 : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_output_r_U_apdone_blk : STD_LOGIC;
    signal ap_block_state9 : BOOLEAN;
    signal sext_ln29_fu_713_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_717_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln29_fu_713_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln29_fu_725_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln29_2_fu_741_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln29_1_cast_fu_731_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_fu_717_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln29_1_fu_751_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln29_2_fu_741_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln29_fu_757_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln29_1_fu_765_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln35_fu_794_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_10_fu_798_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln35_fu_794_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln35_fu_806_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln35_2_fu_822_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln35_1_cast_fu_812_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_10_fu_798_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln35_1_fu_832_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln35_2_fu_822_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal select_ln35_fu_838_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal sext_ln35_1_fu_846_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal regslice_both_input_r_U_apdone_blk : STD_LOGIC;
    signal input_r_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal input_r_TVALID_int_regslice : STD_LOGIC;
    signal input_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_input_r_U_ack_in : STD_LOGIC;
    signal output_r_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal output_r_TVALID_int_regslice : STD_LOGIC;
    signal output_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_output_r_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component FIR_Halfband_v2_FIR_filter IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        FIR_delays_read : IN STD_LOGIC_VECTOR (15 downto 0);
        FIR_delays_read_21 : IN STD_LOGIC_VECTOR (15 downto 0);
        FIR_delays_read_22 : IN STD_LOGIC_VECTOR (15 downto 0);
        FIR_delays_read_23 : IN STD_LOGIC_VECTOR (15 downto 0);
        FIR_delays_read_24 : IN STD_LOGIC_VECTOR (15 downto 0);
        FIR_delays_write : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component FIR_Halfband_v2_FIR_filter_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        FIR_delays_read : IN STD_LOGIC_VECTOR (15 downto 0);
        FIR_delays_read_8 : IN STD_LOGIC_VECTOR (15 downto 0);
        FIR_delays_read_9 : IN STD_LOGIC_VECTOR (15 downto 0);
        FIR_delays_write : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component FIR_Halfband_v2_FIR_filter_transposed IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x_n : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component FIR_Halfband_v2_H_dec_1_20_V_SHIFTREG_AUTO_0R0W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (0 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component FIR_Halfband_v2_H_dec_2_20_V_SHIFTREG_AUTO_0R0W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component FIR_Halfband_v2_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    H_dec_1_20_V_U : component FIR_Halfband_v2_H_dec_1_20_V_SHIFTREG_AUTO_0R0W
    generic map (
        DataWidth => 16,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => ap_const_lv1_1,
        ce0 => H_dec_1_20_V_ce0,
        we0 => H_dec_1_20_V_we0,
        d0 => input_r_TDATA_int_regslice,
        q0 => H_dec_1_20_V_q0);

    H_dec_2_20_V_U : component FIR_Halfband_v2_H_dec_2_20_V_SHIFTREG_AUTO_0R0W
    generic map (
        DataWidth => 16,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => ap_const_lv2_2,
        ce0 => H_dec_2_20_V_ce0,
        we0 => H_dec_2_20_V_we0,
        d0 => add_ln29_fu_773_p2,
        q0 => H_dec_2_20_V_q0);

    H_int_2_20_V_U : component FIR_Halfband_v2_H_dec_2_20_V_SHIFTREG_AUTO_0R0W
    generic map (
        DataWidth => 16,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => ap_const_lv2_2,
        ce0 => H_int_2_20_V_ce0,
        we0 => H_int_2_20_V_we0,
        d0 => p_2_FIR_filter_transposed_fu_448_ap_return,
        q0 => H_int_2_20_V_q0);

    H_int_1_20_V_U : component FIR_Halfband_v2_H_dec_1_20_V_SHIFTREG_AUTO_0R0W
    generic map (
        DataWidth => 16,
        AddressRange => 2,
        AddressWidth => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => ap_const_lv1_1,
        ce0 => H_int_1_20_V_ce0,
        we0 => H_int_1_20_V_we0,
        d0 => ap_phi_mux_p_013_0_0_0_phi_fu_380_p4,
        q0 => H_int_1_20_V_q0);

    grp_FIR_filter_fu_411 : component FIR_Halfband_v2_FIR_filter
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        FIR_delays_read => p_ZL21H_filter_FIR_dec_2_21_0,
        FIR_delays_read_21 => p_ZL21H_filter_FIR_dec_2_21_1,
        FIR_delays_read_22 => p_ZL21H_filter_FIR_dec_2_21_2,
        FIR_delays_read_23 => p_ZL21H_filter_FIR_dec_2_21_3,
        FIR_delays_read_24 => p_ZL21H_filter_FIR_dec_2_21_4,
        FIR_delays_write => add_ln29_fu_773_p2,
        ap_return_0 => grp_FIR_filter_fu_411_ap_return_0,
        ap_return_1 => grp_FIR_filter_fu_411_ap_return_1,
        ap_return_2 => grp_FIR_filter_fu_411_ap_return_2,
        ap_return_3 => grp_FIR_filter_fu_411_ap_return_3,
        ap_return_4 => grp_FIR_filter_fu_411_ap_return_4,
        ap_return_5 => grp_FIR_filter_fu_411_ap_return_5);

    grp_FIR_filter_fu_421 : component FIR_Halfband_v2_FIR_filter
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        FIR_delays_read => p_ZL21H_filter_FIR_int_2_21_0,
        FIR_delays_read_21 => p_ZL21H_filter_FIR_int_2_21_1,
        FIR_delays_read_22 => p_ZL21H_filter_FIR_int_2_21_2,
        FIR_delays_read_23 => p_ZL21H_filter_FIR_int_2_21_3,
        FIR_delays_read_24 => p_ZL21H_filter_FIR_int_2_21_4,
        FIR_delays_write => y3,
        ap_return_0 => grp_FIR_filter_fu_421_ap_return_0,
        ap_return_1 => grp_FIR_filter_fu_421_ap_return_1,
        ap_return_2 => grp_FIR_filter_fu_421_ap_return_2,
        ap_return_3 => grp_FIR_filter_fu_421_ap_return_3,
        ap_return_4 => grp_FIR_filter_fu_421_ap_return_4,
        ap_return_5 => grp_FIR_filter_fu_421_ap_return_5);

    grp_FIR_filter_1_fu_431 : component FIR_Halfband_v2_FIR_filter_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        FIR_delays_read => p_ZL21H_filter_FIR_dec_1_21_0,
        FIR_delays_read_8 => p_ZL21H_filter_FIR_dec_1_21_1,
        FIR_delays_read_9 => p_ZL21H_filter_FIR_dec_1_21_2,
        FIR_delays_write => input_r_TDATA_int_regslice,
        ap_return_0 => grp_FIR_filter_1_fu_431_ap_return_0,
        ap_return_1 => grp_FIR_filter_1_fu_431_ap_return_1,
        ap_return_2 => grp_FIR_filter_1_fu_431_ap_return_2,
        ap_return_3 => grp_FIR_filter_1_fu_431_ap_return_3);

    grp_FIR_filter_1_fu_440 : component FIR_Halfband_v2_FIR_filter_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        FIR_delays_read => p_ZL21H_filter_FIR_int_1_21_0,
        FIR_delays_read_8 => p_ZL21H_filter_FIR_int_1_21_1,
        FIR_delays_read_9 => p_ZL21H_filter_FIR_int_1_21_2,
        FIR_delays_write => y4,
        ap_return_0 => grp_FIR_filter_1_fu_440_ap_return_0,
        ap_return_1 => grp_FIR_filter_1_fu_440_ap_return_1,
        ap_return_2 => grp_FIR_filter_1_fu_440_ap_return_2,
        ap_return_3 => grp_FIR_filter_1_fu_440_ap_return_3);

    p_2_FIR_filter_transposed_fu_448 : component FIR_Halfband_v2_FIR_filter_transposed
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => p_2_FIR_filter_transposed_fu_448_ap_start,
        ap_done => p_2_FIR_filter_transposed_fu_448_ap_done,
        ap_idle => p_2_FIR_filter_transposed_fu_448_ap_idle,
        ap_ready => p_2_FIR_filter_transposed_fu_448_ap_ready,
        x_n => add_ln35_reg_1215,
        ap_return => p_2_FIR_filter_transposed_fu_448_ap_return);

    regslice_both_input_r_U : component FIR_Halfband_v2_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_r_TDATA,
        vld_in => input_r_TVALID,
        ack_in => regslice_both_input_r_U_ack_in,
        data_out => input_r_TDATA_int_regslice,
        vld_out => input_r_TVALID_int_regslice,
        ack_out => input_r_TREADY_int_regslice,
        apdone_blk => regslice_both_input_r_U_apdone_blk);

    regslice_both_output_r_U : component FIR_Halfband_v2_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => output_r_TDATA_int_regslice,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => output_r_TREADY_int_regslice,
        data_out => output_r_TDATA,
        vld_out => regslice_both_output_r_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    p_013_0_0_0_reg_377_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                p_013_0_0_0_reg_377 <= H_int_2_20_V_q0;
            elsif (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8) and (mod_value2_load_reg_1211 = ap_const_lv1_1))) then 
                p_013_0_0_0_reg_377 <= shl_ln43_fu_1080_p2;
            end if; 
        end if;
    end process;

    storemerge1_reg_386_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                storemerge1_reg_386 <= ap_const_lv1_1;
            elsif (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8) and (mod_value2_load_reg_1211 = ap_const_lv1_1))) then 
                storemerge1_reg_386 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    storemerge_reg_399_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state9) and (ap_const_logic_1 = ap_CS_fsm_state9) and (mod_value1_load_reg_1197 = ap_const_lv1_0))) then 
                storemerge_reg_399 <= ap_const_lv1_1;
            elsif (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state15))) then 
                storemerge_reg_399 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                add_ln35_reg_1215 <= add_ln35_fu_854_p2;
                mod_value1_load_reg_1197 <= mod_value1;
                mod_value2_load_reg_1211 <= mod_value2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state9) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                mod_value1 <= ap_phi_mux_storemerge_phi_fu_403_p4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state9) and (ap_const_logic_1 = ap_CS_fsm_state9) and (mod_value1_load_reg_1197 = ap_const_lv1_0))) then
                mod_value2 <= storemerge1_reg_386;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                p_ZL21H_filter_FIR_dec_1_21_0 <= grp_FIR_filter_1_fu_431_ap_return_1;
                p_ZL21H_filter_FIR_dec_1_21_1 <= grp_FIR_filter_1_fu_431_ap_return_2;
                p_ZL21H_filter_FIR_dec_1_21_2 <= grp_FIR_filter_1_fu_431_ap_return_3;
                p_ZL21H_filter_FIR_int_1_21_0 <= grp_FIR_filter_1_fu_440_ap_return_1;
                p_ZL21H_filter_FIR_int_1_21_1 <= grp_FIR_filter_1_fu_440_ap_return_2;
                p_ZL21H_filter_FIR_int_1_21_2 <= grp_FIR_filter_1_fu_440_ap_return_3;
                y1_phase1 <= grp_FIR_filter_1_fu_431_ap_return_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8) and (mod_value2_load_reg_1211 = ap_const_lv1_1))) then
                p_ZL21H_filter_FIR_dec_2_21_0 <= grp_FIR_filter_fu_411_ap_return_1;
                p_ZL21H_filter_FIR_dec_2_21_1 <= grp_FIR_filter_fu_411_ap_return_2;
                p_ZL21H_filter_FIR_dec_2_21_2 <= grp_FIR_filter_fu_411_ap_return_3;
                p_ZL21H_filter_FIR_dec_2_21_3 <= grp_FIR_filter_fu_411_ap_return_4;
                p_ZL21H_filter_FIR_dec_2_21_4 <= grp_FIR_filter_fu_411_ap_return_5;
                p_ZL21H_filter_FIR_int_2_21_0 <= grp_FIR_filter_fu_421_ap_return_1;
                p_ZL21H_filter_FIR_int_2_21_1 <= grp_FIR_filter_fu_421_ap_return_2;
                p_ZL21H_filter_FIR_int_2_21_2 <= grp_FIR_filter_fu_421_ap_return_3;
                p_ZL21H_filter_FIR_int_2_21_3 <= grp_FIR_filter_fu_421_ap_return_4;
                p_ZL21H_filter_FIR_int_2_21_4 <= grp_FIR_filter_fu_421_ap_return_5;
                y2_phase1 <= grp_FIR_filter_fu_411_ap_return_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                y3 <= p_2_FIR_filter_transposed_fu_448_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                y4 <= ap_phi_mux_p_013_0_0_0_phi_fu_380_p4;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state14, ap_CS_fsm_state15, mod_value1_load_load_fu_699_p1, mod_value2_load_load_fu_780_p1, ap_block_state9, input_r_TVALID_int_regslice, output_r_TREADY_int_regslice)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value2_load_load_fu_780_p1 = ap_const_lv1_1) and (mod_value1_load_load_fu_699_p1 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value2_load_load_fu_780_p1 = ap_const_lv1_0) and (mod_value1_load_load_fu_699_p1 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value1_load_load_fu_699_p1 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((ap_const_boolean_0 = ap_block_state9) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when ap_ST_fsm_state15 => 
                if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state15))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state15;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXX";
        end case;
    end process;

    H_dec_1_20_V_ce0_assign_proc : process(ap_CS_fsm_state1, mod_value1_load_load_fu_699_p1, input_r_TVALID_int_regslice)
    begin
        if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value1_load_load_fu_699_p1 = ap_const_lv1_0))) then 
            H_dec_1_20_V_ce0 <= ap_const_logic_1;
        else 
            H_dec_1_20_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    H_dec_1_20_V_we0_assign_proc : process(ap_CS_fsm_state1, mod_value1_load_load_fu_699_p1, input_r_TVALID_int_regslice)
    begin
        if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value1_load_load_fu_699_p1 = ap_const_lv1_0))) then 
            H_dec_1_20_V_we0 <= ap_const_logic_1;
        else 
            H_dec_1_20_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    H_dec_2_20_V_ce0_assign_proc : process(ap_CS_fsm_state1, mod_value1_load_load_fu_699_p1, mod_value2_load_load_fu_780_p1, input_r_TVALID_int_regslice)
    begin
        if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value2_load_load_fu_780_p1 = ap_const_lv1_0) and (mod_value1_load_load_fu_699_p1 = ap_const_lv1_0))) then 
            H_dec_2_20_V_ce0 <= ap_const_logic_1;
        else 
            H_dec_2_20_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    H_dec_2_20_V_we0_assign_proc : process(ap_CS_fsm_state1, mod_value1_load_load_fu_699_p1, mod_value2_load_load_fu_780_p1, input_r_TVALID_int_regslice)
    begin
        if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (mod_value2_load_load_fu_780_p1 = ap_const_lv1_0) and (mod_value1_load_load_fu_699_p1 = ap_const_lv1_0))) then 
            H_dec_2_20_V_we0 <= ap_const_logic_1;
        else 
            H_dec_2_20_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    H_int_1_20_V_ce0_assign_proc : process(ap_CS_fsm_state8, output_r_TREADY_int_regslice)
    begin
        if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            H_int_1_20_V_ce0 <= ap_const_logic_1;
        else 
            H_int_1_20_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    H_int_1_20_V_we0_assign_proc : process(ap_CS_fsm_state8, output_r_TREADY_int_regslice)
    begin
        if (((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            H_int_1_20_V_we0 <= ap_const_logic_1;
        else 
            H_int_1_20_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    H_int_2_20_V_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            H_int_2_20_V_ce0 <= ap_const_logic_1;
        else 
            H_int_2_20_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    H_int_2_20_V_we0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            H_int_2_20_V_we0 <= ap_const_logic_1;
        else 
            H_int_2_20_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln29_fu_773_p2 <= std_logic_vector(unsigned(y1_phase1) + unsigned(sext_ln29_1_fu_765_p1));
    add_ln35_fu_854_p2 <= std_logic_vector(unsigned(y2_phase1) + unsigned(sext_ln35_1_fu_846_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;

    ap_ST_fsm_state14_blk_assign_proc : process(output_r_TREADY_int_regslice)
    begin
        if ((output_r_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state15_blk_assign_proc : process(output_r_TREADY_int_regslice)
    begin
        if ((output_r_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state15_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state15_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(input_r_TVALID_int_regslice)
    begin
        if ((input_r_TVALID_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(output_r_TREADY_int_regslice)
    begin
        if ((output_r_TREADY_int_regslice = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(ap_block_state9)
    begin
        if ((ap_const_boolean_1 = ap_block_state9)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state9_assign_proc : process(mod_value1_load_reg_1197, regslice_both_output_r_U_apdone_blk, output_r_TREADY_int_regslice)
    begin
                ap_block_state9 <= ((regslice_both_output_r_U_apdone_blk = ap_const_logic_1) or ((output_r_TREADY_int_regslice = ap_const_logic_0) and (mod_value1_load_reg_1197 = ap_const_lv1_0)));
    end process;


    ap_phi_mux_p_013_0_0_0_phi_fu_380_p4_assign_proc : process(ap_CS_fsm_state8, mod_value2_load_reg_1211, shl_ln43_fu_1080_p2, p_013_0_0_0_reg_377)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) and (mod_value2_load_reg_1211 = ap_const_lv1_1))) then 
            ap_phi_mux_p_013_0_0_0_phi_fu_380_p4 <= shl_ln43_fu_1080_p2;
        else 
            ap_phi_mux_p_013_0_0_0_phi_fu_380_p4 <= p_013_0_0_0_reg_377;
        end if; 
    end process;


    ap_phi_mux_storemerge_phi_fu_403_p4_assign_proc : process(ap_CS_fsm_state9, mod_value1_load_reg_1197, storemerge_reg_399)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) and (mod_value1_load_reg_1197 = ap_const_lv1_0))) then 
            ap_phi_mux_storemerge_phi_fu_403_p4 <= ap_const_lv1_1;
        else 
            ap_phi_mux_storemerge_phi_fu_403_p4 <= storemerge_reg_399;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    input_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, input_r_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            input_r_TDATA_blk_n <= input_r_TVALID_int_regslice;
        else 
            input_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    input_r_TREADY <= regslice_both_input_r_U_ack_in;

    input_r_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, input_r_TVALID_int_regslice)
    begin
        if (((input_r_TVALID_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            input_r_TREADY_int_regslice <= ap_const_logic_1;
        else 
            input_r_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    mod_value1_load_load_fu_699_p1 <= mod_value1;
    mod_value2_load_load_fu_780_p1 <= mod_value2;

    output_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state9, mod_value1_load_reg_1197, ap_CS_fsm_state14, ap_CS_fsm_state15, output_r_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (mod_value1_load_reg_1197 = ap_const_lv1_0)))) then 
            output_r_TDATA_blk_n <= output_r_TREADY_int_regslice;
        else 
            output_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    output_r_TDATA_int_regslice_assign_proc : process(H_int_1_20_V_q0, ap_CS_fsm_state8, ap_CS_fsm_state14, shl_ln52_fu_1190_p2, output_r_TREADY_int_regslice)
    begin
        if ((output_r_TREADY_int_regslice = ap_const_logic_1)) then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                output_r_TDATA_int_regslice <= shl_ln52_fu_1190_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                output_r_TDATA_int_regslice <= H_int_1_20_V_q0;
            else 
                output_r_TDATA_int_regslice <= "XXXXXXXXXXXXXXXX";
            end if;
        else 
            output_r_TDATA_int_regslice <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    output_r_TVALID <= regslice_both_output_r_U_vld_out;

    output_r_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_state8, ap_CS_fsm_state14, output_r_TREADY_int_regslice)
    begin
        if ((((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14)) or ((output_r_TREADY_int_regslice = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8)))) then 
            output_r_TVALID_int_regslice <= ap_const_logic_1;
        else 
            output_r_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    p_2_FIR_filter_transposed_fu_448_ap_start_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            p_2_FIR_filter_transposed_fu_448_ap_start <= ap_const_logic_1;
        else 
            p_2_FIR_filter_transposed_fu_448_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    select_ln29_fu_757_p3 <= 
        sub_ln29_1_fu_751_p2 when (tmp_fu_717_p3(0) = '1') else 
        trunc_ln29_2_fu_741_p4;
    select_ln35_fu_838_p3 <= 
        sub_ln35_1_fu_832_p2 when (tmp_10_fu_798_p3(0) = '1') else 
        trunc_ln35_2_fu_822_p4;
        sext_ln29_1_fu_765_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln29_fu_757_p3),16));

    sext_ln29_fu_713_p0 <= H_dec_1_20_V_q0;
        sext_ln29_fu_713_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln29_fu_713_p0),17));

        sext_ln35_1_fu_846_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln35_fu_838_p3),16));

    sext_ln35_fu_794_p0 <= H_dec_2_20_V_q0;
        sext_ln35_fu_794_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln35_fu_794_p0),17));

    shl_ln43_fu_1080_p2 <= std_logic_vector(shift_left(unsigned(grp_FIR_filter_fu_421_ap_return_0),to_integer(unsigned('0' & ap_const_lv16_1(16-1 downto 0)))));
    shl_ln52_fu_1190_p2 <= std_logic_vector(shift_left(unsigned(grp_FIR_filter_1_fu_440_ap_return_0),to_integer(unsigned('0' & ap_const_lv16_1(16-1 downto 0)))));
    sub_ln29_1_fu_751_p2 <= std_logic_vector(unsigned(ap_const_lv15_0) - unsigned(trunc_ln29_1_cast_fu_731_p4));
    sub_ln29_fu_725_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(sext_ln29_fu_713_p1));
    sub_ln35_1_fu_832_p2 <= std_logic_vector(unsigned(ap_const_lv15_0) - unsigned(trunc_ln35_1_cast_fu_812_p4));
    sub_ln35_fu_806_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(sext_ln35_fu_794_p1));
    tmp_10_fu_798_p1 <= H_dec_2_20_V_q0;
    tmp_10_fu_798_p3 <= tmp_10_fu_798_p1(15 downto 15);
    tmp_fu_717_p1 <= H_dec_1_20_V_q0;
    tmp_fu_717_p3 <= tmp_fu_717_p1(15 downto 15);
    trunc_ln29_1_cast_fu_731_p4 <= sub_ln29_fu_725_p2(15 downto 1);
    trunc_ln29_2_fu_741_p1 <= H_dec_1_20_V_q0;
    trunc_ln29_2_fu_741_p4 <= trunc_ln29_2_fu_741_p1(15 downto 1);
    trunc_ln35_1_cast_fu_812_p4 <= sub_ln35_fu_806_p2(15 downto 1);
    trunc_ln35_2_fu_822_p1 <= H_dec_2_20_V_q0;
    trunc_ln35_2_fu_822_p4 <= trunc_ln35_2_fu_822_p1(15 downto 1);
end behav;
