// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Multirate_v2_FIR_filter_transposed (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_n,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] x_n;
output  [15:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
reg   [31:0] p_ZL10H_accu_FIR_0;
reg   [31:0] p_ZL10H_accu_FIR_1;
reg   [31:0] p_ZL10H_accu_FIR_2;
reg   [31:0] p_ZL10H_accu_FIR_3;
reg   [31:0] p_ZL10H_accu_FIR_4;
reg   [31:0] p_ZL10H_accu_FIR_5;
reg   [31:0] p_ZL10H_accu_FIR_6;
reg   [31:0] p_ZL10H_accu_FIR_7;
reg   [31:0] p_ZL10H_accu_FIR_8;
reg   [31:0] p_ZL10H_accu_FIR_9;
reg   [31:0] p_ZL10H_accu_FIR_10;
reg   [31:0] p_ZL10H_accu_FIR_11;
reg   [31:0] p_ZL10H_accu_FIR_12;
reg   [31:0] p_ZL10H_accu_FIR_13;
reg   [31:0] p_ZL10H_accu_FIR_14;
reg   [31:0] p_ZL10H_accu_FIR_15;
reg   [31:0] p_ZL10H_accu_FIR_16;
reg   [31:0] p_ZL10H_accu_FIR_17;
reg   [31:0] p_ZL10H_accu_FIR_18;
reg   [31:0] p_ZL10H_accu_FIR_19;
reg   [31:0] p_ZL10H_accu_FIR_20;
reg   [31:0] p_ZL10H_accu_FIR_21;
reg   [31:0] p_ZL10H_accu_FIR_22;
reg   [31:0] p_ZL10H_accu_FIR_23;
reg   [31:0] p_ZL10H_accu_FIR_24;
reg   [31:0] p_ZL10H_accu_FIR_25;
reg   [31:0] p_ZL10H_accu_FIR_26;
reg   [31:0] p_ZL10H_accu_FIR_27;
reg   [31:0] p_ZL10H_accu_FIR_28;
reg   [31:0] p_ZL10H_accu_FIR_29;
reg   [31:0] p_ZL10H_accu_FIR_30;
reg   [31:0] p_ZL10H_accu_FIR_31;
reg   [31:0] p_ZL10H_accu_FIR_32;
reg   [31:0] p_ZL10H_accu_FIR_33;
reg   [31:0] p_ZL10H_accu_FIR_34;
reg   [31:0] p_ZL10H_accu_FIR_35;
reg   [31:0] p_ZL10H_accu_FIR_36;
reg   [31:0] p_ZL10H_accu_FIR_37;
reg   [31:0] p_ZL10H_accu_FIR_38;
reg   [31:0] p_ZL10H_accu_FIR_39;
reg   [31:0] p_ZL10H_accu_FIR_40;
reg   [31:0] p_ZL10H_accu_FIR_41;
reg   [31:0] p_ZL10H_accu_FIR_42;
reg   [31:0] p_ZL10H_accu_FIR_43;
reg   [31:0] p_ZL10H_accu_FIR_44;
reg   [31:0] p_ZL10H_accu_FIR_45;
reg   [31:0] p_ZL10H_accu_FIR_46;
reg   [31:0] p_ZL10H_accu_FIR_47;
reg   [31:0] p_ZL10H_accu_FIR_48;
reg   [31:0] p_ZL10H_accu_FIR_49;
reg   [31:0] p_ZL10H_accu_FIR_50;
reg   [31:0] p_ZL10H_accu_FIR_51;
reg   [31:0] p_ZL10H_accu_FIR_52;
reg   [31:0] p_ZL10H_accu_FIR_53;
reg   [31:0] p_ZL10H_accu_FIR_54;
reg   [31:0] p_ZL10H_accu_FIR_55;
reg   [31:0] p_ZL10H_accu_FIR_56;
reg   [31:0] p_ZL10H_accu_FIR_57;
reg   [31:0] p_ZL10H_accu_FIR_58;
reg   [31:0] p_ZL10H_accu_FIR_59;
reg   [31:0] p_ZL10H_accu_FIR_60;
reg   [31:0] p_ZL10H_accu_FIR_61;
reg   [31:0] p_ZL10H_accu_FIR_62;
reg   [31:0] p_ZL10H_accu_FIR_63;
reg   [31:0] p_ZL10H_accu_FIR_64;
reg   [31:0] p_ZL10H_accu_FIR_65;
reg   [31:0] p_ZL10H_accu_FIR_66;
reg   [31:0] p_ZL10H_accu_FIR_67;
reg   [31:0] p_ZL10H_accu_FIR_68;
reg   [31:0] p_ZL10H_accu_FIR_69;
reg   [31:0] p_ZL10H_accu_FIR_70;
reg   [31:0] p_ZL10H_accu_FIR_71;
reg   [31:0] p_ZL10H_accu_FIR_72;
reg   [31:0] p_ZL10H_accu_FIR_73;
reg   [31:0] p_ZL10H_accu_FIR_74;
reg   [31:0] p_ZL10H_accu_FIR_75;
reg   [31:0] p_ZL10H_accu_FIR_76;
reg   [31:0] p_ZL10H_accu_FIR_77;
reg   [31:0] p_ZL10H_accu_FIR_78;
reg   [31:0] p_ZL10H_accu_FIR_79;
reg   [31:0] p_ZL10H_accu_FIR_80;
reg   [31:0] p_ZL10H_accu_FIR_81;
reg   [31:0] p_ZL10H_accu_FIR_82;
reg   [31:0] p_ZL10H_accu_FIR_83;
reg   [31:0] p_ZL10H_accu_FIR_84;
reg   [31:0] p_ZL10H_accu_FIR_85;
reg   [31:0] p_ZL10H_accu_FIR_86;
reg   [31:0] p_ZL10H_accu_FIR_87;
reg   [31:0] p_ZL10H_accu_FIR_88;
reg   [31:0] p_ZL10H_accu_FIR_89;
reg   [31:0] p_ZL10H_accu_FIR_90;
reg   [31:0] p_ZL10H_accu_FIR_91;
reg   [31:0] p_ZL10H_accu_FIR_92;
reg   [31:0] p_ZL10H_accu_FIR_93;
reg   [31:0] p_ZL10H_accu_FIR_94;
reg   [31:0] p_ZL10H_accu_FIR_95;
reg   [31:0] p_ZL10H_accu_FIR_96;
reg   [31:0] p_ZL10H_accu_FIR_97;
reg   [31:0] p_ZL10H_accu_FIR_98;
reg   [31:0] p_ZL10H_accu_FIR_99;
reg   [31:0] p_ZL10H_accu_FIR_100;
reg   [31:0] p_ZL10H_accu_FIR_101;
reg   [31:0] p_ZL10H_accu_FIR_102;
reg   [31:0] p_ZL10H_accu_FIR_103;
reg   [31:0] p_ZL10H_accu_FIR_104;
reg   [31:0] p_ZL10H_accu_FIR_105;
reg   [30:0] p_ZL10H_accu_FIR_106;
reg   [29:0] p_ZL10H_accu_FIR_107;
reg   [28:0] p_ZL10H_accu_FIR_108;
reg   [27:0] p_ZL10H_accu_FIR_109;
reg   [26:0] p_ZL10H_accu_FIR_110;
reg   [25:0] p_ZL10H_accu_FIR_111;
reg   [25:0] p_ZL10H_accu_FIR_112;
reg   [24:0] p_ZL10H_accu_FIR_113;
reg   [24:0] p_ZL10H_accu_FIR_114;
reg   [22:0] p_ZL10H_accu_FIR_115;
reg  signed [15:0] x_n_read_reg_2930;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] x_n_read_reg_2930_pp0_iter1_reg;
wire  signed [31:0] sext_ln84_fu_384_p1;
reg  signed [31:0] sext_ln84_reg_2951;
reg  signed [31:0] sext_ln84_reg_2951_pp0_iter1_reg;
wire  signed [31:0] sext_ln84_10_fu_439_p1;
reg  signed [31:0] sext_ln84_10_reg_2957;
wire  signed [24:0] mul_ln87_fu_443_p2;
reg  signed [24:0] mul_ln87_reg_2963;
wire  signed [17:0] tmp_fu_458_p3;
reg  signed [17:0] tmp_reg_2968;
wire  signed [23:0] mul_ln87_1_fu_470_p2;
reg  signed [23:0] mul_ln87_1_reg_2973;
wire  signed [21:0] sub_ln87_1_fu_491_p2;
reg  signed [21:0] sub_ln87_1_reg_2978;
wire  signed [23:0] mul_ln87_2_fu_501_p2;
reg  signed [23:0] mul_ln87_2_reg_2983;
wire  signed [21:0] mul_ln87_3_fu_511_p2;
reg  signed [21:0] mul_ln87_3_reg_2988;
wire  signed [23:0] mul_ln87_4_fu_521_p2;
reg  signed [23:0] mul_ln87_4_reg_2993;
wire  signed [31:0] sext_ln87_8_fu_537_p1;
reg  signed [31:0] sext_ln87_8_reg_2998;
wire  signed [24:0] sub_ln87_3_fu_566_p2;
reg  signed [24:0] sub_ln87_3_reg_3004;
wire  signed [31:0] sext_ln87_10_fu_583_p1;
reg  signed [31:0] sext_ln87_10_reg_3009;
wire  signed [31:0] sext_ln87_11_fu_593_p1;
reg  signed [31:0] sext_ln87_11_reg_3015;
wire  signed [31:0] sext_ln87_12_fu_603_p1;
reg  signed [31:0] sext_ln87_12_reg_3020;
wire  signed [31:0] sext_ln87_13_fu_613_p1;
reg  signed [31:0] sext_ln87_13_reg_3025;
wire  signed [31:0] sext_ln87_14_fu_623_p1;
reg  signed [31:0] sext_ln87_14_reg_3030;
wire  signed [31:0] sext_ln87_15_fu_633_p1;
reg  signed [31:0] sext_ln87_15_reg_3035;
wire  signed [31:0] sext_ln87_16_fu_643_p1;
reg  signed [31:0] sext_ln87_16_reg_3040;
wire  signed [31:0] sext_ln87_17_fu_653_p1;
reg  signed [31:0] sext_ln87_17_reg_3045;
wire  signed [31:0] sext_ln87_18_fu_663_p1;
reg  signed [31:0] sext_ln87_18_reg_3050;
wire  signed [31:0] sext_ln87_19_fu_673_p1;
reg  signed [31:0] sext_ln87_19_reg_3055;
wire  signed [31:0] sext_ln87_20_fu_694_p1;
reg  signed [31:0] sext_ln87_20_reg_3060;
wire  signed [31:0] sext_ln87_21_fu_704_p1;
reg  signed [31:0] sext_ln87_21_reg_3065;
wire  signed [31:0] sext_ln87_22_fu_722_p1;
reg  signed [31:0] sext_ln87_22_reg_3070;
wire  signed [31:0] sext_ln87_23_fu_732_p1;
reg  signed [31:0] sext_ln87_23_reg_3075;
wire  signed [31:0] sext_ln87_24_fu_742_p1;
reg  signed [31:0] sext_ln87_24_reg_3080;
wire  signed [31:0] sext_ln87_25_fu_752_p1;
reg  signed [31:0] sext_ln87_25_reg_3085;
wire  signed [31:0] sext_ln87_26_fu_762_p1;
reg  signed [31:0] sext_ln87_26_reg_3090;
wire  signed [31:0] sext_ln87_27_fu_786_p1;
reg  signed [31:0] sext_ln87_27_reg_3095;
wire  signed [31:0] sext_ln87_28_fu_796_p1;
reg  signed [31:0] sext_ln87_28_reg_3100;
wire  signed [31:0] sext_ln87_29_fu_806_p1;
reg  signed [31:0] sext_ln87_29_reg_3105;
wire  signed [31:0] sext_ln87_30_fu_827_p1;
reg  signed [31:0] sext_ln87_30_reg_3110;
wire  signed [31:0] sext_ln87_31_fu_837_p1;
reg  signed [31:0] sext_ln87_31_reg_3115;
wire  signed [31:0] sext_ln87_32_fu_847_p1;
reg  signed [31:0] sext_ln87_32_reg_3120;
wire  signed [31:0] sext_ln87_33_fu_857_p1;
reg  signed [31:0] sext_ln87_33_reg_3125;
wire  signed [31:0] sext_ln87_34_fu_867_p1;
reg  signed [31:0] sext_ln87_34_reg_3130;
wire  signed [31:0] sext_ln87_35_fu_877_p1;
reg  signed [31:0] sext_ln87_35_reg_3135;
wire  signed [31:0] sext_ln87_36_fu_887_p1;
reg  signed [31:0] sext_ln87_36_reg_3140;
wire  signed [31:0] sext_ln87_37_fu_897_p1;
reg  signed [31:0] sext_ln87_37_reg_3145;
wire  signed [31:0] sext_ln87_38_fu_907_p1;
reg  signed [31:0] sext_ln87_38_reg_3150;
wire  signed [31:0] sext_ln87_39_fu_917_p1;
reg  signed [31:0] sext_ln87_39_reg_3155;
wire  signed [31:0] sext_ln87_40_fu_927_p1;
reg  signed [31:0] sext_ln87_40_reg_3160;
wire  signed [31:0] sext_ln87_41_fu_937_p1;
reg  signed [31:0] sext_ln87_41_reg_3165;
wire  signed [31:0] sext_ln87_42_fu_947_p1;
reg  signed [31:0] sext_ln87_42_reg_3170;
wire  signed [31:0] sext_ln87_43_fu_957_p1;
reg  signed [31:0] sext_ln87_43_reg_3176;
wire  signed [31:0] sext_ln87_44_fu_967_p1;
reg  signed [31:0] sext_ln87_44_reg_3181;
wire  signed [31:0] sext_ln87_45_fu_977_p1;
reg  signed [31:0] sext_ln87_45_reg_3186;
wire  signed [31:0] sext_ln87_46_fu_987_p1;
reg  signed [31:0] sext_ln87_46_reg_3191;
wire  signed [31:0] sext_ln87_47_fu_997_p1;
reg  signed [31:0] sext_ln87_47_reg_3196;
wire  signed [31:0] sext_ln87_48_fu_1007_p1;
reg  signed [31:0] sext_ln87_48_reg_3201;
wire  signed [31:0] sext_ln87_49_fu_1017_p1;
reg  signed [31:0] sext_ln87_49_reg_3206;
wire  signed [31:0] sext_ln87_50_fu_1027_p1;
reg  signed [31:0] sext_ln87_50_reg_3211;
wire  signed [31:0] sext_ln87_51_fu_1037_p1;
reg  signed [31:0] sext_ln87_51_reg_3216;
wire  signed [31:0] sext_ln87_52_fu_1047_p1;
reg  signed [31:0] sext_ln87_52_reg_3221;
wire   [31:0] mul_ln87_44_fu_1051_p2;
reg   [31:0] mul_ln87_44_reg_3226;
wire   [31:0] add_ln87_fu_2036_p2;
wire    ap_block_pp0_stage0;
wire   [31:0] add_ln87_1_fu_2067_p2;
wire   [31:0] add_ln87_2_fu_2077_p2;
wire   [31:0] add_ln87_3_fu_2087_p2;
wire   [31:0] add_ln87_4_fu_2097_p2;
wire   [31:0] add_ln87_5_fu_2107_p2;
wire   [31:0] add_ln87_6_fu_2117_p2;
wire   [31:0] add_ln87_7_fu_2127_p2;
wire   [31:0] add_ln87_8_fu_2136_p2;
wire   [31:0] add_ln87_9_fu_2146_p2;
wire   [31:0] add_ln87_10_fu_2155_p2;
wire   [31:0] add_ln87_11_fu_2164_p2;
wire   [31:0] add_ln87_12_fu_2173_p2;
wire   [31:0] add_ln87_13_fu_2182_p2;
wire   [31:0] add_ln87_14_fu_2191_p2;
wire   [31:0] add_ln87_15_fu_2200_p2;
wire   [31:0] add_ln87_16_fu_2209_p2;
wire   [31:0] add_ln87_17_fu_2218_p2;
wire   [31:0] add_ln87_18_fu_2227_p2;
wire   [31:0] add_ln87_19_fu_2236_p2;
wire   [31:0] add_ln87_20_fu_2245_p2;
wire   [31:0] add_ln87_21_fu_2254_p2;
wire   [31:0] add_ln87_22_fu_2263_p2;
wire   [31:0] add_ln87_23_fu_2272_p2;
wire   [31:0] add_ln87_24_fu_2281_p2;
wire   [31:0] add_ln87_25_fu_2290_p2;
wire   [31:0] add_ln87_26_fu_2299_p2;
wire   [31:0] add_ln87_27_fu_2308_p2;
wire   [31:0] add_ln87_28_fu_2317_p2;
wire   [31:0] add_ln87_29_fu_2326_p2;
wire   [31:0] add_ln87_30_fu_2335_p2;
wire   [31:0] add_ln87_31_fu_2344_p2;
wire   [31:0] add_ln87_32_fu_2353_p2;
wire   [31:0] add_ln87_33_fu_2362_p2;
wire   [31:0] add_ln87_34_fu_2371_p2;
wire   [31:0] add_ln87_35_fu_2380_p2;
wire   [31:0] add_ln87_36_fu_2389_p2;
wire   [31:0] add_ln87_37_fu_2398_p2;
wire   [31:0] add_ln87_38_fu_2407_p2;
wire   [31:0] add_ln87_39_fu_2416_p2;
wire   [31:0] add_ln87_40_fu_2425_p2;
wire   [31:0] add_ln87_41_fu_2434_p2;
wire   [31:0] add_ln87_42_fu_2443_p2;
wire   [31:0] add_ln87_43_fu_2452_p2;
wire   [31:0] add_ln87_44_fu_2461_p2;
wire   [31:0] add_ln87_45_fu_2470_p2;
wire   [31:0] add_ln87_46_fu_2479_p2;
wire   [31:0] add_ln87_47_fu_2488_p2;
wire   [31:0] add_ln87_48_fu_2497_p2;
wire   [31:0] add_ln87_49_fu_2506_p2;
wire   [31:0] add_ln87_50_fu_2515_p2;
wire   [31:0] add_ln87_51_fu_2524_p2;
wire   [31:0] add_ln87_52_fu_2533_p2;
wire   [31:0] add_ln87_53_fu_2542_p2;
wire   [31:0] add_ln87_54_fu_2551_p2;
wire   [31:0] add_ln87_55_fu_2560_p2;
wire   [31:0] add_ln87_56_fu_2569_p2;
wire   [31:0] grp_fu_2921_p3;
wire   [31:0] add_ln87_58_fu_1064_p2;
wire   [31:0] add_ln87_59_fu_1074_p2;
wire   [31:0] add_ln87_60_fu_1084_p2;
wire   [31:0] add_ln87_61_fu_1094_p2;
wire   [31:0] add_ln87_62_fu_1104_p2;
wire   [31:0] add_ln87_63_fu_1114_p2;
wire   [31:0] add_ln87_64_fu_1124_p2;
wire   [31:0] add_ln87_65_fu_1134_p2;
wire   [31:0] add_ln87_66_fu_1144_p2;
wire   [31:0] add_ln87_67_fu_1154_p2;
wire   [31:0] add_ln87_68_fu_1164_p2;
wire   [31:0] add_ln87_69_fu_1174_p2;
wire   [31:0] add_ln87_70_fu_1184_p2;
wire   [31:0] add_ln87_71_fu_1194_p2;
wire   [31:0] add_ln87_72_fu_1204_p2;
wire   [31:0] add_ln87_73_fu_1214_p2;
wire   [31:0] add_ln87_74_fu_1224_p2;
wire   [31:0] add_ln87_75_fu_1234_p2;
wire   [31:0] add_ln87_76_fu_1244_p2;
wire   [31:0] add_ln87_77_fu_1254_p2;
wire   [31:0] add_ln87_78_fu_1264_p2;
wire   [31:0] add_ln87_79_fu_1274_p2;
wire   [31:0] add_ln87_80_fu_1284_p2;
wire   [31:0] add_ln87_81_fu_1294_p2;
wire   [31:0] add_ln87_82_fu_1304_p2;
wire   [31:0] add_ln87_83_fu_1314_p2;
wire   [31:0] add_ln87_84_fu_1324_p2;
wire   [31:0] add_ln87_85_fu_1334_p2;
wire   [31:0] add_ln87_86_fu_1344_p2;
wire   [31:0] add_ln87_87_fu_1354_p2;
wire   [31:0] add_ln87_88_fu_1364_p2;
wire   [31:0] add_ln87_89_fu_1374_p2;
wire   [31:0] add_ln87_90_fu_1384_p2;
wire   [31:0] add_ln87_91_fu_1394_p2;
wire   [31:0] add_ln87_92_fu_1404_p2;
wire   [31:0] add_ln87_93_fu_1414_p2;
wire   [31:0] add_ln87_94_fu_1424_p2;
wire   [31:0] add_ln87_95_fu_1434_p2;
wire   [31:0] add_ln87_96_fu_1444_p2;
wire   [31:0] add_ln87_97_fu_1454_p2;
wire   [31:0] add_ln87_98_fu_1464_p2;
wire   [31:0] add_ln87_99_fu_1474_p2;
wire   [31:0] add_ln87_100_fu_1484_p2;
wire   [31:0] add_ln87_101_fu_1494_p2;
wire   [31:0] add_ln87_102_fu_1504_p2;
wire   [31:0] add_ln87_103_fu_1514_p2;
wire   [31:0] add_ln87_104_fu_1524_p2;
wire   [31:0] add_ln87_105_fu_1538_p2;
wire   [30:0] add_ln87_106_fu_1552_p2;
wire   [29:0] add_ln87_107_fu_1566_p2;
wire   [28:0] add_ln87_108_fu_1580_p2;
wire   [27:0] add_ln87_109_fu_1594_p2;
wire   [26:0] add_ln87_110_fu_1608_p2;
wire   [25:0] add_ln87_111_fu_1618_p2;
wire   [25:0] add_ln87_112_fu_1632_p2;
wire   [24:0] add_ln87_113_fu_1642_p2;
wire   [24:0] add_ln87_114_fu_1656_p2;
wire  signed [22:0] sub_ln84_fu_433_p2;
wire  signed [15:0] sext_ln84_fu_384_p0;
wire   [17:0] tmp_1_fu_422_p3;
wire  signed [22:0] p_shl_fu_415_p3;
wire  signed [22:0] sext_ln84_11_fu_429_p1;
wire  signed [15:0] mul_ln87_fu_443_p0;
wire  signed [24:0] sext_ln84_8_fu_409_p1;
wire  signed [8:0] mul_ln87_fu_443_p1;
wire  signed [16:0] sext_ln87_1_fu_449_p1;
wire   [16:0] sub_ln87_fu_452_p2;
wire  signed [15:0] mul_ln87_1_fu_470_p0;
wire  signed [23:0] sext_ln84_7_fu_406_p1;
wire   [7:0] mul_ln87_1_fu_470_p1;
wire   [20:0] tmp_2_fu_480_p3;
wire  signed [21:0] sext_ln87_56_fu_487_p1;
wire  signed [15:0] mul_ln87_2_fu_501_p0;
wire  signed [7:0] mul_ln87_2_fu_501_p1;
wire   [5:0] mul_ln87_3_fu_511_p1;
wire  signed [15:0] mul_ln87_4_fu_521_p0;
wire   [7:0] mul_ln87_4_fu_521_p1;
wire  signed [6:0] mul_ln87_5_fu_531_p1;
wire  signed [22:0] mul_ln87_5_fu_531_p2;
wire  signed [24:0] sext_ln87_62_fu_545_p1;
wire  signed [16:0] tmp_3_fu_555_p3;
wire   [24:0] sub_ln87_2_fu_549_p2;
wire  signed [24:0] sext_ln87_63_fu_562_p1;
wire   [21:0] shl_ln87_1_fu_576_p3;
wire  signed [15:0] mul_ln87_6_fu_587_p0;
wire   [8:0] mul_ln87_6_fu_587_p1;
wire   [24:0] mul_ln87_6_fu_587_p2;
wire  signed [15:0] mul_ln87_7_fu_597_p0;
wire  signed [7:0] mul_ln87_7_fu_597_p1;
wire   [23:0] mul_ln87_7_fu_597_p2;
wire  signed [15:0] mul_ln87_8_fu_607_p0;
wire  signed [8:0] mul_ln87_8_fu_607_p1;
wire   [24:0] mul_ln87_8_fu_607_p2;
wire  signed [15:0] mul_ln87_9_fu_617_p0;
wire   [8:0] mul_ln87_9_fu_617_p1;
wire   [24:0] mul_ln87_9_fu_617_p2;
wire  signed [15:0] mul_ln87_10_fu_627_p0;
wire  signed [8:0] mul_ln87_10_fu_627_p1;
wire   [24:0] mul_ln87_10_fu_627_p2;
wire  signed [15:0] mul_ln87_11_fu_637_p0;
wire  signed [8:0] mul_ln87_11_fu_637_p1;
wire   [24:0] mul_ln87_11_fu_637_p2;
wire  signed [15:0] mul_ln87_12_fu_647_p0;
wire   [8:0] mul_ln87_12_fu_647_p1;
wire   [24:0] mul_ln87_12_fu_647_p2;
wire  signed [15:0] mul_ln87_13_fu_657_p0;
wire   [8:0] mul_ln87_13_fu_657_p1;
wire   [24:0] mul_ln87_13_fu_657_p2;
wire  signed [15:0] mul_ln87_14_fu_667_p0;
wire  signed [8:0] mul_ln87_14_fu_667_p1;
wire   [24:0] mul_ln87_14_fu_667_p2;
wire  signed [19:0] tmp_4_fu_677_p3;
wire  signed [24:0] sext_ln87_65_fu_684_p1;
wire   [24:0] sub_ln87_4_fu_688_p2;
wire  signed [15:0] mul_ln87_15_fu_698_p0;
wire  signed [25:0] sext_ln84_5_fu_400_p1;
wire   [9:0] mul_ln87_15_fu_698_p1;
wire   [25:0] mul_ln87_15_fu_698_p2;
wire  signed [23:0] sext_ln87_66_fu_708_p1;
wire  signed [23:0] sext_ln87_67_fu_712_p1;
wire   [23:0] sub_ln87_5_fu_716_p2;
wire  signed [15:0] mul_ln87_16_fu_726_p0;
wire  signed [9:0] mul_ln87_16_fu_726_p1;
wire   [25:0] mul_ln87_16_fu_726_p2;
wire  signed [15:0] mul_ln87_17_fu_736_p0;
wire  signed [7:0] mul_ln87_17_fu_736_p1;
wire   [23:0] mul_ln87_17_fu_736_p2;
wire  signed [15:0] mul_ln87_18_fu_746_p0;
wire   [9:0] mul_ln87_18_fu_746_p1;
wire   [25:0] mul_ln87_18_fu_746_p2;
wire  signed [15:0] mul_ln87_19_fu_756_p0;
wire  signed [9:0] mul_ln87_19_fu_756_p1;
wire   [25:0] mul_ln87_19_fu_756_p2;
wire  signed [21:0] sext_ln87_68_fu_766_p1;
wire   [21:0] sub_ln87_6_fu_770_p2;
wire  signed [21:0] sext_ln87_69_fu_776_p1;
wire   [21:0] sub_ln87_7_fu_780_p2;
wire  signed [15:0] mul_ln87_20_fu_790_p0;
wire  signed [26:0] sext_ln84_4_fu_397_p1;
wire   [10:0] mul_ln87_20_fu_790_p1;
wire   [26:0] mul_ln87_20_fu_790_p2;
wire  signed [15:0] mul_ln87_21_fu_800_p0;
wire  signed [10:0] mul_ln87_21_fu_800_p1;
wire   [26:0] mul_ln87_21_fu_800_p2;
wire   [18:0] tmp_5_fu_810_p3;
wire  signed [23:0] sext_ln87_70_fu_817_p1;
wire   [23:0] sub_ln87_8_fu_821_p2;
wire  signed [15:0] mul_ln87_22_fu_831_p0;
wire   [10:0] mul_ln87_22_fu_831_p1;
wire   [26:0] mul_ln87_22_fu_831_p2;
wire  signed [15:0] mul_ln87_23_fu_841_p0;
wire  signed [8:0] mul_ln87_23_fu_841_p1;
wire   [24:0] mul_ln87_23_fu_841_p2;
wire  signed [15:0] mul_ln87_24_fu_851_p0;
wire  signed [10:0] mul_ln87_24_fu_851_p1;
wire   [26:0] mul_ln87_24_fu_851_p2;
wire  signed [15:0] mul_ln87_25_fu_861_p0;
wire   [9:0] mul_ln87_25_fu_861_p1;
wire   [25:0] mul_ln87_25_fu_861_p2;
wire  signed [15:0] mul_ln87_26_fu_871_p0;
wire   [10:0] mul_ln87_26_fu_871_p1;
wire   [26:0] mul_ln87_26_fu_871_p2;
wire  signed [15:0] mul_ln87_27_fu_881_p0;
wire  signed [9:0] mul_ln87_27_fu_881_p1;
wire   [25:0] mul_ln87_27_fu_881_p2;
wire  signed [15:0] mul_ln87_28_fu_891_p0;
wire  signed [10:0] mul_ln87_28_fu_891_p1;
wire   [26:0] mul_ln87_28_fu_891_p2;
wire  signed [15:0] mul_ln87_29_fu_901_p0;
wire   [10:0] mul_ln87_29_fu_901_p1;
wire   [26:0] mul_ln87_29_fu_901_p2;
wire  signed [15:0] mul_ln87_30_fu_911_p0;
wire   [10:0] mul_ln87_30_fu_911_p1;
wire   [26:0] mul_ln87_30_fu_911_p2;
wire  signed [15:0] mul_ln87_31_fu_921_p0;
wire  signed [10:0] mul_ln87_31_fu_921_p1;
wire   [26:0] mul_ln87_31_fu_921_p2;
wire  signed [15:0] mul_ln87_32_fu_931_p0;
wire  signed [10:0] mul_ln87_32_fu_931_p1;
wire   [26:0] mul_ln87_32_fu_931_p2;
wire  signed [15:0] mul_ln87_33_fu_941_p0;
wire  signed [27:0] sext_ln84_3_fu_394_p1;
wire   [11:0] mul_ln87_33_fu_941_p1;
wire   [27:0] mul_ln87_33_fu_941_p2;
wire  signed [15:0] mul_ln87_34_fu_951_p0;
wire   [10:0] mul_ln87_34_fu_951_p1;
wire   [26:0] mul_ln87_34_fu_951_p2;
wire  signed [15:0] mul_ln87_35_fu_961_p0;
wire  signed [11:0] mul_ln87_35_fu_961_p1;
wire   [27:0] mul_ln87_35_fu_961_p2;
wire  signed [15:0] mul_ln87_36_fu_971_p0;
wire  signed [11:0] mul_ln87_36_fu_971_p1;
wire   [27:0] mul_ln87_36_fu_971_p2;
wire  signed [15:0] mul_ln87_37_fu_981_p0;
wire   [11:0] mul_ln87_37_fu_981_p1;
wire   [27:0] mul_ln87_37_fu_981_p2;
wire  signed [15:0] mul_ln87_38_fu_991_p0;
wire   [11:0] mul_ln87_38_fu_991_p1;
wire   [27:0] mul_ln87_38_fu_991_p2;
wire  signed [15:0] mul_ln87_39_fu_1001_p0;
wire  signed [28:0] sext_ln84_2_fu_391_p1;
wire  signed [12:0] mul_ln87_39_fu_1001_p1;
wire   [28:0] mul_ln87_39_fu_1001_p2;
wire  signed [15:0] mul_ln87_40_fu_1011_p0;
wire  signed [11:0] mul_ln87_40_fu_1011_p1;
wire   [27:0] mul_ln87_40_fu_1011_p2;
wire  signed [15:0] mul_ln87_41_fu_1021_p0;
wire   [12:0] mul_ln87_41_fu_1021_p1;
wire   [28:0] mul_ln87_41_fu_1021_p2;
wire  signed [13:0] mul_ln87_42_fu_1031_p1;
wire   [29:0] mul_ln87_42_fu_1031_p2;
wire  signed [15:0] mul_ln87_43_fu_1041_p0;
wire  signed [11:0] mul_ln87_43_fu_1041_p1;
wire   [27:0] mul_ln87_43_fu_1041_p2;
wire  signed [15:0] mul_ln87_44_fu_1051_p0;
wire   [15:0] mul_ln87_44_fu_1051_p1;
wire  signed [30:0] sext_ln87_71_fu_1534_p0;
wire  signed [31:0] sext_ln87_71_fu_1534_p1;
wire  signed [29:0] sext_ln87_72_fu_1548_p0;
wire  signed [30:0] sext_ln87_72_fu_1548_p1;
wire  signed [30:0] sext_ln87_64_fu_572_p1;
wire  signed [28:0] sext_ln87_73_fu_1562_p0;
wire  signed [29:0] sext_ln87_73_fu_1562_p1;
wire  signed [29:0] sext_ln87_61_fu_541_p1;
wire  signed [27:0] sext_ln87_74_fu_1576_p0;
wire  signed [28:0] sext_ln87_74_fu_1576_p1;
wire  signed [28:0] sext_ln87_60_fu_527_p1;
wire  signed [26:0] sext_ln87_75_fu_1590_p0;
wire  signed [27:0] sext_ln87_75_fu_1590_p1;
wire  signed [27:0] sext_ln87_59_fu_517_p1;
wire  signed [25:0] sext_ln87_76_fu_1604_p0;
wire  signed [26:0] sext_ln87_76_fu_1604_p1;
wire  signed [26:0] sext_ln87_58_fu_507_p1;
wire  signed [25:0] sext_ln87_57_fu_497_p1;
wire  signed [24:0] sext_ln87_77_fu_1628_p0;
wire  signed [25:0] sext_ln87_77_fu_1628_p1;
wire  signed [25:0] sext_ln87_55_fu_476_p1;
wire  signed [24:0] sext_ln87_53_fu_466_p1;
wire  signed [22:0] sext_ln87_54_fu_1652_p0;
wire  signed [24:0] sext_ln87_54_fu_1652_p1;
wire   [31:0] add_ln84_fu_2014_p2;
wire  signed [31:0] sext_ln87_fu_2033_p1;
wire  signed [31:0] sext_ln87_2_fu_2042_p1;
wire  signed [31:0] sext_ln87_3_fu_2045_p1;
wire  signed [31:0] sext_ln87_4_fu_2048_p1;
wire  signed [31:0] sext_ln87_5_fu_2051_p1;
wire  signed [31:0] sext_ln87_6_fu_2054_p1;
wire  signed [31:0] sext_ln87_7_fu_2057_p1;
wire  signed [31:0] sext_ln87_9_fu_2060_p1;
wire   [15:0] grp_fu_2921_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 p_ZL10H_accu_FIR_0 = 32'd0;
#0 p_ZL10H_accu_FIR_1 = 32'd0;
#0 p_ZL10H_accu_FIR_2 = 32'd0;
#0 p_ZL10H_accu_FIR_3 = 32'd0;
#0 p_ZL10H_accu_FIR_4 = 32'd0;
#0 p_ZL10H_accu_FIR_5 = 32'd0;
#0 p_ZL10H_accu_FIR_6 = 32'd0;
#0 p_ZL10H_accu_FIR_7 = 32'd0;
#0 p_ZL10H_accu_FIR_8 = 32'd0;
#0 p_ZL10H_accu_FIR_9 = 32'd0;
#0 p_ZL10H_accu_FIR_10 = 32'd0;
#0 p_ZL10H_accu_FIR_11 = 32'd0;
#0 p_ZL10H_accu_FIR_12 = 32'd0;
#0 p_ZL10H_accu_FIR_13 = 32'd0;
#0 p_ZL10H_accu_FIR_14 = 32'd0;
#0 p_ZL10H_accu_FIR_15 = 32'd0;
#0 p_ZL10H_accu_FIR_16 = 32'd0;
#0 p_ZL10H_accu_FIR_17 = 32'd0;
#0 p_ZL10H_accu_FIR_18 = 32'd0;
#0 p_ZL10H_accu_FIR_19 = 32'd0;
#0 p_ZL10H_accu_FIR_20 = 32'd0;
#0 p_ZL10H_accu_FIR_21 = 32'd0;
#0 p_ZL10H_accu_FIR_22 = 32'd0;
#0 p_ZL10H_accu_FIR_23 = 32'd0;
#0 p_ZL10H_accu_FIR_24 = 32'd0;
#0 p_ZL10H_accu_FIR_25 = 32'd0;
#0 p_ZL10H_accu_FIR_26 = 32'd0;
#0 p_ZL10H_accu_FIR_27 = 32'd0;
#0 p_ZL10H_accu_FIR_28 = 32'd0;
#0 p_ZL10H_accu_FIR_29 = 32'd0;
#0 p_ZL10H_accu_FIR_30 = 32'd0;
#0 p_ZL10H_accu_FIR_31 = 32'd0;
#0 p_ZL10H_accu_FIR_32 = 32'd0;
#0 p_ZL10H_accu_FIR_33 = 32'd0;
#0 p_ZL10H_accu_FIR_34 = 32'd0;
#0 p_ZL10H_accu_FIR_35 = 32'd0;
#0 p_ZL10H_accu_FIR_36 = 32'd0;
#0 p_ZL10H_accu_FIR_37 = 32'd0;
#0 p_ZL10H_accu_FIR_38 = 32'd0;
#0 p_ZL10H_accu_FIR_39 = 32'd0;
#0 p_ZL10H_accu_FIR_40 = 32'd0;
#0 p_ZL10H_accu_FIR_41 = 32'd0;
#0 p_ZL10H_accu_FIR_42 = 32'd0;
#0 p_ZL10H_accu_FIR_43 = 32'd0;
#0 p_ZL10H_accu_FIR_44 = 32'd0;
#0 p_ZL10H_accu_FIR_45 = 32'd0;
#0 p_ZL10H_accu_FIR_46 = 32'd0;
#0 p_ZL10H_accu_FIR_47 = 32'd0;
#0 p_ZL10H_accu_FIR_48 = 32'd0;
#0 p_ZL10H_accu_FIR_49 = 32'd0;
#0 p_ZL10H_accu_FIR_50 = 32'd0;
#0 p_ZL10H_accu_FIR_51 = 32'd0;
#0 p_ZL10H_accu_FIR_52 = 32'd0;
#0 p_ZL10H_accu_FIR_53 = 32'd0;
#0 p_ZL10H_accu_FIR_54 = 32'd0;
#0 p_ZL10H_accu_FIR_55 = 32'd0;
#0 p_ZL10H_accu_FIR_56 = 32'd0;
#0 p_ZL10H_accu_FIR_57 = 32'd0;
#0 p_ZL10H_accu_FIR_58 = 32'd0;
#0 p_ZL10H_accu_FIR_59 = 32'd0;
#0 p_ZL10H_accu_FIR_60 = 32'd0;
#0 p_ZL10H_accu_FIR_61 = 32'd0;
#0 p_ZL10H_accu_FIR_62 = 32'd0;
#0 p_ZL10H_accu_FIR_63 = 32'd0;
#0 p_ZL10H_accu_FIR_64 = 32'd0;
#0 p_ZL10H_accu_FIR_65 = 32'd0;
#0 p_ZL10H_accu_FIR_66 = 32'd0;
#0 p_ZL10H_accu_FIR_67 = 32'd0;
#0 p_ZL10H_accu_FIR_68 = 32'd0;
#0 p_ZL10H_accu_FIR_69 = 32'd0;
#0 p_ZL10H_accu_FIR_70 = 32'd0;
#0 p_ZL10H_accu_FIR_71 = 32'd0;
#0 p_ZL10H_accu_FIR_72 = 32'd0;
#0 p_ZL10H_accu_FIR_73 = 32'd0;
#0 p_ZL10H_accu_FIR_74 = 32'd0;
#0 p_ZL10H_accu_FIR_75 = 32'd0;
#0 p_ZL10H_accu_FIR_76 = 32'd0;
#0 p_ZL10H_accu_FIR_77 = 32'd0;
#0 p_ZL10H_accu_FIR_78 = 32'd0;
#0 p_ZL10H_accu_FIR_79 = 32'd0;
#0 p_ZL10H_accu_FIR_80 = 32'd0;
#0 p_ZL10H_accu_FIR_81 = 32'd0;
#0 p_ZL10H_accu_FIR_82 = 32'd0;
#0 p_ZL10H_accu_FIR_83 = 32'd0;
#0 p_ZL10H_accu_FIR_84 = 32'd0;
#0 p_ZL10H_accu_FIR_85 = 32'd0;
#0 p_ZL10H_accu_FIR_86 = 32'd0;
#0 p_ZL10H_accu_FIR_87 = 32'd0;
#0 p_ZL10H_accu_FIR_88 = 32'd0;
#0 p_ZL10H_accu_FIR_89 = 32'd0;
#0 p_ZL10H_accu_FIR_90 = 32'd0;
#0 p_ZL10H_accu_FIR_91 = 32'd0;
#0 p_ZL10H_accu_FIR_92 = 32'd0;
#0 p_ZL10H_accu_FIR_93 = 32'd0;
#0 p_ZL10H_accu_FIR_94 = 32'd0;
#0 p_ZL10H_accu_FIR_95 = 32'd0;
#0 p_ZL10H_accu_FIR_96 = 32'd0;
#0 p_ZL10H_accu_FIR_97 = 32'd0;
#0 p_ZL10H_accu_FIR_98 = 32'd0;
#0 p_ZL10H_accu_FIR_99 = 32'd0;
#0 p_ZL10H_accu_FIR_100 = 32'd0;
#0 p_ZL10H_accu_FIR_101 = 32'd0;
#0 p_ZL10H_accu_FIR_102 = 32'd0;
#0 p_ZL10H_accu_FIR_103 = 32'd0;
#0 p_ZL10H_accu_FIR_104 = 32'd0;
#0 p_ZL10H_accu_FIR_105 = 32'd0;
#0 p_ZL10H_accu_FIR_106 = 31'd0;
#0 p_ZL10H_accu_FIR_107 = 30'd0;
#0 p_ZL10H_accu_FIR_108 = 29'd0;
#0 p_ZL10H_accu_FIR_109 = 28'd0;
#0 p_ZL10H_accu_FIR_110 = 27'd0;
#0 p_ZL10H_accu_FIR_111 = 26'd0;
#0 p_ZL10H_accu_FIR_112 = 26'd0;
#0 p_ZL10H_accu_FIR_113 = 25'd0;
#0 p_ZL10H_accu_FIR_114 = 25'd0;
#0 p_ZL10H_accu_FIR_115 = 23'd0;
end

Multirate_v2_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U31(
    .din0(mul_ln87_fu_443_p0),
    .din1(mul_ln87_fu_443_p1),
    .dout(mul_ln87_fu_443_p2)
);

Multirate_v2_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U32(
    .din0(mul_ln87_1_fu_470_p0),
    .din1(mul_ln87_1_fu_470_p1),
    .dout(mul_ln87_1_fu_470_p2)
);

Multirate_v2_mul_16s_8s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8s_24_1_1_U33(
    .din0(mul_ln87_2_fu_501_p0),
    .din1(mul_ln87_2_fu_501_p1),
    .dout(mul_ln87_2_fu_501_p2)
);

Multirate_v2_mul_16s_6ns_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 22 ))
mul_16s_6ns_22_1_1_U34(
    .din0(x_n_read_reg_2930_pp0_iter1_reg),
    .din1(mul_ln87_3_fu_511_p1),
    .dout(mul_ln87_3_fu_511_p2)
);

Multirate_v2_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U35(
    .din0(mul_ln87_4_fu_521_p0),
    .din1(mul_ln87_4_fu_521_p1),
    .dout(mul_ln87_4_fu_521_p2)
);

Multirate_v2_mul_16s_7s_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7s_23_1_1_U36(
    .din0(x_n_read_reg_2930_pp0_iter1_reg),
    .din1(mul_ln87_5_fu_531_p1),
    .dout(mul_ln87_5_fu_531_p2)
);

Multirate_v2_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U37(
    .din0(mul_ln87_6_fu_587_p0),
    .din1(mul_ln87_6_fu_587_p1),
    .dout(mul_ln87_6_fu_587_p2)
);

Multirate_v2_mul_16s_8s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8s_24_1_1_U38(
    .din0(mul_ln87_7_fu_597_p0),
    .din1(mul_ln87_7_fu_597_p1),
    .dout(mul_ln87_7_fu_597_p2)
);

Multirate_v2_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U39(
    .din0(mul_ln87_8_fu_607_p0),
    .din1(mul_ln87_8_fu_607_p1),
    .dout(mul_ln87_8_fu_607_p2)
);

Multirate_v2_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U40(
    .din0(mul_ln87_9_fu_617_p0),
    .din1(mul_ln87_9_fu_617_p1),
    .dout(mul_ln87_9_fu_617_p2)
);

Multirate_v2_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U41(
    .din0(mul_ln87_10_fu_627_p0),
    .din1(mul_ln87_10_fu_627_p1),
    .dout(mul_ln87_10_fu_627_p2)
);

Multirate_v2_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U42(
    .din0(mul_ln87_11_fu_637_p0),
    .din1(mul_ln87_11_fu_637_p1),
    .dout(mul_ln87_11_fu_637_p2)
);

Multirate_v2_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U43(
    .din0(mul_ln87_12_fu_647_p0),
    .din1(mul_ln87_12_fu_647_p1),
    .dout(mul_ln87_12_fu_647_p2)
);

Multirate_v2_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U44(
    .din0(mul_ln87_13_fu_657_p0),
    .din1(mul_ln87_13_fu_657_p1),
    .dout(mul_ln87_13_fu_657_p2)
);

Multirate_v2_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U45(
    .din0(mul_ln87_14_fu_667_p0),
    .din1(mul_ln87_14_fu_667_p1),
    .dout(mul_ln87_14_fu_667_p2)
);

Multirate_v2_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U46(
    .din0(mul_ln87_15_fu_698_p0),
    .din1(mul_ln87_15_fu_698_p1),
    .dout(mul_ln87_15_fu_698_p2)
);

Multirate_v2_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U47(
    .din0(mul_ln87_16_fu_726_p0),
    .din1(mul_ln87_16_fu_726_p1),
    .dout(mul_ln87_16_fu_726_p2)
);

Multirate_v2_mul_16s_8s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8s_24_1_1_U48(
    .din0(mul_ln87_17_fu_736_p0),
    .din1(mul_ln87_17_fu_736_p1),
    .dout(mul_ln87_17_fu_736_p2)
);

Multirate_v2_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U49(
    .din0(mul_ln87_18_fu_746_p0),
    .din1(mul_ln87_18_fu_746_p1),
    .dout(mul_ln87_18_fu_746_p2)
);

Multirate_v2_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U50(
    .din0(mul_ln87_19_fu_756_p0),
    .din1(mul_ln87_19_fu_756_p1),
    .dout(mul_ln87_19_fu_756_p2)
);

Multirate_v2_mul_16s_11ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11ns_27_1_1_U51(
    .din0(mul_ln87_20_fu_790_p0),
    .din1(mul_ln87_20_fu_790_p1),
    .dout(mul_ln87_20_fu_790_p2)
);

Multirate_v2_mul_16s_11s_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11s_27_1_1_U52(
    .din0(mul_ln87_21_fu_800_p0),
    .din1(mul_ln87_21_fu_800_p1),
    .dout(mul_ln87_21_fu_800_p2)
);

Multirate_v2_mul_16s_11ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11ns_27_1_1_U53(
    .din0(mul_ln87_22_fu_831_p0),
    .din1(mul_ln87_22_fu_831_p1),
    .dout(mul_ln87_22_fu_831_p2)
);

Multirate_v2_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U54(
    .din0(mul_ln87_23_fu_841_p0),
    .din1(mul_ln87_23_fu_841_p1),
    .dout(mul_ln87_23_fu_841_p2)
);

Multirate_v2_mul_16s_11s_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11s_27_1_1_U55(
    .din0(mul_ln87_24_fu_851_p0),
    .din1(mul_ln87_24_fu_851_p1),
    .dout(mul_ln87_24_fu_851_p2)
);

Multirate_v2_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U56(
    .din0(mul_ln87_25_fu_861_p0),
    .din1(mul_ln87_25_fu_861_p1),
    .dout(mul_ln87_25_fu_861_p2)
);

Multirate_v2_mul_16s_11ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11ns_27_1_1_U57(
    .din0(mul_ln87_26_fu_871_p0),
    .din1(mul_ln87_26_fu_871_p1),
    .dout(mul_ln87_26_fu_871_p2)
);

Multirate_v2_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U58(
    .din0(mul_ln87_27_fu_881_p0),
    .din1(mul_ln87_27_fu_881_p1),
    .dout(mul_ln87_27_fu_881_p2)
);

Multirate_v2_mul_16s_11s_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11s_27_1_1_U59(
    .din0(mul_ln87_28_fu_891_p0),
    .din1(mul_ln87_28_fu_891_p1),
    .dout(mul_ln87_28_fu_891_p2)
);

Multirate_v2_mul_16s_11ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11ns_27_1_1_U60(
    .din0(mul_ln87_29_fu_901_p0),
    .din1(mul_ln87_29_fu_901_p1),
    .dout(mul_ln87_29_fu_901_p2)
);

Multirate_v2_mul_16s_11ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11ns_27_1_1_U61(
    .din0(mul_ln87_30_fu_911_p0),
    .din1(mul_ln87_30_fu_911_p1),
    .dout(mul_ln87_30_fu_911_p2)
);

Multirate_v2_mul_16s_11s_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11s_27_1_1_U62(
    .din0(mul_ln87_31_fu_921_p0),
    .din1(mul_ln87_31_fu_921_p1),
    .dout(mul_ln87_31_fu_921_p2)
);

Multirate_v2_mul_16s_11s_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11s_27_1_1_U63(
    .din0(mul_ln87_32_fu_931_p0),
    .din1(mul_ln87_32_fu_931_p1),
    .dout(mul_ln87_32_fu_931_p2)
);

Multirate_v2_mul_16s_12ns_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 28 ))
mul_16s_12ns_28_1_1_U64(
    .din0(mul_ln87_33_fu_941_p0),
    .din1(mul_ln87_33_fu_941_p1),
    .dout(mul_ln87_33_fu_941_p2)
);

Multirate_v2_mul_16s_11ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11ns_27_1_1_U65(
    .din0(mul_ln87_34_fu_951_p0),
    .din1(mul_ln87_34_fu_951_p1),
    .dout(mul_ln87_34_fu_951_p2)
);

Multirate_v2_mul_16s_12s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 28 ))
mul_16s_12s_28_1_1_U66(
    .din0(mul_ln87_35_fu_961_p0),
    .din1(mul_ln87_35_fu_961_p1),
    .dout(mul_ln87_35_fu_961_p2)
);

Multirate_v2_mul_16s_12s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 28 ))
mul_16s_12s_28_1_1_U67(
    .din0(mul_ln87_36_fu_971_p0),
    .din1(mul_ln87_36_fu_971_p1),
    .dout(mul_ln87_36_fu_971_p2)
);

Multirate_v2_mul_16s_12ns_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 28 ))
mul_16s_12ns_28_1_1_U68(
    .din0(mul_ln87_37_fu_981_p0),
    .din1(mul_ln87_37_fu_981_p1),
    .dout(mul_ln87_37_fu_981_p2)
);

Multirate_v2_mul_16s_12ns_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 28 ))
mul_16s_12ns_28_1_1_U69(
    .din0(mul_ln87_38_fu_991_p0),
    .din1(mul_ln87_38_fu_991_p1),
    .dout(mul_ln87_38_fu_991_p2)
);

Multirate_v2_mul_16s_13s_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mul_16s_13s_29_1_1_U70(
    .din0(mul_ln87_39_fu_1001_p0),
    .din1(mul_ln87_39_fu_1001_p1),
    .dout(mul_ln87_39_fu_1001_p2)
);

Multirate_v2_mul_16s_12s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 28 ))
mul_16s_12s_28_1_1_U71(
    .din0(mul_ln87_40_fu_1011_p0),
    .din1(mul_ln87_40_fu_1011_p1),
    .dout(mul_ln87_40_fu_1011_p2)
);

Multirate_v2_mul_16s_13ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 29 ))
mul_16s_13ns_29_1_1_U72(
    .din0(mul_ln87_41_fu_1021_p0),
    .din1(mul_ln87_41_fu_1021_p1),
    .dout(mul_ln87_41_fu_1021_p2)
);

Multirate_v2_mul_16s_14s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 30 ))
mul_16s_14s_30_1_1_U73(
    .din0(x_n_read_reg_2930_pp0_iter1_reg),
    .din1(mul_ln87_42_fu_1031_p1),
    .dout(mul_ln87_42_fu_1031_p2)
);

Multirate_v2_mul_16s_12s_28_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 28 ))
mul_16s_12s_28_1_1_U74(
    .din0(mul_ln87_43_fu_1041_p0),
    .din1(mul_ln87_43_fu_1041_p1),
    .dout(mul_ln87_43_fu_1041_p2)
);

Multirate_v2_mul_16s_16ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_16s_16ns_32_1_1_U75(
    .din0(mul_ln87_44_fu_1051_p0),
    .din1(mul_ln87_44_fu_1051_p1),
    .dout(mul_ln87_44_fu_1051_p2)
);

Multirate_v2_mac_muladd_16s_16ns_32ns_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16ns_32ns_32_4_1_U76(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sext_ln84_fu_384_p0),
    .din1(grp_fu_2921_p1),
    .din2(p_ZL10H_accu_FIR_58),
    .ce(1'b1),
    .dout(grp_fu_2921_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        mul_ln87_1_reg_2973 <= mul_ln87_1_fu_470_p2;
        mul_ln87_2_reg_2983 <= mul_ln87_2_fu_501_p2;
        mul_ln87_3_reg_2988 <= mul_ln87_3_fu_511_p2;
        mul_ln87_44_reg_3226 <= mul_ln87_44_fu_1051_p2;
        mul_ln87_4_reg_2993 <= mul_ln87_4_fu_521_p2;
        mul_ln87_reg_2963 <= mul_ln87_fu_443_p2;
        sext_ln84_10_reg_2957[31 : 2] <= sext_ln84_10_fu_439_p1[31 : 2];
        sext_ln87_10_reg_3009[31 : 6] <= sext_ln87_10_fu_583_p1[31 : 6];
        sext_ln87_11_reg_3015 <= sext_ln87_11_fu_593_p1;
        sext_ln87_12_reg_3020 <= sext_ln87_12_fu_603_p1;
        sext_ln87_13_reg_3025 <= sext_ln87_13_fu_613_p1;
        sext_ln87_14_reg_3030 <= sext_ln87_14_fu_623_p1;
        sext_ln87_15_reg_3035 <= sext_ln87_15_fu_633_p1;
        sext_ln87_16_reg_3040 <= sext_ln87_16_fu_643_p1;
        sext_ln87_17_reg_3045 <= sext_ln87_17_fu_653_p1;
        sext_ln87_18_reg_3050 <= sext_ln87_18_fu_663_p1;
        sext_ln87_19_reg_3055 <= sext_ln87_19_fu_673_p1;
        sext_ln87_20_reg_3060[31 : 4] <= sext_ln87_20_fu_694_p1[31 : 4];
        sext_ln87_21_reg_3065 <= sext_ln87_21_fu_704_p1;
        sext_ln87_22_reg_3070[31 : 1] <= sext_ln87_22_fu_722_p1[31 : 1];
        sext_ln87_23_reg_3075 <= sext_ln87_23_fu_732_p1;
        sext_ln87_24_reg_3080 <= sext_ln87_24_fu_742_p1;
        sext_ln87_25_reg_3085 <= sext_ln87_25_fu_752_p1;
        sext_ln87_26_reg_3090 <= sext_ln87_26_fu_762_p1;
        sext_ln87_27_reg_3095[31 : 1] <= sext_ln87_27_fu_786_p1[31 : 1];
        sext_ln87_28_reg_3100 <= sext_ln87_28_fu_796_p1;
        sext_ln87_29_reg_3105 <= sext_ln87_29_fu_806_p1;
        sext_ln87_30_reg_3110[31 : 3] <= sext_ln87_30_fu_827_p1[31 : 3];
        sext_ln87_31_reg_3115 <= sext_ln87_31_fu_837_p1;
        sext_ln87_32_reg_3120 <= sext_ln87_32_fu_847_p1;
        sext_ln87_33_reg_3125 <= sext_ln87_33_fu_857_p1;
        sext_ln87_34_reg_3130 <= sext_ln87_34_fu_867_p1;
        sext_ln87_35_reg_3135 <= sext_ln87_35_fu_877_p1;
        sext_ln87_36_reg_3140 <= sext_ln87_36_fu_887_p1;
        sext_ln87_37_reg_3145 <= sext_ln87_37_fu_897_p1;
        sext_ln87_38_reg_3150 <= sext_ln87_38_fu_907_p1;
        sext_ln87_39_reg_3155 <= sext_ln87_39_fu_917_p1;
        sext_ln87_40_reg_3160 <= sext_ln87_40_fu_927_p1;
        sext_ln87_41_reg_3165 <= sext_ln87_41_fu_937_p1;
        sext_ln87_42_reg_3170 <= sext_ln87_42_fu_947_p1;
        sext_ln87_43_reg_3176 <= sext_ln87_43_fu_957_p1;
        sext_ln87_44_reg_3181 <= sext_ln87_44_fu_967_p1;
        sext_ln87_45_reg_3186 <= sext_ln87_45_fu_977_p1;
        sext_ln87_46_reg_3191 <= sext_ln87_46_fu_987_p1;
        sext_ln87_47_reg_3196 <= sext_ln87_47_fu_997_p1;
        sext_ln87_48_reg_3201 <= sext_ln87_48_fu_1007_p1;
        sext_ln87_49_reg_3206 <= sext_ln87_49_fu_1017_p1;
        sext_ln87_50_reg_3211 <= sext_ln87_50_fu_1027_p1;
        sext_ln87_51_reg_3216 <= sext_ln87_51_fu_1037_p1;
        sext_ln87_52_reg_3221 <= sext_ln87_52_fu_1047_p1;
        sext_ln87_8_reg_2998 <= sext_ln87_8_fu_537_p1;
        sub_ln87_1_reg_2978[21 : 5] <= sub_ln87_1_fu_491_p2[21 : 5];
        sub_ln87_3_reg_3004[24 : 1] <= sub_ln87_3_fu_566_p2[24 : 1];
        tmp_reg_2968[17 : 1] <= tmp_fu_458_p3[17 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_ZL10H_accu_FIR_0 <= add_ln87_fu_2036_p2;
        p_ZL10H_accu_FIR_1 <= add_ln87_1_fu_2067_p2;
        p_ZL10H_accu_FIR_10 <= add_ln87_10_fu_2155_p2;
        p_ZL10H_accu_FIR_11 <= add_ln87_11_fu_2164_p2;
        p_ZL10H_accu_FIR_12 <= add_ln87_12_fu_2173_p2;
        p_ZL10H_accu_FIR_13 <= add_ln87_13_fu_2182_p2;
        p_ZL10H_accu_FIR_14 <= add_ln87_14_fu_2191_p2;
        p_ZL10H_accu_FIR_15 <= add_ln87_15_fu_2200_p2;
        p_ZL10H_accu_FIR_16 <= add_ln87_16_fu_2209_p2;
        p_ZL10H_accu_FIR_17 <= add_ln87_17_fu_2218_p2;
        p_ZL10H_accu_FIR_18 <= add_ln87_18_fu_2227_p2;
        p_ZL10H_accu_FIR_19 <= add_ln87_19_fu_2236_p2;
        p_ZL10H_accu_FIR_2 <= add_ln87_2_fu_2077_p2;
        p_ZL10H_accu_FIR_20 <= add_ln87_20_fu_2245_p2;
        p_ZL10H_accu_FIR_21 <= add_ln87_21_fu_2254_p2;
        p_ZL10H_accu_FIR_22 <= add_ln87_22_fu_2263_p2;
        p_ZL10H_accu_FIR_23 <= add_ln87_23_fu_2272_p2;
        p_ZL10H_accu_FIR_24 <= add_ln87_24_fu_2281_p2;
        p_ZL10H_accu_FIR_25 <= add_ln87_25_fu_2290_p2;
        p_ZL10H_accu_FIR_26 <= add_ln87_26_fu_2299_p2;
        p_ZL10H_accu_FIR_27 <= add_ln87_27_fu_2308_p2;
        p_ZL10H_accu_FIR_28 <= add_ln87_28_fu_2317_p2;
        p_ZL10H_accu_FIR_29 <= add_ln87_29_fu_2326_p2;
        p_ZL10H_accu_FIR_3 <= add_ln87_3_fu_2087_p2;
        p_ZL10H_accu_FIR_30 <= add_ln87_30_fu_2335_p2;
        p_ZL10H_accu_FIR_31 <= add_ln87_31_fu_2344_p2;
        p_ZL10H_accu_FIR_32 <= add_ln87_32_fu_2353_p2;
        p_ZL10H_accu_FIR_33 <= add_ln87_33_fu_2362_p2;
        p_ZL10H_accu_FIR_34 <= add_ln87_34_fu_2371_p2;
        p_ZL10H_accu_FIR_35 <= add_ln87_35_fu_2380_p2;
        p_ZL10H_accu_FIR_36 <= add_ln87_36_fu_2389_p2;
        p_ZL10H_accu_FIR_37 <= add_ln87_37_fu_2398_p2;
        p_ZL10H_accu_FIR_38 <= add_ln87_38_fu_2407_p2;
        p_ZL10H_accu_FIR_39 <= add_ln87_39_fu_2416_p2;
        p_ZL10H_accu_FIR_4 <= add_ln87_4_fu_2097_p2;
        p_ZL10H_accu_FIR_40 <= add_ln87_40_fu_2425_p2;
        p_ZL10H_accu_FIR_41 <= add_ln87_41_fu_2434_p2;
        p_ZL10H_accu_FIR_42 <= add_ln87_42_fu_2443_p2;
        p_ZL10H_accu_FIR_43 <= add_ln87_43_fu_2452_p2;
        p_ZL10H_accu_FIR_44 <= add_ln87_44_fu_2461_p2;
        p_ZL10H_accu_FIR_45 <= add_ln87_45_fu_2470_p2;
        p_ZL10H_accu_FIR_46 <= add_ln87_46_fu_2479_p2;
        p_ZL10H_accu_FIR_47 <= add_ln87_47_fu_2488_p2;
        p_ZL10H_accu_FIR_48 <= add_ln87_48_fu_2497_p2;
        p_ZL10H_accu_FIR_49 <= add_ln87_49_fu_2506_p2;
        p_ZL10H_accu_FIR_5 <= add_ln87_5_fu_2107_p2;
        p_ZL10H_accu_FIR_50 <= add_ln87_50_fu_2515_p2;
        p_ZL10H_accu_FIR_51 <= add_ln87_51_fu_2524_p2;
        p_ZL10H_accu_FIR_52 <= add_ln87_52_fu_2533_p2;
        p_ZL10H_accu_FIR_53 <= add_ln87_53_fu_2542_p2;
        p_ZL10H_accu_FIR_54 <= add_ln87_54_fu_2551_p2;
        p_ZL10H_accu_FIR_55 <= add_ln87_55_fu_2560_p2;
        p_ZL10H_accu_FIR_56 <= add_ln87_56_fu_2569_p2;
        p_ZL10H_accu_FIR_57 <= grp_fu_2921_p3;
        p_ZL10H_accu_FIR_6 <= add_ln87_6_fu_2117_p2;
        p_ZL10H_accu_FIR_7 <= add_ln87_7_fu_2127_p2;
        p_ZL10H_accu_FIR_8 <= add_ln87_8_fu_2136_p2;
        p_ZL10H_accu_FIR_9 <= add_ln87_9_fu_2146_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZL10H_accu_FIR_100 <= add_ln87_100_fu_1484_p2;
        p_ZL10H_accu_FIR_101 <= add_ln87_101_fu_1494_p2;
        p_ZL10H_accu_FIR_102 <= add_ln87_102_fu_1504_p2;
        p_ZL10H_accu_FIR_103 <= add_ln87_103_fu_1514_p2;
        p_ZL10H_accu_FIR_104 <= add_ln87_104_fu_1524_p2;
        p_ZL10H_accu_FIR_105 <= add_ln87_105_fu_1538_p2;
        p_ZL10H_accu_FIR_106 <= add_ln87_106_fu_1552_p2;
        p_ZL10H_accu_FIR_107 <= add_ln87_107_fu_1566_p2;
        p_ZL10H_accu_FIR_108 <= add_ln87_108_fu_1580_p2;
        p_ZL10H_accu_FIR_109 <= add_ln87_109_fu_1594_p2;
        p_ZL10H_accu_FIR_110 <= add_ln87_110_fu_1608_p2;
        p_ZL10H_accu_FIR_111 <= add_ln87_111_fu_1618_p2;
        p_ZL10H_accu_FIR_112 <= add_ln87_112_fu_1632_p2;
        p_ZL10H_accu_FIR_113 <= add_ln87_113_fu_1642_p2;
        p_ZL10H_accu_FIR_114 <= add_ln87_114_fu_1656_p2;
        p_ZL10H_accu_FIR_115[22 : 2] <= sub_ln84_fu_433_p2[22 : 2];
        p_ZL10H_accu_FIR_58 <= add_ln87_58_fu_1064_p2;
        p_ZL10H_accu_FIR_59 <= add_ln87_59_fu_1074_p2;
        p_ZL10H_accu_FIR_60 <= add_ln87_60_fu_1084_p2;
        p_ZL10H_accu_FIR_61 <= add_ln87_61_fu_1094_p2;
        p_ZL10H_accu_FIR_62 <= add_ln87_62_fu_1104_p2;
        p_ZL10H_accu_FIR_63 <= add_ln87_63_fu_1114_p2;
        p_ZL10H_accu_FIR_64 <= add_ln87_64_fu_1124_p2;
        p_ZL10H_accu_FIR_65 <= add_ln87_65_fu_1134_p2;
        p_ZL10H_accu_FIR_66 <= add_ln87_66_fu_1144_p2;
        p_ZL10H_accu_FIR_67 <= add_ln87_67_fu_1154_p2;
        p_ZL10H_accu_FIR_68 <= add_ln87_68_fu_1164_p2;
        p_ZL10H_accu_FIR_69 <= add_ln87_69_fu_1174_p2;
        p_ZL10H_accu_FIR_70 <= add_ln87_70_fu_1184_p2;
        p_ZL10H_accu_FIR_71 <= add_ln87_71_fu_1194_p2;
        p_ZL10H_accu_FIR_72 <= add_ln87_72_fu_1204_p2;
        p_ZL10H_accu_FIR_73 <= add_ln87_73_fu_1214_p2;
        p_ZL10H_accu_FIR_74 <= add_ln87_74_fu_1224_p2;
        p_ZL10H_accu_FIR_75 <= add_ln87_75_fu_1234_p2;
        p_ZL10H_accu_FIR_76 <= add_ln87_76_fu_1244_p2;
        p_ZL10H_accu_FIR_77 <= add_ln87_77_fu_1254_p2;
        p_ZL10H_accu_FIR_78 <= add_ln87_78_fu_1264_p2;
        p_ZL10H_accu_FIR_79 <= add_ln87_79_fu_1274_p2;
        p_ZL10H_accu_FIR_80 <= add_ln87_80_fu_1284_p2;
        p_ZL10H_accu_FIR_81 <= add_ln87_81_fu_1294_p2;
        p_ZL10H_accu_FIR_82 <= add_ln87_82_fu_1304_p2;
        p_ZL10H_accu_FIR_83 <= add_ln87_83_fu_1314_p2;
        p_ZL10H_accu_FIR_84 <= add_ln87_84_fu_1324_p2;
        p_ZL10H_accu_FIR_85 <= add_ln87_85_fu_1334_p2;
        p_ZL10H_accu_FIR_86 <= add_ln87_86_fu_1344_p2;
        p_ZL10H_accu_FIR_87 <= add_ln87_87_fu_1354_p2;
        p_ZL10H_accu_FIR_88 <= add_ln87_88_fu_1364_p2;
        p_ZL10H_accu_FIR_89 <= add_ln87_89_fu_1374_p2;
        p_ZL10H_accu_FIR_90 <= add_ln87_90_fu_1384_p2;
        p_ZL10H_accu_FIR_91 <= add_ln87_91_fu_1394_p2;
        p_ZL10H_accu_FIR_92 <= add_ln87_92_fu_1404_p2;
        p_ZL10H_accu_FIR_93 <= add_ln87_93_fu_1414_p2;
        p_ZL10H_accu_FIR_94 <= add_ln87_94_fu_1424_p2;
        p_ZL10H_accu_FIR_95 <= add_ln87_95_fu_1434_p2;
        p_ZL10H_accu_FIR_96 <= add_ln87_96_fu_1444_p2;
        p_ZL10H_accu_FIR_97 <= add_ln87_97_fu_1454_p2;
        p_ZL10H_accu_FIR_98 <= add_ln87_98_fu_1464_p2;
        p_ZL10H_accu_FIR_99 <= add_ln87_99_fu_1474_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sext_ln84_reg_2951 <= sext_ln84_fu_384_p1;
        sext_ln84_reg_2951_pp0_iter1_reg <= sext_ln84_reg_2951;
        x_n_read_reg_2930 <= x_n;
        x_n_read_reg_2930_pp0_iter1_reg <= x_n_read_reg_2930;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln84_fu_2014_p2 = ($signed(sext_ln84_10_reg_2957) + $signed(p_ZL10H_accu_FIR_0));

assign add_ln87_100_fu_1484_p2 = ($signed(p_ZL10H_accu_FIR_101) + $signed(sext_ln87_14_fu_623_p1));

assign add_ln87_101_fu_1494_p2 = ($signed(p_ZL10H_accu_FIR_102) + $signed(sext_ln84_10_fu_439_p1));

assign add_ln87_102_fu_1504_p2 = ($signed(p_ZL10H_accu_FIR_103) + $signed(sext_ln87_13_fu_613_p1));

assign add_ln87_103_fu_1514_p2 = ($signed(p_ZL10H_accu_FIR_104) + $signed(sext_ln87_12_fu_603_p1));

assign add_ln87_104_fu_1524_p2 = ($signed(p_ZL10H_accu_FIR_105) + $signed(sext_ln87_11_fu_593_p1));

assign add_ln87_105_fu_1538_p2 = ($signed(sext_ln87_71_fu_1534_p1) + $signed(sext_ln87_10_fu_583_p1));

assign add_ln87_106_fu_1552_p2 = ($signed(sext_ln87_72_fu_1548_p1) + $signed(sext_ln87_64_fu_572_p1));

assign add_ln87_107_fu_1566_p2 = ($signed(sext_ln87_73_fu_1562_p1) + $signed(sext_ln87_61_fu_541_p1));

assign add_ln87_108_fu_1580_p2 = ($signed(sext_ln87_74_fu_1576_p1) + $signed(sext_ln87_60_fu_527_p1));

assign add_ln87_109_fu_1594_p2 = ($signed(sext_ln87_75_fu_1590_p1) + $signed(sext_ln87_59_fu_517_p1));

assign add_ln87_10_fu_2155_p2 = ($signed(p_ZL10H_accu_FIR_11) + $signed(sext_ln87_11_reg_3015));

assign add_ln87_110_fu_1608_p2 = ($signed(sext_ln87_76_fu_1604_p1) + $signed(sext_ln87_58_fu_507_p1));

assign add_ln87_111_fu_1618_p2 = ($signed(p_ZL10H_accu_FIR_112) + $signed(sext_ln87_57_fu_497_p1));

assign add_ln87_112_fu_1632_p2 = ($signed(sext_ln87_77_fu_1628_p1) + $signed(sext_ln87_55_fu_476_p1));

assign add_ln87_113_fu_1642_p2 = ($signed(p_ZL10H_accu_FIR_114) + $signed(sext_ln87_53_fu_466_p1));

assign add_ln87_114_fu_1656_p2 = ($signed(sext_ln87_54_fu_1652_p1) + $signed(mul_ln87_fu_443_p2));

assign add_ln87_11_fu_2164_p2 = ($signed(p_ZL10H_accu_FIR_12) + $signed(sext_ln87_12_reg_3020));

assign add_ln87_12_fu_2173_p2 = ($signed(p_ZL10H_accu_FIR_13) + $signed(sext_ln87_13_reg_3025));

assign add_ln87_13_fu_2182_p2 = ($signed(p_ZL10H_accu_FIR_14) + $signed(sext_ln84_10_reg_2957));

assign add_ln87_14_fu_2191_p2 = ($signed(p_ZL10H_accu_FIR_15) + $signed(sext_ln87_14_reg_3030));

assign add_ln87_15_fu_2200_p2 = ($signed(p_ZL10H_accu_FIR_16) + $signed(sext_ln87_15_reg_3035));

assign add_ln87_16_fu_2209_p2 = ($signed(p_ZL10H_accu_FIR_17) + $signed(sext_ln87_16_reg_3040));

assign add_ln87_17_fu_2218_p2 = ($signed(p_ZL10H_accu_FIR_18) + $signed(sext_ln87_17_reg_3045));

assign add_ln87_18_fu_2227_p2 = ($signed(p_ZL10H_accu_FIR_19) + $signed(sext_ln87_18_reg_3050));

assign add_ln87_19_fu_2236_p2 = ($signed(p_ZL10H_accu_FIR_20) + $signed(sext_ln87_19_reg_3055));

assign add_ln87_1_fu_2067_p2 = ($signed(p_ZL10H_accu_FIR_2) + $signed(sext_ln87_2_fu_2042_p1));

assign add_ln87_20_fu_2245_p2 = ($signed(p_ZL10H_accu_FIR_21) + $signed(sext_ln87_20_reg_3060));

assign add_ln87_21_fu_2254_p2 = ($signed(p_ZL10H_accu_FIR_22) + $signed(sext_ln87_21_reg_3065));

assign add_ln87_22_fu_2263_p2 = ($signed(p_ZL10H_accu_FIR_23) + $signed(sext_ln87_22_reg_3070));

assign add_ln87_23_fu_2272_p2 = ($signed(p_ZL10H_accu_FIR_24) + $signed(sext_ln87_23_reg_3075));

assign add_ln87_24_fu_2281_p2 = ($signed(p_ZL10H_accu_FIR_25) + $signed(sext_ln87_24_reg_3080));

assign add_ln87_25_fu_2290_p2 = ($signed(p_ZL10H_accu_FIR_26) + $signed(sext_ln87_25_reg_3085));

assign add_ln87_26_fu_2299_p2 = ($signed(p_ZL10H_accu_FIR_27) + $signed(sext_ln87_10_reg_3009));

assign add_ln87_27_fu_2308_p2 = ($signed(p_ZL10H_accu_FIR_28) + $signed(sext_ln87_26_reg_3090));

assign add_ln87_28_fu_2317_p2 = ($signed(p_ZL10H_accu_FIR_29) + $signed(sext_ln87_27_reg_3095));

assign add_ln87_29_fu_2326_p2 = ($signed(p_ZL10H_accu_FIR_30) + $signed(sext_ln87_28_reg_3100));

assign add_ln87_2_fu_2077_p2 = ($signed(p_ZL10H_accu_FIR_3) + $signed(sext_ln87_3_fu_2045_p1));

assign add_ln87_30_fu_2335_p2 = ($signed(p_ZL10H_accu_FIR_31) + $signed(sext_ln87_8_reg_2998));

assign add_ln87_31_fu_2344_p2 = ($signed(p_ZL10H_accu_FIR_32) + $signed(sext_ln87_29_reg_3105));

assign add_ln87_32_fu_2353_p2 = ($signed(p_ZL10H_accu_FIR_33) + $signed(sext_ln87_30_reg_3110));

assign add_ln87_33_fu_2362_p2 = ($signed(p_ZL10H_accu_FIR_34) + $signed(sext_ln87_31_reg_3115));

assign add_ln87_34_fu_2371_p2 = ($signed(p_ZL10H_accu_FIR_35) + $signed(sext_ln87_32_reg_3120));

assign add_ln87_35_fu_2380_p2 = ($signed(p_ZL10H_accu_FIR_36) + $signed(sext_ln87_33_reg_3125));

assign add_ln87_36_fu_2389_p2 = ($signed(p_ZL10H_accu_FIR_37) + $signed(sext_ln87_34_reg_3130));

assign add_ln87_37_fu_2398_p2 = ($signed(p_ZL10H_accu_FIR_38) + $signed(sext_ln87_35_reg_3135));

assign add_ln87_38_fu_2407_p2 = ($signed(p_ZL10H_accu_FIR_39) + $signed(sext_ln87_36_reg_3140));

assign add_ln87_39_fu_2416_p2 = ($signed(p_ZL10H_accu_FIR_40) + $signed(sext_ln87_37_reg_3145));

assign add_ln87_3_fu_2087_p2 = ($signed(p_ZL10H_accu_FIR_4) + $signed(sext_ln87_4_fu_2048_p1));

assign add_ln87_40_fu_2425_p2 = ($signed(p_ZL10H_accu_FIR_41) + $signed(sext_ln87_38_reg_3150));

assign add_ln87_41_fu_2434_p2 = ($signed(p_ZL10H_accu_FIR_42) + $signed(sext_ln87_39_reg_3155));

assign add_ln87_42_fu_2443_p2 = ($signed(p_ZL10H_accu_FIR_43) + $signed(sext_ln87_40_reg_3160));

assign add_ln87_43_fu_2452_p2 = ($signed(p_ZL10H_accu_FIR_44) + $signed(sext_ln87_41_reg_3165));

assign add_ln87_44_fu_2461_p2 = ($signed(p_ZL10H_accu_FIR_45) + $signed(sext_ln87_42_reg_3170));

assign add_ln87_45_fu_2470_p2 = ($signed(p_ZL10H_accu_FIR_46) + $signed(sext_ln87_43_reg_3176));

assign add_ln87_46_fu_2479_p2 = ($signed(p_ZL10H_accu_FIR_47) + $signed(sext_ln87_44_reg_3181));

assign add_ln87_47_fu_2488_p2 = ($signed(p_ZL10H_accu_FIR_48) + $signed(sext_ln87_45_reg_3186));

assign add_ln87_48_fu_2497_p2 = ($signed(p_ZL10H_accu_FIR_49) + $signed(sext_ln87_46_reg_3191));

assign add_ln87_49_fu_2506_p2 = ($signed(p_ZL10H_accu_FIR_50) + $signed(sext_ln87_47_reg_3196));

assign add_ln87_4_fu_2097_p2 = ($signed(p_ZL10H_accu_FIR_5) + $signed(sext_ln87_5_fu_2051_p1));

assign add_ln87_50_fu_2515_p2 = ($signed(p_ZL10H_accu_FIR_51) + $signed(sext_ln87_48_reg_3201));

assign add_ln87_51_fu_2524_p2 = ($signed(p_ZL10H_accu_FIR_52) + $signed(sext_ln87_49_reg_3206));

assign add_ln87_52_fu_2533_p2 = ($signed(p_ZL10H_accu_FIR_53) + $signed(sext_ln87_50_reg_3211));

assign add_ln87_53_fu_2542_p2 = ($signed(p_ZL10H_accu_FIR_54) + $signed(sext_ln87_42_reg_3170));

assign add_ln87_54_fu_2551_p2 = ($signed(p_ZL10H_accu_FIR_55) + $signed(sext_ln87_51_reg_3216));

assign add_ln87_55_fu_2560_p2 = ($signed(p_ZL10H_accu_FIR_56) + $signed(sext_ln87_52_reg_3221));

assign add_ln87_56_fu_2569_p2 = (p_ZL10H_accu_FIR_57 + mul_ln87_44_reg_3226);

assign add_ln87_58_fu_1064_p2 = (p_ZL10H_accu_FIR_59 + mul_ln87_44_fu_1051_p2);

assign add_ln87_59_fu_1074_p2 = ($signed(p_ZL10H_accu_FIR_60) + $signed(sext_ln87_52_fu_1047_p1));

assign add_ln87_5_fu_2107_p2 = ($signed(p_ZL10H_accu_FIR_6) + $signed(sext_ln87_6_fu_2054_p1));

assign add_ln87_60_fu_1084_p2 = ($signed(p_ZL10H_accu_FIR_61) + $signed(sext_ln87_51_fu_1037_p1));

assign add_ln87_61_fu_1094_p2 = ($signed(p_ZL10H_accu_FIR_62) + $signed(sext_ln87_42_fu_947_p1));

assign add_ln87_62_fu_1104_p2 = ($signed(p_ZL10H_accu_FIR_63) + $signed(sext_ln87_50_fu_1027_p1));

assign add_ln87_63_fu_1114_p2 = ($signed(p_ZL10H_accu_FIR_64) + $signed(sext_ln87_49_fu_1017_p1));

assign add_ln87_64_fu_1124_p2 = ($signed(p_ZL10H_accu_FIR_65) + $signed(sext_ln87_48_fu_1007_p1));

assign add_ln87_65_fu_1134_p2 = ($signed(p_ZL10H_accu_FIR_66) + $signed(sext_ln87_47_fu_997_p1));

assign add_ln87_66_fu_1144_p2 = ($signed(p_ZL10H_accu_FIR_67) + $signed(sext_ln87_46_fu_987_p1));

assign add_ln87_67_fu_1154_p2 = ($signed(p_ZL10H_accu_FIR_68) + $signed(sext_ln87_45_fu_977_p1));

assign add_ln87_68_fu_1164_p2 = ($signed(p_ZL10H_accu_FIR_69) + $signed(sext_ln87_44_fu_967_p1));

assign add_ln87_69_fu_1174_p2 = ($signed(p_ZL10H_accu_FIR_70) + $signed(sext_ln87_43_fu_957_p1));

assign add_ln87_6_fu_2117_p2 = ($signed(p_ZL10H_accu_FIR_7) + $signed(sext_ln87_7_fu_2057_p1));

assign add_ln87_70_fu_1184_p2 = ($signed(p_ZL10H_accu_FIR_71) + $signed(sext_ln87_42_fu_947_p1));

assign add_ln87_71_fu_1194_p2 = ($signed(p_ZL10H_accu_FIR_72) + $signed(sext_ln87_41_fu_937_p1));

assign add_ln87_72_fu_1204_p2 = ($signed(p_ZL10H_accu_FIR_73) + $signed(sext_ln87_40_fu_927_p1));

assign add_ln87_73_fu_1214_p2 = ($signed(p_ZL10H_accu_FIR_74) + $signed(sext_ln87_39_fu_917_p1));

assign add_ln87_74_fu_1224_p2 = ($signed(p_ZL10H_accu_FIR_75) + $signed(sext_ln87_38_fu_907_p1));

assign add_ln87_75_fu_1234_p2 = ($signed(p_ZL10H_accu_FIR_76) + $signed(sext_ln87_37_fu_897_p1));

assign add_ln87_76_fu_1244_p2 = ($signed(p_ZL10H_accu_FIR_77) + $signed(sext_ln87_36_fu_887_p1));

assign add_ln87_77_fu_1254_p2 = ($signed(p_ZL10H_accu_FIR_78) + $signed(sext_ln87_35_fu_877_p1));

assign add_ln87_78_fu_1264_p2 = ($signed(p_ZL10H_accu_FIR_79) + $signed(sext_ln87_34_fu_867_p1));

assign add_ln87_79_fu_1274_p2 = ($signed(p_ZL10H_accu_FIR_80) + $signed(sext_ln87_33_fu_857_p1));

assign add_ln87_7_fu_2127_p2 = ($signed(p_ZL10H_accu_FIR_8) + $signed(sext_ln87_8_reg_2998));

assign add_ln87_80_fu_1284_p2 = ($signed(p_ZL10H_accu_FIR_81) + $signed(sext_ln87_32_fu_847_p1));

assign add_ln87_81_fu_1294_p2 = ($signed(p_ZL10H_accu_FIR_82) + $signed(sext_ln87_31_fu_837_p1));

assign add_ln87_82_fu_1304_p2 = ($signed(p_ZL10H_accu_FIR_83) + $signed(sext_ln87_30_fu_827_p1));

assign add_ln87_83_fu_1314_p2 = ($signed(p_ZL10H_accu_FIR_84) + $signed(sext_ln87_29_fu_806_p1));

assign add_ln87_84_fu_1324_p2 = ($signed(p_ZL10H_accu_FIR_85) + $signed(sext_ln87_8_fu_537_p1));

assign add_ln87_85_fu_1334_p2 = ($signed(p_ZL10H_accu_FIR_86) + $signed(sext_ln87_28_fu_796_p1));

assign add_ln87_86_fu_1344_p2 = ($signed(p_ZL10H_accu_FIR_87) + $signed(sext_ln87_27_fu_786_p1));

assign add_ln87_87_fu_1354_p2 = ($signed(p_ZL10H_accu_FIR_88) + $signed(sext_ln87_26_fu_762_p1));

assign add_ln87_88_fu_1364_p2 = ($signed(p_ZL10H_accu_FIR_89) + $signed(sext_ln87_10_fu_583_p1));

assign add_ln87_89_fu_1374_p2 = ($signed(p_ZL10H_accu_FIR_90) + $signed(sext_ln87_25_fu_752_p1));

assign add_ln87_8_fu_2136_p2 = ($signed(p_ZL10H_accu_FIR_9) + $signed(sext_ln87_9_fu_2060_p1));

assign add_ln87_90_fu_1384_p2 = ($signed(p_ZL10H_accu_FIR_91) + $signed(sext_ln87_24_fu_742_p1));

assign add_ln87_91_fu_1394_p2 = ($signed(p_ZL10H_accu_FIR_92) + $signed(sext_ln87_23_fu_732_p1));

assign add_ln87_92_fu_1404_p2 = ($signed(p_ZL10H_accu_FIR_93) + $signed(sext_ln87_22_fu_722_p1));

assign add_ln87_93_fu_1414_p2 = ($signed(p_ZL10H_accu_FIR_94) + $signed(sext_ln87_21_fu_704_p1));

assign add_ln87_94_fu_1424_p2 = ($signed(p_ZL10H_accu_FIR_95) + $signed(sext_ln87_20_fu_694_p1));

assign add_ln87_95_fu_1434_p2 = ($signed(p_ZL10H_accu_FIR_96) + $signed(sext_ln87_19_fu_673_p1));

assign add_ln87_96_fu_1444_p2 = ($signed(p_ZL10H_accu_FIR_97) + $signed(sext_ln87_18_fu_663_p1));

assign add_ln87_97_fu_1454_p2 = ($signed(p_ZL10H_accu_FIR_98) + $signed(sext_ln87_17_fu_653_p1));

assign add_ln87_98_fu_1464_p2 = ($signed(p_ZL10H_accu_FIR_99) + $signed(sext_ln87_16_fu_643_p1));

assign add_ln87_99_fu_1474_p2 = ($signed(p_ZL10H_accu_FIR_100) + $signed(sext_ln87_15_fu_633_p1));

assign add_ln87_9_fu_2146_p2 = ($signed(p_ZL10H_accu_FIR_10) + $signed(sext_ln87_10_reg_3009));

assign add_ln87_fu_2036_p2 = ($signed(p_ZL10H_accu_FIR_1) + $signed(sext_ln87_fu_2033_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = {{add_ln84_fu_2014_p2[31:16]}};

assign grp_fu_2921_p1 = 32'd33914;

assign mul_ln87_10_fu_627_p0 = sext_ln84_8_fu_409_p1;

assign mul_ln87_10_fu_627_p1 = 25'd33554270;

assign mul_ln87_11_fu_637_p0 = sext_ln84_8_fu_409_p1;

assign mul_ln87_11_fu_637_p1 = 25'd33554274;

assign mul_ln87_12_fu_647_p0 = sext_ln84_8_fu_409_p1;

assign mul_ln87_12_fu_647_p1 = 25'd202;

assign mul_ln87_13_fu_657_p0 = sext_ln84_8_fu_409_p1;

assign mul_ln87_13_fu_657_p1 = 25'd152;

assign mul_ln87_14_fu_667_p0 = sext_ln84_8_fu_409_p1;

assign mul_ln87_14_fu_667_p1 = 25'd33554182;

assign mul_ln87_15_fu_698_p0 = sext_ln84_5_fu_400_p1;

assign mul_ln87_15_fu_698_p1 = 26'd298;

assign mul_ln87_16_fu_726_p0 = sext_ln84_5_fu_400_p1;

assign mul_ln87_16_fu_726_p1 = 26'd67108510;

assign mul_ln87_17_fu_736_p0 = sext_ln84_7_fu_406_p1;

assign mul_ln87_17_fu_736_p1 = 24'd16777114;

assign mul_ln87_18_fu_746_p0 = sext_ln84_5_fu_400_p1;

assign mul_ln87_18_fu_746_p1 = 26'd410;

assign mul_ln87_19_fu_756_p0 = sext_ln84_5_fu_400_p1;

assign mul_ln87_19_fu_756_p1 = 26'd67108392;

assign mul_ln87_1_fu_470_p0 = sext_ln84_7_fu_406_p1;

assign mul_ln87_1_fu_470_p1 = 24'd76;

assign mul_ln87_20_fu_790_p0 = sext_ln84_4_fu_397_p1;

assign mul_ln87_20_fu_790_p1 = 27'd532;

assign mul_ln87_21_fu_800_p0 = sext_ln84_4_fu_397_p1;

assign mul_ln87_21_fu_800_p1 = 27'd134217130;

assign mul_ln87_22_fu_831_p0 = sext_ln84_4_fu_397_p1;

assign mul_ln87_22_fu_831_p1 = 27'd660;

assign mul_ln87_23_fu_841_p0 = sext_ln84_8_fu_409_p1;

assign mul_ln87_23_fu_841_p1 = 25'd33554214;

assign mul_ln87_24_fu_851_p0 = sext_ln84_4_fu_397_p1;

assign mul_ln87_24_fu_851_p1 = 27'd134217002;

assign mul_ln87_25_fu_861_p0 = sext_ln84_5_fu_400_p1;

assign mul_ln87_25_fu_861_p1 = 26'd330;

assign mul_ln87_26_fu_871_p0 = sext_ln84_4_fu_397_p1;

assign mul_ln87_26_fu_871_p1 = 27'd786;

assign mul_ln87_27_fu_881_p0 = sext_ln84_5_fu_400_p1;

assign mul_ln87_27_fu_881_p1 = 26'd67108390;

assign mul_ln87_28_fu_891_p0 = sext_ln84_4_fu_397_p1;

assign mul_ln87_28_fu_891_p1 = 27'd134216880;

assign mul_ln87_29_fu_901_p0 = sext_ln84_4_fu_397_p1;

assign mul_ln87_29_fu_901_p1 = 27'd644;

assign mul_ln87_2_fu_501_p0 = sext_ln84_7_fu_406_p1;

assign mul_ln87_2_fu_501_p1 = 24'd16777106;

assign mul_ln87_30_fu_911_p0 = sext_ln84_4_fu_397_p1;

assign mul_ln87_30_fu_911_p1 = 27'd902;

assign mul_ln87_31_fu_921_p0 = sext_ln84_4_fu_397_p1;

assign mul_ln87_31_fu_921_p1 = 27'd134216868;

assign mul_ln87_32_fu_931_p0 = sext_ln84_4_fu_397_p1;

assign mul_ln87_32_fu_931_p1 = 27'd134216770;

assign mul_ln87_33_fu_941_p0 = sext_ln84_3_fu_394_p1;

assign mul_ln87_33_fu_941_p1 = 28'd1128;

assign mul_ln87_34_fu_951_p0 = sext_ln84_4_fu_397_p1;

assign mul_ln87_34_fu_951_p1 = 27'd1004;

assign mul_ln87_35_fu_961_p0 = sext_ln84_3_fu_394_p1;

assign mul_ln87_35_fu_961_p1 = 28'd268433972;

assign mul_ln87_36_fu_971_p0 = sext_ln84_3_fu_394_p1;

assign mul_ln87_36_fu_971_p1 = 28'd268434410;

assign mul_ln87_37_fu_981_p0 = sext_ln84_3_fu_394_p1;

assign mul_ln87_37_fu_981_p1 = 28'd1972;

assign mul_ln87_38_fu_991_p0 = sext_ln84_3_fu_394_p1;

assign mul_ln87_38_fu_991_p1 = 28'd1080;

assign mul_ln87_39_fu_1001_p0 = sext_ln84_2_fu_391_p1;

assign mul_ln87_39_fu_1001_p1 = 29'd536868204;

assign mul_ln87_3_fu_511_p1 = 22'd22;

assign mul_ln87_40_fu_1011_p0 = sext_ln84_3_fu_394_p1;

assign mul_ln87_40_fu_1011_p1 = 28'd268434346;

assign mul_ln87_41_fu_1021_p0 = sext_ln84_2_fu_391_p1;

assign mul_ln87_41_fu_1021_p1 = 29'd3974;

assign mul_ln87_42_fu_1031_p1 = 30'd1073734990;

assign mul_ln87_43_fu_1041_p0 = sext_ln84_3_fu_394_p1;

assign mul_ln87_43_fu_1041_p1 = 28'd268434312;

assign mul_ln87_44_fu_1051_p0 = sext_ln84_reg_2951_pp0_iter1_reg;

assign mul_ln87_44_fu_1051_p1 = 32'd20820;

assign mul_ln87_4_fu_521_p0 = sext_ln84_7_fu_406_p1;

assign mul_ln87_4_fu_521_p1 = 24'd110;

assign mul_ln87_5_fu_531_p1 = 23'd8388562;

assign mul_ln87_6_fu_587_p0 = sext_ln84_8_fu_409_p1;

assign mul_ln87_6_fu_587_p1 = 25'd138;

assign mul_ln87_7_fu_597_p0 = sext_ln84_7_fu_406_p1;

assign mul_ln87_7_fu_597_p1 = 24'd16777122;

assign mul_ln87_8_fu_607_p0 = sext_ln84_8_fu_409_p1;

assign mul_ln87_8_fu_607_p1 = 25'd33554282;

assign mul_ln87_9_fu_617_p0 = sext_ln84_8_fu_409_p1;

assign mul_ln87_9_fu_617_p1 = 25'd154;

assign mul_ln87_fu_443_p0 = sext_ln84_8_fu_409_p1;

assign mul_ln87_fu_443_p1 = 25'd33554222;

assign p_shl_fu_415_p3 = {{x_n_read_reg_2930_pp0_iter1_reg}, {7'd0}};

assign sext_ln84_10_fu_439_p1 = sub_ln84_fu_433_p2;

assign sext_ln84_11_fu_429_p1 = $signed(tmp_1_fu_422_p3);

assign sext_ln84_2_fu_391_p1 = x_n_read_reg_2930_pp0_iter1_reg;

assign sext_ln84_3_fu_394_p1 = x_n_read_reg_2930_pp0_iter1_reg;

assign sext_ln84_4_fu_397_p1 = x_n_read_reg_2930_pp0_iter1_reg;

assign sext_ln84_5_fu_400_p1 = x_n_read_reg_2930_pp0_iter1_reg;

assign sext_ln84_7_fu_406_p1 = x_n_read_reg_2930_pp0_iter1_reg;

assign sext_ln84_8_fu_409_p1 = x_n_read_reg_2930_pp0_iter1_reg;

assign sext_ln84_fu_384_p0 = x_n;

assign sext_ln84_fu_384_p1 = sext_ln84_fu_384_p0;

assign sext_ln87_10_fu_583_p1 = $signed(shl_ln87_1_fu_576_p3);

assign sext_ln87_11_fu_593_p1 = $signed(mul_ln87_6_fu_587_p2);

assign sext_ln87_12_fu_603_p1 = $signed(mul_ln87_7_fu_597_p2);

assign sext_ln87_13_fu_613_p1 = $signed(mul_ln87_8_fu_607_p2);

assign sext_ln87_14_fu_623_p1 = $signed(mul_ln87_9_fu_617_p2);

assign sext_ln87_15_fu_633_p1 = $signed(mul_ln87_10_fu_627_p2);

assign sext_ln87_16_fu_643_p1 = $signed(mul_ln87_11_fu_637_p2);

assign sext_ln87_17_fu_653_p1 = $signed(mul_ln87_12_fu_647_p2);

assign sext_ln87_18_fu_663_p1 = $signed(mul_ln87_13_fu_657_p2);

assign sext_ln87_19_fu_673_p1 = $signed(mul_ln87_14_fu_667_p2);

assign sext_ln87_1_fu_449_p1 = x_n_read_reg_2930_pp0_iter1_reg;

assign sext_ln87_20_fu_694_p1 = $signed(sub_ln87_4_fu_688_p2);

assign sext_ln87_21_fu_704_p1 = $signed(mul_ln87_15_fu_698_p2);

assign sext_ln87_22_fu_722_p1 = $signed(sub_ln87_5_fu_716_p2);

assign sext_ln87_23_fu_732_p1 = $signed(mul_ln87_16_fu_726_p2);

assign sext_ln87_24_fu_742_p1 = $signed(mul_ln87_17_fu_736_p2);

assign sext_ln87_25_fu_752_p1 = $signed(mul_ln87_18_fu_746_p2);

assign sext_ln87_26_fu_762_p1 = $signed(mul_ln87_19_fu_756_p2);

assign sext_ln87_27_fu_786_p1 = $signed(sub_ln87_7_fu_780_p2);

assign sext_ln87_28_fu_796_p1 = $signed(mul_ln87_20_fu_790_p2);

assign sext_ln87_29_fu_806_p1 = $signed(mul_ln87_21_fu_800_p2);

assign sext_ln87_2_fu_2042_p1 = tmp_reg_2968;

assign sext_ln87_30_fu_827_p1 = $signed(sub_ln87_8_fu_821_p2);

assign sext_ln87_31_fu_837_p1 = $signed(mul_ln87_22_fu_831_p2);

assign sext_ln87_32_fu_847_p1 = $signed(mul_ln87_23_fu_841_p2);

assign sext_ln87_33_fu_857_p1 = $signed(mul_ln87_24_fu_851_p2);

assign sext_ln87_34_fu_867_p1 = $signed(mul_ln87_25_fu_861_p2);

assign sext_ln87_35_fu_877_p1 = $signed(mul_ln87_26_fu_871_p2);

assign sext_ln87_36_fu_887_p1 = $signed(mul_ln87_27_fu_881_p2);

assign sext_ln87_37_fu_897_p1 = $signed(mul_ln87_28_fu_891_p2);

assign sext_ln87_38_fu_907_p1 = $signed(mul_ln87_29_fu_901_p2);

assign sext_ln87_39_fu_917_p1 = $signed(mul_ln87_30_fu_911_p2);

assign sext_ln87_3_fu_2045_p1 = mul_ln87_1_reg_2973;

assign sext_ln87_40_fu_927_p1 = $signed(mul_ln87_31_fu_921_p2);

assign sext_ln87_41_fu_937_p1 = $signed(mul_ln87_32_fu_931_p2);

assign sext_ln87_42_fu_947_p1 = $signed(mul_ln87_33_fu_941_p2);

assign sext_ln87_43_fu_957_p1 = $signed(mul_ln87_34_fu_951_p2);

assign sext_ln87_44_fu_967_p1 = $signed(mul_ln87_35_fu_961_p2);

assign sext_ln87_45_fu_977_p1 = $signed(mul_ln87_36_fu_971_p2);

assign sext_ln87_46_fu_987_p1 = $signed(mul_ln87_37_fu_981_p2);

assign sext_ln87_47_fu_997_p1 = $signed(mul_ln87_38_fu_991_p2);

assign sext_ln87_48_fu_1007_p1 = $signed(mul_ln87_39_fu_1001_p2);

assign sext_ln87_49_fu_1017_p1 = $signed(mul_ln87_40_fu_1011_p2);

assign sext_ln87_4_fu_2048_p1 = sub_ln87_1_reg_2978;

assign sext_ln87_50_fu_1027_p1 = $signed(mul_ln87_41_fu_1021_p2);

assign sext_ln87_51_fu_1037_p1 = $signed(mul_ln87_42_fu_1031_p2);

assign sext_ln87_52_fu_1047_p1 = $signed(mul_ln87_43_fu_1041_p2);

assign sext_ln87_53_fu_466_p1 = tmp_fu_458_p3;

assign sext_ln87_54_fu_1652_p0 = p_ZL10H_accu_FIR_115;

assign sext_ln87_54_fu_1652_p1 = sext_ln87_54_fu_1652_p0;

assign sext_ln87_55_fu_476_p1 = mul_ln87_1_fu_470_p2;

assign sext_ln87_56_fu_487_p1 = $signed(tmp_2_fu_480_p3);

assign sext_ln87_57_fu_497_p1 = sub_ln87_1_fu_491_p2;

assign sext_ln87_58_fu_507_p1 = mul_ln87_2_fu_501_p2;

assign sext_ln87_59_fu_517_p1 = mul_ln87_3_fu_511_p2;

assign sext_ln87_5_fu_2051_p1 = mul_ln87_2_reg_2983;

assign sext_ln87_60_fu_527_p1 = mul_ln87_4_fu_521_p2;

assign sext_ln87_61_fu_541_p1 = mul_ln87_5_fu_531_p2;

assign sext_ln87_62_fu_545_p1 = p_shl_fu_415_p3;

assign sext_ln87_63_fu_562_p1 = tmp_3_fu_555_p3;

assign sext_ln87_64_fu_572_p1 = sub_ln87_3_fu_566_p2;

assign sext_ln87_65_fu_684_p1 = tmp_4_fu_677_p3;

assign sext_ln87_66_fu_708_p1 = p_shl_fu_415_p3;

assign sext_ln87_67_fu_712_p1 = tmp_3_fu_555_p3;

assign sext_ln87_68_fu_766_p1 = tmp_4_fu_677_p3;

assign sext_ln87_69_fu_776_p1 = tmp_3_fu_555_p3;

assign sext_ln87_6_fu_2054_p1 = mul_ln87_3_reg_2988;

assign sext_ln87_70_fu_817_p1 = $signed(tmp_5_fu_810_p3);

assign sext_ln87_71_fu_1534_p0 = p_ZL10H_accu_FIR_106;

assign sext_ln87_71_fu_1534_p1 = sext_ln87_71_fu_1534_p0;

assign sext_ln87_72_fu_1548_p0 = p_ZL10H_accu_FIR_107;

assign sext_ln87_72_fu_1548_p1 = sext_ln87_72_fu_1548_p0;

assign sext_ln87_73_fu_1562_p0 = p_ZL10H_accu_FIR_108;

assign sext_ln87_73_fu_1562_p1 = sext_ln87_73_fu_1562_p0;

assign sext_ln87_74_fu_1576_p0 = p_ZL10H_accu_FIR_109;

assign sext_ln87_74_fu_1576_p1 = sext_ln87_74_fu_1576_p0;

assign sext_ln87_75_fu_1590_p0 = p_ZL10H_accu_FIR_110;

assign sext_ln87_75_fu_1590_p1 = sext_ln87_75_fu_1590_p0;

assign sext_ln87_76_fu_1604_p0 = p_ZL10H_accu_FIR_111;

assign sext_ln87_76_fu_1604_p1 = sext_ln87_76_fu_1604_p0;

assign sext_ln87_77_fu_1628_p0 = p_ZL10H_accu_FIR_113;

assign sext_ln87_77_fu_1628_p1 = sext_ln87_77_fu_1628_p0;

assign sext_ln87_7_fu_2057_p1 = mul_ln87_4_reg_2993;

assign sext_ln87_8_fu_537_p1 = mul_ln87_5_fu_531_p2;

assign sext_ln87_9_fu_2060_p1 = sub_ln87_3_reg_3004;

assign sext_ln87_fu_2033_p1 = mul_ln87_reg_2963;

assign shl_ln87_1_fu_576_p3 = {{x_n_read_reg_2930_pp0_iter1_reg}, {6'd0}};

assign sub_ln84_fu_433_p2 = ($signed(p_shl_fu_415_p3) - $signed(sext_ln84_11_fu_429_p1));

assign sub_ln87_1_fu_491_p2 = ($signed(22'd0) - $signed(sext_ln87_56_fu_487_p1));

assign sub_ln87_2_fu_549_p2 = ($signed(25'd0) - $signed(sext_ln87_62_fu_545_p1));

assign sub_ln87_3_fu_566_p2 = ($signed(sub_ln87_2_fu_549_p2) - $signed(sext_ln87_63_fu_562_p1));

assign sub_ln87_4_fu_688_p2 = ($signed(sub_ln87_2_fu_549_p2) - $signed(sext_ln87_65_fu_684_p1));

assign sub_ln87_5_fu_716_p2 = ($signed(sext_ln87_66_fu_708_p1) - $signed(sext_ln87_67_fu_712_p1));

assign sub_ln87_6_fu_770_p2 = ($signed(22'd0) - $signed(sext_ln87_68_fu_766_p1));

assign sub_ln87_7_fu_780_p2 = ($signed(sub_ln87_6_fu_770_p2) - $signed(sext_ln87_69_fu_776_p1));

assign sub_ln87_8_fu_821_p2 = ($signed(sext_ln87_66_fu_708_p1) - $signed(sext_ln87_70_fu_817_p1));

assign sub_ln87_fu_452_p2 = ($signed(17'd0) - $signed(sext_ln87_1_fu_449_p1));

assign tmp_1_fu_422_p3 = {{x_n_read_reg_2930_pp0_iter1_reg}, {2'd0}};

assign tmp_2_fu_480_p3 = {{x_n_read_reg_2930_pp0_iter1_reg}, {5'd0}};

assign tmp_3_fu_555_p3 = {{x_n_read_reg_2930_pp0_iter1_reg}, {1'd0}};

assign tmp_4_fu_677_p3 = {{x_n_read_reg_2930_pp0_iter1_reg}, {4'd0}};

assign tmp_5_fu_810_p3 = {{x_n_read_reg_2930_pp0_iter1_reg}, {3'd0}};

assign tmp_fu_458_p3 = {{sub_ln87_fu_452_p2}, {1'd0}};

always @ (posedge ap_clk) begin
    p_ZL10H_accu_FIR_115[1:0] <= 2'b00;
    sext_ln84_10_reg_2957[1:0] <= 2'b00;
    tmp_reg_2968[0] <= 1'b0;
    sub_ln87_1_reg_2978[4:0] <= 5'b00000;
    sub_ln87_3_reg_3004[0] <= 1'b0;
    sext_ln87_10_reg_3009[5:0] <= 6'b000000;
    sext_ln87_20_reg_3060[3:0] <= 4'b0000;
    sext_ln87_22_reg_3070[0] <= 1'b0;
    sext_ln87_27_reg_3095[0] <= 1'b0;
    sext_ln87_30_reg_3110[2:0] <= 3'b000;
end

endmodule //Multirate_v2_FIR_filter_transposed
